MudBlazor/MudBlazor

src/MudBlazor.Docs/Shared/MainLayout.razor, src/MudBlazor/Components/Button/Button.razor.cs, src/MudBlazor/Components/Button/IconButton.razor.cs, src/MudBlazor/Components/Link/MudLink.razor, src/MudBlazor/Components/Link/MudLink.razor.cs
Also made the link to the github page open in a new tab.
=> Added Target property to Button, IconButton and Link

src/MudBlazor/Components/Select/MudSelect.razor
This PR fixes fixes Select not passing Error to underlying input
=> Fixed Select not passing Error to underlying input

src/MudBlazor/Components/TextField/MudTextField.razor
This PR fixes fixes TextField not passing Error to underlying input
=> Fixed TextField not passing Error to underlying input

src/MudBlazor/Base/MudBaseButton.cs, src/MudBlazor/Components/Button/MudButton.razor, src/MudBlazor/Components/Button/MudFab.razor, src/MudBlazor/Components/Button/MudIconButton.razor, src/MudBlazor/Enums/ButtonType.cs, src/MudBlazor/Extensions/EnumExtensions.cs, src/MudBlazor/MudBlazor.xml
This PR adds a ButtonType parameter which is needed for Forms.
=> Added Button Type

src/MudBlazor.Docs/Components/DocsIcons.razor, src/MudBlazor.Docs/Pages/Components/MudIcons/MudIconsPage.razor, src/MudBlazor.Docs/Style/Components/_icons.scss
MudDocs - Allow search and choose type material icons
=> docs-feature - search material Icons

.gitignore
A handy change for people using the VS extension Local History
=> Added VS extension temp directory .history to gitignore

src/MudBlazor.UnitTests/Utilities/BindingConverterTests.cs
=> Added unit tests for DateConverter and NullableDateConverter.

src/MudBlazor.Docs.Client/Program.cs
Nice project!
Tried out the client application in your master branch. Would crash when switching pages. Fixed it by registering the same service as the server application registers.
=> Fix client example crash when switching pages

src/MudBlazor.Docs/Pages/Components/Form/FormPage.razor, src/MudBlazor.Docs/Shared/NavMenu.razor
Issue also occurs on the live website, the examples link is broken in the API docs.
How would you like pull requests, only for your develop branch, or for the master branch as well?
=> Fixed the broken form links.

src/MudBlazor.Docs/Data/Element.cs, src/MudBlazor.Docs/Models/DocStrings.generated.cs, src/MudBlazor.Docs/Models/Snippets.generated.cs, src/MudBlazor.Docs/MudBlazor.Docs.csproj, src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor, src/MudBlazor.Docs/Pages/Components/Autocomplete/Code/AutocompleteClrObjectsExampleCode.razor, src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteClrObjectsExample.razor, src/MudBlazor.UnitTests/Components/_AllComponents.cs, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
- Added an example with Binding to a POCO class (Element, from Periodic Table);
- Added handler for OnBlurred for Text coercion. It syncs Text property to the current Value.
Thanks again to @henon for the help.
=> MudAutoComplete extensions

src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsWithBagdesExample.razor, src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor, src/MudBlazor/Components/Tabs/MudTabPanel.razor, src/MudBlazor/Components/Tabs/MudTabs.razor, src/MudBlazor/MudBlazor.xml, src/MudBlazor/compilerconfig.json
Initial work to add MudBadge on MudTabPanel
=> Initial work to add MudBadge on MudTabPanel

src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest2.razor, src/MudBlazor.UnitTests/Components/AutocompleteTests.cs, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
=> Fixes AutoComplete popup with MinCharacters

src/MudBlazor/Base/MudBaseInput.cs, src/MudBlazor/MudBlazor.xml
This PR allows realtime validation with EditForm
=> Added EditContext based validation on input

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor, src/MudBlazor/Components/Input/MudInput.razor, src/MudBlazor/Components/Select/MudSelect.razor, src/MudBlazor/Components/TextField/MudTextField.razor, src/MudBlazor/MudBlazor.xml
The previous pullrequest does not compile because I forgot to update the reference variable names in the razor files.
This should fix it.
=> Fixed ref variable names

.vscode/launch.json, .vscode/tasks.json, src/MudBlazor.UnitTests.Viewer/Properties/launchSettings.json, src/MudBlazor/compilerconfig.build.files.conf, src/MudBlazor/compilerconfig.build.json
Tested on
vscode - macOS
vscode - win10
visual studio 2019 - win10
=> Fixes #214 vscode build tasks

src/MudBlazor/Styles/components/_select.scss
=> Prevent MudSelect from collapsing

src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
Missed it sorry.
Just docs though
=> Fix Type in Component in Docs

src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj, src/MudBlazor.Docs/Models/DocStrings.generated.cs, src/MudBlazor.Docs/Models/Snippets.generated.cs, src/MudBlazor.Docs/MudBlazor.Docs.csproj, src/MudBlazor.Docs/Pages/Components/Checkbox/Code/CheckboxConversionExampleCode.razor, src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxConversionExample.razor, src/MudBlazor.Docs/Pages/Components/Switch/Code/SwitchConversionExampleCode.razor, src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchConversionExample.razor, src/MudBlazor/Base/MudBooleanInput.cs
It allows some customization on binding models to any MudBooleanInput.
=> Converter Property for MudBooleanInput

src/MudBlazor/Components/TimeLine/MudTimeLine.razor, src/MudBlazor/Components/TimeLine/MudTimeLine.razor.cs, src/MudBlazor/Components/TimeLine/MudTimeLineItem.razor, src/MudBlazor/Components/TimeLine/MudTimeLineItem.razor.cs, src/MudBlazor/Styles/MudBlazor.scss, src/MudBlazor/Styles/components/_timeline.scss
First attempt on creating a Time Line component.
@Garderoben will work on necessary css and layout.
Reference: https://vuetifyjs.com/en/components/timelines/
=> MudTimeLine Component (WIP)

.vscode/launch.json, .vscode/tasks.json
So vscode users can run the docs sites
=> Add some useful vscode tasks

src/MudBlazor.UnitTests/Components/HighlighterTests.cs
Added some tests to check the markup of the highlighter under several conditions
=> Added Mudhighlighter tests

CHANGELOG.md
Prevent this file becoming stale or out of sync.
=> Fixes #233 - Changelog link to releases

src/MudBlazor.Docs/Components/SectionSource.razor, src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderStepsExample.razor, src/MudBlazor.Docs/Pages/Components/Table/Examples/TableExample.razor, src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor, src/MudBlazor.Docs/Pages/Project/Team.razor, src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj, src/MudBlazor.UnitTests/Utilities/StyleBuilderTests.cs, src/MudBlazor/Base/MudBaseInput.cs, src/MudBlazor/Base/MudFormComponent.cs, src/MudBlazor/Components/Chart/MudChart.razor.cs, src/MudBlazor/Services/ResizeListener/ServiceCollectionExtensions.cs, src/MudBlazor/Utilities/BindingConverters/DefaultConverter.cs, src/MudBlazor/Utilities/ColorTransformation.cs, src/MudBlazor/Utilities/CssBuilder.cs, src/MudBlazor/Utilities/StyleBuilder.cs
I know @Garderoben is not too worried about these but I think its good to fix the easy ones.
I have only done straightforward low risk ones.
=> Fix compiler warnings

src/MudBlazor/Styles/core/_base.scss
Please check carefully.
Discussed at length with @henon @porkopek 
Feel free to discuss.
Also need to remove <app> from MudBlazorTemplates
=> Fixes #263 - MudLayout inside div (block)

src/MudBlazor/Components/Picker/MudPicker.razor
Picker adorement click should toggle picker overlay
Try it here: https://mudblazor.com/components/timepicker
The click on the icon does not trigger the toggle
=> Trigger toggle on picker adorement click

src/MudBlazor.Docs/MudBlazor.Docs.csproj
- Cope with spaces in repo path
- Reported by @porkopek 
@henon
=> Fix docs compiler in path with space

src/MudBlazor.Docs/Pages/Components/Button/Code/ButtonLinkExampleCode.razor
-  checkin for now to avoid coming up in changes for everyone
- we will `.gitignore` these soon as they are always recreated if needed
=> Update generated doc

src/MudBlazor/Base/MudBaseButton.cs, src/MudBlazor/Components/Button/MudButton.razor, src/MudBlazor/Components/Button/MudFab.razor, src/MudBlazor/Components/Button/MudIconButton.razor, src/MudBlazor/Components/Button/MudToggleIconButton.razor, src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
Buttons should also be focusable as they are form elements.
Implemented method FocusAsync for the Mud variants of buttons
=> Focus for buttons (net5)

src/MudBlazor.Docs.Client/MudBlazor.Docs.Client.csproj, src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
-  Fix SDK on unit test viewer (not launching)
-  Remove razor language version as per MS recommendations
=> Fix UnitTests.Viewer and remove razor version

src/MudBlazor.Docs/Pages/Components/Dialog/Code/DialogOptionsExampleCode.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Code/DialogPassingDataExample_DialogCode.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Code/DialogTemplateExampleCode.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Code/DialogUsageExampleCode.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogOptionsExample.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogPassingDataExample_Dialog.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogTemplateExample.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogUsageExample.razor, src/MudBlazor.UnitTests/Components/DatePickerTests.cs, src/MudBlazor.UnitTests/Components/FormTests.cs, src/MudBlazor.UnitTests/Components/SelectTests.cs, src/MudBlazor.UnitTests/Components/ToggleIconButtonTest.cs, src/MudBlazor.UnitTests/Mocks/MockHeadElementHelper.cs, src/MudBlazor.UnitTests/Mocks/MockResizeListenerService.cs, src/MudBlazor/Components/DatePicker/MudDatePicker.razor.cs, src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
- This is a code quality PR
- It doesn't touch any public API.
- It corrects a few of the examples, tests and private library code.  
- We shouldn't be using async incorrectly in examples as it is public facing.
=> Fix CS1998 incorrect async usage

src/MudBlazor.Docs.Client/wwwroot/index.html, src/MudBlazor.Docs.Server/Pages/_Host.cshtml, src/MudBlazor.Docs/Pages/Components/Element/Code/MudElementRefExampleCode.razor, src/MudBlazor.Docs/Pages/Components/Element/ElementPage.razor, src/MudBlazor.Docs/Pages/Components/Element/Examples/MudElementRefExample.razor, src/MudBlazor.Docs/wwwroot/JS/examples.js, src/MudBlazor/Components/Button/MudButton.razor, src/MudBlazor/Components/Button/MudFab.razor, src/MudBlazor/Components/Button/MudIconButton.razor, src/MudBlazor/Components/Element/MudElement.cs
- Add @porkopek Ref binding for `MudElement` to net5 branch.
- Remove TODOs
- @henon
=> Added MudElement reference two-way binding

src/MudBlazor.UnitTests/Mocks/MockHeadElementHelper.cs, src/MudBlazor.UnitTests/Mocks/MockResizeListenerService.cs
=> Fix restore pragma warning

src/MudBlazor/Components/Button/MudButton.razor, src/MudBlazor/Components/Button/MudFab.razor, src/MudBlazor/Components/Button/MudIconButton.razor
ref in MudElement needs to be bound
=> Changed from ref to bind-ref in MudElement in buttons

src/MudBlazor.Docs/Pages/Components/Dialog/Code/DialogPassingDataExample_DialogCode.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogPassingDataExample_Dialog.razor, src/MudBlazor.Docs/Pages/Components/Overlay/Code/OverlayUsageExampleCode.razor, src/MudBlazor.Docs/Pages/Components/Overlay/Code/OverlayZIndexExampleCode.razor, src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayUsageExample.razor, src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayZIndexExample.razor, src/MudBlazor/Base/MudFormComponent.cs, src/MudBlazor/Components/Alert/MudAlert.razor.cs
=> Fix various compiler warnings

src/MudBlazor.Docs.Compiler/TestsForApiPages.cs, src/MudBlazor.Docs.Compiler/TestsForExamples.cs, src/MudBlazor.UnitTests/Components/AutocompleteTests.cs, src/MudBlazor.UnitTests/Components/FormTests.cs, src/MudBlazor.UnitTests/Components/SelectTests.cs, src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
- @henon please can you check why the rendercount changed
- This also fixes the find element bug in net5 (tested)
=> Upgrade bunit

src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerBasicUsageExample.razor, src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerBasicUsageExample.razor, src/MudBlazor/Base/MudBasePicker.cs, src/MudBlazor/Components/DatePicker/MudDatePicker.razor, src/MudBlazor/Components/Picker/MudPicker.razor, src/MudBlazor/Components/TimePicker/MudTimePicker.razor, src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs, src/MudBlazor/Components/TimePicker/MudTimePickerDial.razor, src/MudBlazor/Styles/components/_pickertime.scss
Some date and time picker fixes for issues: #308 #301 
Changes:
- Added animation to time picker
- switch to minutes after hour is selected
- changed `MudBasePicker`, added a  readonly attribute. This enables to type the required data/time directly
=> Date and time picker fixes

src/MudBlazor.Docs.Compiler/CodeBuilder.cs, src/MudBlazor.Docs.Compiler/TestsForExamples.cs
- Added some MudBlazor.Providers for DatePicker tests
- Added AddOptions() to the IServiceCollection for Upload sample in net5 so I don't forget later on merge
=> Update automated test dependencies

src/MudBlazor.UnitTests/Mocks/MockResizeListenerService.cs, src/MudBlazor.UnitTests/Mocks/MockSnackbar.cs
- Thanks for your patience 😄 .  There has been some good refactoring on this and its not all about silencing them.
- The only remaining ones are 3 in https://github.com/Garderoben/MudBlazor/issues/404.  They may need some redesign of the table context so are less straight forward.   Will liase with @henon as it is one of his original components.
=> Fix Compiler warnings - nearly there

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableSingleSelectionTest1.razor, src/MudBlazor.UnitTests/Components/TableTests.cs, src/MudBlazor/Components/Table/MudTable.razor
- My first table test. 
- Please feel free to advise on style/execution.
=> Add a table test for single select

src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
- Comment out unused variable (compiler warning).  It seems breakpoints in themes is not implemented yet.
=> Comment out unused variable. Make const.

src/MudBlazor/Base/MudBaseButton.cs
=> Initialize RetainFocusOnClick to true by default

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePagingTest1.razor, src/MudBlazor.UnitTests/Components/TableTests.cs, src/MudBlazor/Components/Table/MudTable.razor.cs, src/MudBlazor/Components/Table/MudTableBase.cs
- Add 4 paging tests
- Fix pager State notification thanks @henon 
- Fix pager invalid current page on. filter.
=> Add some table paging tests

.vscode/tasks.json, src/MudBlazor.UnitTests/Components/TableTests.cs
- Just testing my ability to increase test coverage
- This test is for the rare senario that the SelectedItems collection is set to null
- Also added historic analysis to track improvement in code coverage
=> Table coverage

src/MudBlazor/Base/MudFormComponent.cs
=> Fixes #463 malformed doc comment

src/MudBlazor.UnitTests.Viewer/TestComponents/TimePicker/TimePickerTest1.razor, src/MudBlazor.UnitTests/Components/TimePickerTests.cs, src/MudBlazor/Components/TimePicker/MudTimePicker.razor, src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs, src/MudBlazor/Enums/OpenToView.cs
- Some time picker tests (probably too many :).  Will refactor later.
- Coverage at 97.7% (a challenge for some one)
- Fixed a bug with dragging minutes hand switches to hours due to OpenTo parameter and re-rendering
=> Timepicker tests

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
=> Date Picker Tests

src/MudBlazor/Components/Dialog/MudDialog.razor, src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor, src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor.cs, src/MudBlazor/Extensions/TaskExtensions.cs, src/MudBlazor/TScripts/elementReference.js
=> New focus trap component

src/MudBlazor/Base/MudBaseButton.cs, src/MudBlazor/Components/Button/MudButton.razor, src/MudBlazor/Components/Button/MudFab.razor, src/MudBlazor/Components/Button/MudIconButton.razor, src/MudBlazor/TScripts/elementReference.js
=> Remove RetainFocusOnClick

src/MudBlazor.UnitTests/Components/TimePickerTests.cs
- Same treatment as DatePicker tests
- Remove boiler plate
- Test name as description
=> Refactor Timepicker Tests

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
- Increase coverage of datepicker
- Refactor boiler plate
- New naming delete summaries.  Having the test as the description means failures are easier to identify.  Summary is not shown in test runners build systems etc
=> Datepicker tests

src/MudBlazor/Styles/components/_select.scss
=> Autocomplete in expansion panel

src/MudBlazor.Docs.Compiler/TestsForApiPages.cs, src/MudBlazor.Docs.Compiler/TestsForExamples.cs, src/MudBlazor.UnitTests.Viewer/Program.cs, src/MudBlazor.UnitTests/Extensions/TestContextExtensions.cs, src/MudBlazor.UnitTests/Mocks/MockBrowserWindowSizeProvider.cs, src/MudBlazor/Components/Picker/MudPicker.razor, src/MudBlazor/Components/Picker/MudPicker.razor.cs, src/MudBlazor/Interop/BoundingClientRect.cs, src/MudBlazor/Styles/components/_picker.scss, src/MudBlazor/TScripts/DOM.js
- Fixes #267 
- This is @tungi52's work thank you 🙏 https://github.com/Garderoben/MudBlazor/pull/438
- I am resubmitting because I wanted to oversee the merge conflicts
- I would like @tungi52 to sign off
=> Fixes  #267 picker position

src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
- New version fixes some bugs.
- No impact on library or docs.
=> Update Coverage reporting

src/MudBlazor/Services/DialogService.cs
There is no corresponding method declaration in IDialogService interface
=> Remove unused ShowMessageBox from DialogService class

src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/DragAndDropFileUploadExample.razor, src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadIconButtonExample.razor, src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadValidationExample.razor, src/MudBlazor.Docs/Pages/Components/FileUpload/FileUploadPage.razor
- Added a Drag and Drop example
- Added a example on how to validate the files type
=> FileUpload Drag and Drop and Validation examples

src/MudBlazor/Components/Tabs/MudTabPanel.razor, src/MudBlazor/Components/Tabs/MudTabs.razor.cs
=> MudTabs fix

src/MudBlazor.Docs/Pages/Components/Badge/Examples/BadgeInteractiveExample.razor, src/MudBlazor/Components/Badge/MudBadge.razor.cs
This PR proposes some small improvements to the badge component:
-Avoid string interpolation for simple concatenation (better performance)
-Added some precisions to property descriptions (supported content types, etc)
-Use pattern matching for content type detection
-Make sure non-supported Content type results to a null content in component (could have displayed incorrect content in the rare cases where content type changed from supported type to non-supported type)
-Removed unnecessary StateHasChanged call in doc example
=> Some badge improvements

src/MudBlazor/Components/Avatar/MudAvatar.razor, src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
The code was directly in the razor file so I moved it to a .cs file
=> Add missing code-behind file of Avatar component

src/MudBlazor/Base/MudBasePicker.cs, src/MudBlazor/Base/MudBaseSelectItem.cs
As the title says, fixed async calls in some base components. Also made some improvements to keep implementations details inside the class, state management, event catch-and-modify, etc.
=> Fix async calls in BaseSelectItem

src/MudBlazor/Components/Tabs/MudTabs.razor, src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Add possibility to declare custom classes on ChildContent host of MudTabs.
=> [MudTabs] Custom class parameter for panel content host.

src/.editorconfig
- For some reason this didn't come with the merge
=> Apply same coding standards to net5

.gitignore, src/MudBlazor.Docs.Compiler/TestsForExamples.cs, src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadButtonExample.razor, src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadIconButtonExample.razor, src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadValidationExample.razor
- To make it easier to see the important bits
=> Reduce unimportant diff

src/MudBlazor/Styles/components/_input.scss, src/MudBlazor/Styles/components/_list.scss
- Style change in net5 override with develop
=> Style diff accept develop version

src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
=> Align packages with net5

src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
- These packages run tests fine
=> Move away from  pre-released packages

src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor, src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxReadOnlyExample.razor, src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchReadOnlyExample.razor, src/MudBlazor.Docs/Pages/Components/Switch/SwitchPage.razor, src/MudBlazor/Base/MudBooleanInput.cs, src/MudBlazor/Components/CheckBox/MudCheckBox.razor, src/MudBlazor/Components/Switch/MudSwitch.razor
=> ReadOnly for CheckBox & Switch (#537)

src/MudBlazor/Components/List/MudListItem.razor
=> Remove ripplet

src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/DragAndDropFileUploadExample.razor, src/MudBlazor/Base/MudBaseButton.cs, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs, src/MudBlazor/Components/Button/MudButton.razor, src/MudBlazor/Components/Button/MudFab.razor, src/MudBlazor/Components/Button/MudIconButton.razor, src/MudBlazor/Components/Input/MudInput.razor, src/MudBlazor/Components/Input/MudInput.razor.cs, src/MudBlazor/Components/Select/MudSelect.razor, src/MudBlazor/Components/Select/MudSelect.razor.cs, src/MudBlazor/Components/TextField/MudTextField.razor, src/MudBlazor/Components/TextField/MudTextField.razor.cs
- This adds ElementReference without functionality so the diff is much easier for moving to net5
@henon
=> Add ElementReference to components

src/.editorconfig
=> Demote readonoly warning to suggestion

src/MudBlazor/Components/TreeView/MudTreeView.razor.cs, src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs, src/MudBlazor/Components/TreeView/MudTreeViewItemBuilder.razor.cs
-  Was waiting till after merge so didn't conflict please merge to net5 aswell
-
=> Refactor Treeview after PR

src/MudBlazor/Components/TreeView/MudTreeView.razor.cs, src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs, src/MudBlazor/Components/TreeView/MudTreeViewItemBuilder.razor.cs
=> Treeview diff net5

src/MudBlazor/Base/MudBasePicker.cs, src/MudBlazor/Components/Picker/MudPicker.razor.cs
As discussed in #522 here's the PR for BasePicker.
=> Fix async calls in BasePicker

src/MudBlazor.Docs/Pages/Components/ScrollToTop/ScrollToTopPage.razor
- No longer required with AddMudServices()
@porkopek
=> Remove services docs from ScrollToTop

src/MudBlazor.Docs/Components/MudBlazorApp/CalculatorApp/Expression.cs, src/MudBlazor.Docs/Components/MudBlazorApp/CalculatorApp/SimpleParser.cs, src/MudBlazor.Docs/Data/PeriodicTable.cs, src/MudBlazor.Docs/Models/ApiLink.cs, src/MudBlazor/Components/Badge/MudBadge.razor, src/MudBlazor/Components/Badge/MudBadge.razor.cs, src/MudBlazor/Components/Button/MudFab.razor.cs, src/MudBlazor/Components/Chart/Charts/Line.razor.cs, src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs, src/MudBlazor/Components/Dialog/MudDialogProvider.razor, src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs, src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs, src/MudBlazor/Components/Skeleton/MudSkeleton.razor, src/MudBlazor/Components/Skeleton/MudSkeleton.razor.cs, src/MudBlazor/Components/Snackbar/State.cs, src/MudBlazor/Components/Table/MudTableBase.cs, src/MudBlazor/Components/Table/TableContext.cs, src/MudBlazor/Components/Table/TableRowValidator.cs, src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs, src/MudBlazor/Components/TreeView/MudTreeView.razor.cs, src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs, src/MudBlazor/Extensions/DateTimeExtensions.cs, src/MudBlazor/Services/DialogService.cs, src/MudBlazor/Services/ServiceConfiguration.cs, src/MudBlazor/Utilities/BindingConverters/DefaultConverter.cs, src/MudBlazor/Utilities/BindingConverters/NumericConverter.cs
- Using the opportunity while its quiet.
=> Refactoring accord to our rules

src/MudBlazor.Docs/.config/dotnet-tools.json, src/MudBlazor.Docs/MudBlazor.Docs.csproj, src/MudBlazor.Docs/excubowebcompiler.json, src/MudBlazor/.config/dotnet-tools.json, src/MudBlazor/MudBlazor.csproj, src/MudBlazor/excubowebcompiler.json
- For @Garderoben to look at why scss compilation is differing from the extension.
=> Add back excubo webcompiler config file

src/MudBlazor.Docs/Pages/Components/IconButton/IconButtonPage.razor
- Looks like someone got half way through adding toggle button to icon button page
- Toggle button has its own page
=> Remove incorrect toggle button example

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor, src/MudBlazor/Components/Collapse/MudCollapse.razor, src/MudBlazor/Components/Collapse/MudCollapse.razor.cs, src/MudBlazor/Styles/components/_collapse.scss, src/MudBlazor/Styles/components/_popover.scss, src/MudBlazor/Styles/components/_select.scss
- fix for issue #205 
- fix decimal-string conversion in MudCollapse
=> fix select popup in expansion panel

src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
- As discussed with @Garderoben 
- He has asked I could do the change
=> Revert readonly  and PascalCase const

src/MudBlazor.UnitTests/Components/BreadcrumbTests.cs, src/MudBlazor.UnitTests/Components/TimePickerTests.cs, src/MudBlazor/Components/Chart/Charts/Bar.razor, src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
=> Bar to partial Test IDE1006

src/MudBlazor/Components/Card/MudCard.razor, src/MudBlazor/Components/Card/MudCard.razor.cs, src/MudBlazor/Components/Card/MudCardActions.razor, src/MudBlazor/Components/Card/MudCardActions.razor.cs, src/MudBlazor/Components/Card/MudCardContent.razor, src/MudBlazor/Components/Card/MudCardContent.razor.cs, src/MudBlazor/Components/Card/MudCardHeader.razor, src/MudBlazor/Components/Card/MudCardHeader.razor.cs
The code was directly in the razor files so I moved it to .cs files
=> Add missing code-behind file of Card components

src/MudBlazor.Docs/Pages/Components/ButtonFAB/Examples/FabSizeExample.razor, src/MudBlazor/Components/Button/MudFab.razor, src/MudBlazor/Components/Button/MudFab.razor.cs
=> Added IconSize parameter to MudFab and examples for using it.

.vscode/launch.json
- Was pointing to netcore3.1 binary
=> FIx vscode launch task for net5

src/MudBlazor/Components/Input/MudDebouncedInput.cs
Because the internal timer was set in SetParameters hook, it was recreated each time new parameter values were set in the component.
So, for example, timer was recreated on each key stroke in the debounced doc example, and previous timer was not disposed.
This new version:
-only creates a timer when there is not already one
-disposes the existing timer if DebounceInterval is reset to zero (or component itself is disposed, of course)
-properly update the input Value if DebounceInterval is reset to zero while timer was running
-updates the existing timer interval if DebounceInterval value is modified
-ignores negative DebounceInterval values
=> Fix timer leak in debounced input component

src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs, src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor.cs, src/MudBlazor/Components/Select/MudSelect.razor, src/MudBlazor/Components/Select/MudSelect.razor.cs
- Remove unused code
- Rename field
=> Refactorings

src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarHtmlInMessageExample.razor, src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor, src/MudBlazor.UnitTests/Components/SnackbarTests.cs, src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
=> Render Snackbar messages using MarkupString for HTML Support

src/MudBlazor.UnitTests/Components/TreeViewTest.cs, src/MudBlazor/Components/Collapse/MudCollapse.razor, src/MudBlazor/Components/Collapse/MudCollapse.razor.cs, src/MudBlazor/Styles/components/_collapse.scss, src/MudBlazor/TScripts/DOM.js
Fix previously messed up collapse animation.
=> Collapse fix

src/MudBlazor/Styles/components/_slider.scss
- Fixes https://github.com/Garderoben/MudBlazor/issues/630
=> Fix blank slider on firefox

src/MudBlazor.UnitTests/Components/TableTests.cs
=> Remove service already included in TestContext

src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuTest1.razor, src/MudBlazor.UnitTests/Components/DatePickerTests.cs, src/MudBlazor.UnitTests/Components/MenuTests.cs, src/MudBlazor.UnitTests/Components/TimePickerTests.cs, src/MudBlazor/Components/List/MudListItem.razor.cs
- Also fix some formatting
- Fix #576 Menu not closing
=> Add a menu Test

src/MudBlazor.UnitTests/Utilities/BindingConverterTests.cs, src/MudBlazor/Utilities/BindingConverters/DefaultConverter.cs
-  Add more type tests for full coverage
- Fix TimeSpan (non-nullable version)
- Fix return logic Default(T) is always returned.
- Add Exception testing
=> Add more tests to Converters

src/MudBlazor.Docs/MudBlazor.Docs.csproj, src/MudBlazor/MudBlazor.csproj
- As described dotnet tool update seems slower
=> Revert dotnet tool restore for build speed

src/MudBlazor.Docs/excubowebcompiler.json, src/MudBlazor/excubowebcompiler.json
- Urgent please - surprised no one has come across this yet.  The minification was shortening the variables which we cant do
=> Fix JS minification

src/MudBlazor.Docs.Client/MudBlazor.Docs.Client.csproj, src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj, src/MudBlazor/MudBlazor.csproj
- `MudBlazor.csproj` reference should be taken by `MudBlazor.Docs.csproj`
- Tidy up
=> Small project tidy up

src/MudBlazor/Styles/components/_popover.scss
Related to comments in https://github.com/Garderoben/MudBlazor/issues/256
=> Allow Direction.Right and OffsetY

src/MudBlazor.UnitTests.Viewer/TestComponents/ToggleIconButton/ToggleIconButtonTest1.razor, src/MudBlazor.UnitTests/Components/ToggleIconButtonTest.cs
=> Add sync test for ToggleIconButon

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs, src/MudBlazor.UnitTests/Components/ChipSetTests.cs, src/MudBlazor.UnitTests/Components/DatePickerTests.cs, src/MudBlazor.UnitTests/Components/DateRangePickerTests .cs, src/MudBlazor.UnitTests/Components/SelectTests.cs, src/MudBlazor.UnitTests/Components/TableTests.cs, src/MudBlazor.UnitTests/Components/TextFieldTests.cs, src/MudBlazor.UnitTests/Components/TimePickerTests.cs, src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
- As per #673 
- Move in prep for fixing warnings
=> Move suppression BL0005

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs, src/MudBlazor.UnitTests/Components/ChipSetTests.cs, src/MudBlazor.UnitTests/Components/FormTests.cs, src/MudBlazor.UnitTests/Components/SelectTests.cs, src/MudBlazor.UnitTests/Extensions/IRenderedComponentExtensions.cs, src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs, src/MudBlazor/Components/Input/MudDebouncedInput.cs, src/MudBlazor/Components/Radio/MudRadio.razor.cs, src/MudBlazor/Services/DomService.cs
- Do we want to automate this?
=> dotnet format

src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs, src/MudBlazor/Components/DatePicker/MudDatePicker.cs
=> Use DefaultConverter<DateTime?> in Date Pickers

src/.editorconfig
- 2 rules I cant bring myself to refactor because I think they make the code less readable.
=> Add more exceptions to code rules

src/MudBlazor.UnitTests/Components/DatePickerTests.cs, src/MudBlazor.UnitTests/Components/SelectTests.cs, src/MudBlazor/Base/MudBaseInput.cs, src/MudBlazor/Components/Chart/Charts/Bar.razor, src/MudBlazor/Components/Chart/Charts/Bar.razor.cs, src/MudBlazor/Components/Table/MudTable.razor.cs, src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs, src/MudBlazor/Utilities/ColorManager.cs, src/MudBlazor/Utilities/ColorTransformation.cs, src/MudBlazor/Utilities/StyleBuilder.cs
- Refactor as per our code rules
=> Refactor per our code rules

src/MudBlazor.Docs/MudBlazor.Docs.csproj
=> Remove unecessary entry in csproj

src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldSelectExample.razor, src/MudBlazor/Base/MudBaseInput.cs, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs, src/MudBlazor/Components/Input/MudInput.razor.cs, src/MudBlazor/Components/Select/MudSelect.razor.cs, src/MudBlazor/Components/TextField/MudTextField.razor.cs
- Sorry about that.  To be fair this was copied from previous author.
=> Fix typo in SelectAsync

src/MudBlazor.Docs/Pages/Components/Form/Examples/MudFormExample.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithRadioGroupTest.razor, src/MudBlazor.UnitTests/Components/FormTests.cs, src/MudBlazor/Components/Radio/MudRadioGroup.razor, src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
=> Make RadioGroup a form component

src/MudBlazor/Components/AppBar/MudAppBar.razor.cs, src/MudBlazor/Components/Main/MudMainContent.razor, src/MudBlazor/Styles/layout/_appbar.scss, src/MudBlazor/Styles/layout/_drawer.scss, src/MudBlazor/Styles/layout/_main.scss
Fix drawer css error in #684 ([bug](https://github.com/Garderoben/MudBlazor/pull/684#issuecomment-770265672))
Thanks @leMicin for pointing out.
Sorry guys! I hope that's all I made wrong.
=> Fix drawer css

src/MudBlazor.Docs/Pages/Components/Hidden/Examples/BrowserResizeEventExample.razor, src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
I found a small problem with the updated ResizeListenerService in Hidden examples.
=> resizelistener and hidden example fix

src/MudBlazor.Docs.Compiler/T.cs, src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
- Fixes https://github.com/Garderoben/MudBlazor/pull/677
=> Allow for multiple type parameters in API tests

src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerResponsiveTest.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerTest1.razor, src/MudBlazor.UnitTests/Components/DrawerTest.cs, src/MudBlazor.UnitTests/Mocks/MockResizeListenerService.cs, src/MudBlazor/Components/Drawer/MudDrawer.razor.cs, src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
I added a few test for drawer. 
I tried to use MockResizeListener to simulate different screen sizes, I don't know this is the right way.
=> Drawer tests

src/MudBlazor.UnitTests/Components/IconTests.cs, src/MudBlazor/Components/Icon/MudIcon.razor
- Honoring baseclass Style parameter when using custom icons
- Added unit test for both cases
=> honor style of baseclass when using custom icon

src/MudBlazor/Styles/abstracts/_variables.scss, src/MudBlazor/Styles/layout/_appbar.scss, src/MudBlazor/Styles/layout/_drawer.scss, src/MudBlazor/Styles/layout/_main.scss
There are left some inconsistency after the drawer update in the css-s, this PR tries to solve them.
=> Tidy up drawer css

src/MudBlazor.Docs/MudBlazor.Docs.csproj, src/MudBlazor/MudBlazor.csproj
=> Remove unwanted files from nuget

src/MudBlazor.Docs/MudBlazor.Docs.csproj, src/MudBlazor/MudBlazor.csproj
- Build comments were too specific and the target name describes things adequately
=> Remove build comments

src/MudBlazor/Components/Table/MudTableBase.cs, src/MudBlazor/Styles/components/_table.scss
=> MudTable: honor Breakpoint.None and don't break, no matter how small the screen #381

src/MudBlazor.UnitTests/Components/TextFieldTests.cs, src/MudBlazor/Components/Input/MudInput.razor
Fix for #765 
Add test to avoid this in the future.
=> Fix textarea

src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerClippingExample.razor, src/MudBlazor/Components/AppBar/MudAppBar.razor.cs, src/MudBlazor/Styles/components/_toolbar.scss, src/MudBlazor/Styles/layout/_drawer.scss
=> Fix drawer height and position

src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Wireframes/Examples/Layout2WireframeExample.razor
This makes wireframe2 behave like the thumbnail suggests it should.
=> Update clipped property to ClipMode for Drawer in wireframe2 example.

src/MudBlazor.Docs.Client/wwwroot/index.html
Error on startup using Docs.Client.
=> Wasm doesn't load

src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerTimeEditModeExample.razor, src/MudBlazor.Docs/Pages/Components/TimePicker/TimePickerPage.razor, src/MudBlazor.UnitTests/Components/TimePickerTests.cs, src/MudBlazor/Components/TimePicker/MudTimePicker.razor, src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs, src/MudBlazor/Enums/TimeEditMode.cs
Concerning this question [#747](https://github.com/Garderoben/MudBlazor/issues/747)
=> Time picker edit mode

.azure/pipelines/ci.yml, src/MudBlazor.UnitTests/Utilities/CodeSnippetUrlTests.cs
- Fix pipeline for merges after branch name change
- Fix test committed as failing
=> Build on merge. Fix test

.azure/pipelines/ci.yml
=> Fix pipeline run on all merges

src/MudBlazor.Docs/Pages/Project/Credit.razor
I sent an email for details, thanks.
=> Please remove this item

src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor, src/MudBlazor/Components/TreeView/MudTreeView.razor, src/MudBlazor/Components/TreeView/MudTreeView.razor.cs, src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs, src/MudBlazor/Styles/components/_treeview.scss
Add ICommand support for TreeViewItem: #776
Allow define maximum size: #795
=> Add command and overflow for treeview

src/MudBlazor.UnitTests/Components/LinkTests.cs, src/MudBlazor.UnitTests/Components/NavLinkTests.cs, src/MudBlazor/Components/Link/MudLink.razor.cs, src/MudBlazor/Components/NavMenu/MudNavLink.razor, src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
**Motivation**
Fix issues #809 #593 
~~As target can take limited values, should I create a Enum ?~~
Edit: target is not limited values, my mistake.
Thanks
=> Add Target on MudNavLink

src/MudBlazor/Base/MudBaseButton.cs, src/MudBlazor/Base/MudBaseSelectItem.cs, src/MudBlazor/Base/MudBooleanInput.cs, src/MudBlazor/Components/Button/MudButton.razor.cs, src/MudBlazor/Components/Button/MudFab.razor.cs, src/MudBlazor/Components/Button/MudIconButton.razor.cs, src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs, src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs, src/MudBlazor/Components/Menu/MudMenu.razor.cs, src/MudBlazor/Components/Menu/MudMenuItem.razor.cs, src/MudBlazor/Components/Picker/MudPicker.razor.cs, src/MudBlazor/Components/Switch/MudSwitch.razor.cs
When i was gonna do a fix for a issue regarding missing disabled functionality this morning i notice that allot of our components missing any kind of "backend" check if its really disabled or not so simply removing the disabled CSS class or the disabled text from the element in the browser would make it functioning again.
I probably missed some components, some i was unsure on where and how to implement it like autocomplete, selects and so on.
=> Security fix, missing disabled checks in backend for inputs/buttons

src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
=> Fix icon search in docs

src/MudBlazor/Components/Select/MudSelect.razor.cs
=> Fix MudSelect height

src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuExample.razor, src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuIconExample.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/NavLink/NavLinkDisabledTest.razor, src/MudBlazor.UnitTests/Components/NavLinkTests.cs, src/MudBlazor/Components/NavMenu/MudNavLink.razor, src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs, src/MudBlazor/Styles/components/_navmenu.scss
=> Disable MudNavlink

src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs, src/MudBlazor.UnitTests/Mocks/MockHttpHelper.cs, src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
- So we don't need internet for unit tests
=> Add MockHttpMessageHandler to tests

.azure/pipelines/jobs/default-build.yml, .azure/pipelines/jobs/default-test.yml
- To try and fix intermittent build failures
=> Remove netcore 3.1 from build and test.

src/MudBlazor.Docs/.config/dotnet-tools.json, src/MudBlazor/.config/dotnet-tools.json
- To see if it fixes the intermittent build errors
=> Update excubo webcompiler

src/MudBlazor.Docs/.config/dotnet-tools.json, src/MudBlazor/.config/dotnet-tools.json
- Tracking in https://github.com/excubo-ag/WebCompiler/issues/25
=> Update to 2.6.5 for logging errors

src/MudBlazor.Docs/Components/DocsApi.razor, src/MudBlazor.Docs/Models/ApiLink.cs, src/MudBlazor.Docs/Styles/components/_docssection.scss, src/MudBlazor/Base/MudComponentBase.cs, src/MudBlazor/Components/Form/MudForm.razor.cs, src/MudBlazor/Components/ScrollToTop/MudScrollToTop.razor.cs, src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
Possible fix for #519 
I formatted some summaries because they didn't look quite nice.
=> Fix api mobile layout

src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
=> Fix DateRangePicker in dialog mode

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor, src/MudBlazor/Components/Table/MudTr.razor
A fix for #300 I think it is just about the missing `DataLabel`s for `RowEditingTemplate`
=> TableInlineEditExample (small screen)

src/MudBlazor/Styles/components/_treeview.scss
I made a small mistake in my last PR.
=> Change treeview overflow to auto

src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewDenseExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor, src/MudBlazor/Components/TreeView/MudTreeView.razor.cs, src/MudBlazor/Styles/components/_treeview.scss
=> Treeview add dense mode

src/MudBlazor.Docs/Pages/Components/Button/ButtonPage.razor, src/MudBlazor.Docs/Pages/Components/Button/Examples/ButtonLinkExample.razor, src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/DragAndDropFileUploadExample.razor, src/MudBlazor.UnitTests/Components/ButtonsTests.cs, src/MudBlazor/Base/MudBaseButton.cs
=> Fix MudButton Link Disabled

src/MudBlazor/Components/Drawer/MudDrawer.razor.cs, src/MudBlazor/Styles/layout/_drawer.scss
=> Fix drawer flash on page load

src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderBasicExample.razor, src/MudBlazor/Components/Slider/MudSlider.razor, src/MudBlazor/Components/Slider/MudSlider.razor.cs, src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs, src/MudBlazor/Styles/components/_slider.scss
Fix for https://github.com/Garderoben/MudBlazor/issues/900
Added Color property
=> Add colors for MudSlider

src/MudBlazor.Docs.Client/wwwroot/index.html, src/MudBlazor.Docs.Server/Pages/_Host.cshtml
- To be applied just before publishing the website so users get latest version of js and css
=> Cache bust static assets 5.0.2

src/MudBlazor/Components/Table/TableContext.cs
=> Fix initial sort direction

src/MudBlazor.Docs/Models/ApiLink.cs, src/MudBlazor.Docs/Pages/Components/Snackbar/ManualMarkdown/MarkdownSnackbarConfigurationService.razor
- Fixes #964
- Fixes #965
- Fixes #906
=> Fix Snackbar docs

src/MudBlazor.Docs/Pages/Components/Charts/Examples/DonutExample1.razor, src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample1.razor, src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample2.razor, src/MudBlazor.Docs/Pages/Components/Charts/Examples/PieExample1.razor, src/MudBlazor.Docs/Pages/Components/Charts/LineChartPage.razor, src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerStaticExample.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogPassingDataExample.razor, src/MudBlazor.Docs/Pages/Components/SimpleTable/Examples/SimpleTableExample.razor, src/MudBlazor.Docs/Pages/Components/SimpleTable/Examples/SimpleTableHoverDenseExample.razor, src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor, src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerStaticExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewActivateExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewDenseExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewExpandOnClickExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewHoverExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewIconExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewItemTemplateExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewSelectExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewSimpleExample.razor, src/MudBlazor.Docs/Pages/Versions/Versions.razor
=> Fix examples pages for mobiles

src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
Bug: [https://gyazo.com/c59780b50b23a90a270fc387e48545e9](https://gyazo.com/c59780b50b23a90a270fc387e48545e9)
=> Fix continuous rerender in MudSwipeArea

src/MudBlazor.Docs/Pages/Components/Tooltip/Examples/TooltipDelayedExample.razor, src/MudBlazor.Docs/Pages/Components/Tooltip/TooltipPage.razor, src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
=> Change Tooltip Delay parameter to milliseconds

src/MudBlazor/Components/Snackbar/SnackbarService.cs, src/MudBlazor/Interfaces/ISnackbar.cs
=> Returns Snackbar instance on creation

src/MudBlazor/Components/Table/TableContext.cs
=> Fix checkbox when list is empty

src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs, src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
- Obsolete Minimum and Maximum for Progress circular
- Add message to use new property
=> Obsolete Maximum and Minimum

src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectUsageExample.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectTest1.razor, src/MudBlazor.UnitTests/Components/SelectTests.cs, src/MudBlazor/Components/Select/MudSelectItem.razor
=> Fix disabled MudSelectItem

src/MudBlazor.Docs/Components/DocsApi.razor
=> Hide obsolete properties in API docs

src/MudBlazor/Styles/components/_input.scss
- Fixes #859.
- @Garderoben already disabled functionality of button when disabled
- This fixes the visuals
=> Disable Adornment when input disabled

src/MudBlazor/Components/Tabs/MudTabs.razor.cs
=> Ignore ObjectDisposedException in Tabs

src/MudBlazor.Docs/Components/DocsPageHeader.razor, src/MudBlazor.Docs/Extensions/NavigationManagerExtensions.cs, src/MudBlazor.Docs/Models/ApiLink.cs
- This removes absolute paths so if you are in wasm you stay in wasm and if you are in server you stay in server
=> Always respect base dir on website

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
- Fixes #905 
- Also fix-up logic
=> Autocomplete readonly

src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarSizeExample.razor, src/MudBlazor.Docs/Pages/Components/Button/Examples/ButtonSizeExample.razor, src/MudBlazor.Docs/Pages/Components/ButtonFAB/Examples/FabSizeExample.razor
- As part of making the examples independent of docs style
@Garderoben Is this how you want it?
=> Fix #140 Remove SectionContentRow from examples

src/MudBlazor.Docs/Components/SectionContentRow.razor, src/MudBlazor.Docs/Styles/components/_docssection.scss
- No longer needed after #1018
=> Remove unused SectionContentRow Component

src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarNavigationExample.razor, src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor, src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs, src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs, src/MudBlazor/Components/Snackbar/SnackbarConfiguration.cs, src/MudBlazor/Components/Snackbar/SnackbarOptions.cs, src/MudBlazor/Components/Snackbar/SnackbarService.cs, src/MudBlazor/Services/ServiceCollectionExtensions.cs
=> Close snackbar after navigation

src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsCustomScrollIconsExample.razor, src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsScrollExample.razor, src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor, src/MudBlazor/Components/Tabs/MudTabs.razor, src/MudBlazor/Components/Tabs/MudTabs.razor.cs, src/MudBlazor/Styles/components/_tabs.scss
MudTabs Scrollable on resize, added vertical scroll, added option to always show buttons.
=> MudTabs Scrollable on resize, added vertical scroll, added option to always show buttons and MaxHeight. #824

src/MudBlazor/Components/Field/MudField.razor.cs
=> Fix error on MudField

src/MudBlazor.Docs.Client/wwwroot/index.html, src/MudBlazor.Docs.Server/Pages/_Host.cshtml, src/MudBlazor/MudBlazor.csproj
- Update static assets query string for cache busting
- Update nuget version
=> Update static assets and pack 5.0.3

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
=> Fix autocomplete restore scroll position

src/MudBlazor/Components/MessageBox/MudMessageBox.razor
=> Add TitleContent on MudMessageBox

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
Fixes #959 (I guess), at least doesn't break anything
=> Autocomplete: fixes input autocomplete=off #959

src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor, src/MudBlazor/Components/Table/MudTableBase.cs
- Seems to be a recurring question ands it wasn't in the docs
=> Update table docs Breakpoint.None

src/MudBlazor/Components/Tabs/MudTabs.razor, src/MudBlazor/Components/Tabs/MudTabs.razor.cs, src/MudBlazor/Styles/components/_dialog.scss
Fix #1046 and [https://try.mudblazor.com/snippet/cYmlYxulnzHGvihQ](https://try.mudblazor.com/snippet/cYmlYxulnzHGvihQ) (Slider width is smaller than tab panel inside dialog.)
=> Scrolling tabs on panel activation

src/MudBlazor/Components/Rating/MudRatingItem.razor
=> Fix hidden rating star inside a dialog

src/MudBlazor/Components/Table/MudTable.razor.cs, src/MudBlazor/Components/Table/TableContext.cs
=> Fix table multiselect excessivecallback

src/MudBlazor.Docs.Client/wwwroot/index.html, src/MudBlazor.Docs.Server/Pages/_Host.cshtml
- As part of #1098
- This is probably not the solution but it does no harm and we want to eliminate it from the equation
=> Change js script order

src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerBasicUsageExample.razor, src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerColorExample.razor, src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerDialogExample.razor, src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerElevationExample.razor, src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerInternationalizationExample.razor, src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerViewsExample.razor, src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DateRangePickerUsageExample.razor, src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerBasicUsageExample.razor, src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerDialogExample.razor, src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerTimeEditModeExample.razor, src/MudBlazor/Styles/components/_picker.scss
Fixes #876
This forces inline picker to respect the width of the grid
See here an example
https://try.mudblazor.com/snippet/GaGlOxkTWeBjxlKN
=> Fix mud-picker-inline width in Grid

src/MudBlazor/Components/Select/MudSelect.razor
=> Add support for Required parameter to Select component

src/MudBlazor/Services/DialogService.cs
=> Add key to MudDialogInstance

src/MudBlazor/Styles/layout/_drawer.scss
#1112
It doesn't make a big difference in the current behaviour.
=> change drawer-content height to 100%

src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs, src/MudBlazor/Styles/layout/_appbar.scss, src/MudBlazor/Styles/layout/_main.scss
=> fix appbar/maincontent css in firefox esr

src/MudBlazor.UnitTests/Components/NavLinkTests.cs, src/MudBlazor/Components/NavMenu/MudNavLink.razor, src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
A simple solution for #745 #1168.
=> Fire onclick event in MudNavLink

src/MudBlazor.Docs/Pages/Components/Alert/AlertPage.razor, src/MudBlazor.Docs/Pages/Components/Icons/IconsPage.razor, src/MudBlazor.Docs/Pages/Components/Paper/PaperPage.razor, src/MudBlazor.Docs/Pages/Features/Breakpoints/BreakpointsPage.razor, src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
Whilst learning and reviewing the Documentation, I made a few changes to improve grammar, spelling and punctuation on pages.  I also added some extra information to the MudPaper Component based on the answer to some questions @Garderoben answered on discord.  Feel free to adjust/remove commits as you see fit
=> Various small Documentation grammar/spelling/other improvements

src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
@TyrenDe 
We also have an issue with UpdateHeight running after dispose can I use the _disposed field or is that a race condition.
=> Fix object disposed exception

src/MudBlazor/Styles/components/_breadcrumbs.scss
=> Breadcrumb separator dark mode

src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor, src/MudBlazor/Components/Picker/MudPicker.razor, src/MudBlazor/Components/Picker/MudPicker.razor.cs
=> Add dense mode to pickers

src/MudBlazor.UnitTests/Components/TextFieldTests.cs, src/MudBlazor/Base/MudBaseInput.cs, src/MudBlazor/Components/Input/MudInput.razor.cs
=> Input/TextField/Autocomplete: fix swallowing of input while typing

src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuTest1.razor, src/MudBlazor.UnitTests/Components/MenuTests.cs, src/MudBlazor/Components/Menu/MudMenuItem.razor
Added menu test for class pass thorough
Fixes #1277
=> Added class and style to menu item pass through

src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelExpansions.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelMultiExpansion.razor, src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs, src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
=> Fix expansion panel collapsing order #1316

src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/ScrollableTabsTest.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsAddingRemovingTabsTest.razor, src/MudBlazor.UnitTests/Components/TabsTests.cs, src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs, src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs, src/MudBlazor.UnitTests/Mocks/MockResizeObserver.cs, src/MudBlazor.UnitTests/Services/ResizeObserverTests.cs, src/MudBlazor/Components/Tabs/MudTabPanel.razor, src/MudBlazor/Components/Tabs/MudTabs.razor, src/MudBlazor/Components/Tabs/MudTabs.razor.cs, src/MudBlazor/Services/ReseizeObserver/IResizeObserver.cs, src/MudBlazor/Services/ReseizeObserver/IResizeObserverFactory.cs, src/MudBlazor/Services/ReseizeObserver/ResizeObserver.cs, src/MudBlazor/Services/ReseizeObserver/ResizeObserverFactory.cs, src/MudBlazor/Services/ReseizeObserver/ResizeObserverOptions.cs, src/MudBlazor/Services/ServiceCollectionExtensions.cs, src/MudBlazor/Services/ServiceConfiguration.cs, src/MudBlazor/TScripts/mudResizeObserver.js
=> Improved Scrolling and Resizing for Tabs

src/MudBlazor/Styles/core/_ripple.scss
=> Removed invalid translate3d in mud-ripple

src/MudBlazor.UnitTests/Components/TabsTests.cs, src/MudBlazor/Components/Badge/MudBadge.razor, src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor, src/MudBlazor/Components/Chart/MudChart.razor, src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs, src/MudBlazor/Components/Collapse/MudCollapse.razor.cs, src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor, src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor, src/MudBlazor/Components/Field/MudField.razor.cs, src/MudBlazor/Components/InputControl/MudInputControl.razor.cs, src/MudBlazor/Components/Menu/MudMenu.razor, src/MudBlazor/Components/NavMenu/MudNavGroup.razor, src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs, src/MudBlazor/Components/NavMenu/MudNavLink.razor, src/MudBlazor/Components/Overlay/MudOverlay.razor.cs, src/MudBlazor/Components/Picker/MudPickerToolbar.razor, src/MudBlazor/Components/Radio/MudRadio.razor.cs, src/MudBlazor/Components/ScrollToTop/MudScrollToTop.razor.cs, src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor.cs, src/MudBlazor/Components/Sparkline/MudSparkLine.razor, src/MudBlazor/Components/Table/MudTablePager.razor, src/MudBlazor/Components/Table/MudTablePager.razor.cs, src/MudBlazor/Components/Tabs/MudTabPanel.razor, src/MudBlazor/Components/TextField/MudTextField.razor, src/MudBlazor/Components/TimePicker/MudTimePicker.razor, src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs, src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
I added missing Class and Style properties in a bunch of files (similar to #1263 and #1277)
I removed Class and Style properties from child components (similar to #814)
Fixes #814 and #1263
| Component  |  Class added |  Style added |  Class/Style removed from children|
| :------------: | :------------: | :------------: | :------------: |
| Badge  |   | x  |   |
| Breadcrumbs | x  | x  |   |
| Chart |   |  x |   |
| CheckBox |   |   |  x |
| Collapse |   |  x |   |
| ExpansionPanel |   | x  |   |
| ExpansionPanels |   | x  |   |
| Field |   |   |  x |
| InputControl |   |   |  x |
| Menu |   |  x |   |
| NavGroup |   |   |  x |
| NavLink |   |   |  x |
| Overlay |   |   | x  |
| PickerToolBar |   | x  |   |
| Radio |   |   |  x |
| ScrollToTop |  x |   |   |
| SnackbarElement |   |  x | …
=> Missing Class and Style properties added / Class and Style properties were removed from children

src/MudBlazor/Styles/layout/_drawer.scss
=> Fixes MudDrawer wrong zindex

src/MudBlazor/Components/Select/MudSelect.razor.cs
=> Fixed: update icon after parameters changed

src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadButtonExample.razor, src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectInteractiveExample.razor
This change just updates the file count example to read => 0 Files, 1 File, 2Files instead of  0 File, 1 File, 2 Files
=> update to file count text

src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectInteractiveExample.razor, src/MudBlazor/Styles/components/_dialog.scss
=> Added borderradius to dialog child elements

src/MudBlazor.Docs/Models/ApiLink.cs, src/MudBlazor.Docs/Services/MenuService.cs
=> Fix 404 error on chart API pages

src/MudBlazor/Components/Select/MudSelect.razor, src/MudBlazor/Components/Select/MudSelect.razor.cs
=> MudSelect apply IconSize and AdornmentColor

src/MudBlazor/Components/Drawer/MudDrawer.razor.cs, src/MudBlazor/Styles/components/_overlay.scss, src/MudBlazor/Styles/layout/_drawer.scss
Fix #1405 
Also I make changes on the z-index properties of the drawer, because after #1349 I found a wrong behaviour in some special cases.
=> Fix drawer always open

src/MudBlazor/Components/DatePicker/DateRange.cs, src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor, src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
=> Fix DateRangePicker does not show error

src/MudBlazor/Styles/components/_input.scss
=> Fix text field wrong hover color

src/MudBlazor/Components/Select/MudSelect.razor.cs
Fixes for #1364, tested with simple demo as in issue to prove now works ok.
=> Ensure margin reflected to input controls, not just the list.

src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
=> Fix MudDateRangePicker required validation

src/MudBlazor/Components/Tabs/MudTabs.razor, src/MudBlazor/Components/Tabs/MudTabs.razor.cs
=> FIX: MudTabs Component RightToLeft Support

src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerBasicUsageExample.razor, src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs, src/MudBlazor/Extensions/TimeSpanExtensions.cs
=> Add TimeFormat to MudTimePicker

src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewServerExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewServerTest.razor, src/MudBlazor.UnitTests/Components/TreeViewTest.cs, src/MudBlazor/Components/TreeView/MudTreeView.razor.cs, src/MudBlazor/Components/TreeView/MudTreeViewItem.razor, src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs, src/MudBlazor/Components/TreeView/MudTreeViewItemToggleButton.razor, src/MudBlazor/Styles/components/_treeview.scss
=> Add data load on demand for MudTreeView

src/MudBlazor.Docs/Shared/NavMenu.razor, src/MudBlazor.Docs/Styles/core/_base.scss
=> Fixes #1537

src/MudBlazor.Docs/Pages/Components/Charts/Examples/BarExample1.razor, src/MudBlazor.Docs/Pages/Components/Charts/Examples/DonutExample1.razor, src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample1.razor, src/MudBlazor.Docs/Pages/Components/Charts/Examples/PieExample1.razor, src/MudBlazor.UnitTests/Components/ChartTests.cs, src/MudBlazor/Components/Chart/Charts/Bar.razor, src/MudBlazor/Components/Chart/Charts/Donut.razor, src/MudBlazor/Components/Chart/Charts/Line.razor, src/MudBlazor/Components/Chart/Charts/Pie.razor, src/MudBlazor/Components/Chart/MudChart.razor, src/MudBlazor/Components/Chart/MudChart.razor.cs
Reopened from #1491 Due to other source branch
=> MudChart Selectable portions 

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableHorizontalScrollExample.razor, src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor, src/MudBlazor/Styles/components/_table.scss
Please evaluate if "display: block;" can have unwanted side effects. In my testing cases, everything just worked fine.
closes #1174
=> Fixed Horizontal Table scrolling

src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor, src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxIndeterminateExample.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/CheckBox/CheckBoxTriStateTest.razor, src/MudBlazor.UnitTests/Components/CheckBoxTests.cs, src/MudBlazor/Base/MudBooleanInput.cs, src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
Implementation of TriState Parameter for MudCheckbox : https://github.com/Garderoben/MudBlazor/issues/1546
=> TriState parameter addition for MudCheckBox

src/MudBlazor/Components/Menu/MudMenu.razor, src/MudBlazor/Styles/components/_menu.scss
=> Disable browser's context menu for right click mode in MudMenu

src/MudBlazor.UnitTests/Components/TimePickerTests.cs, src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
=> MudTimePicker automatic submit time in static variant

src/MudBlazor.Docs/Pages/Components/Drawer/DrawerPage.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerMiniCustomExample.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerMiniExample.razor, src/MudBlazor.UnitTests/Components/DrawerTest.cs, src/MudBlazor/Components/Drawer/MudDrawer.razor, src/MudBlazor/Components/Drawer/MudDrawer.razor.cs, src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs, src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs, src/MudBlazor/Enums/DrawerVariant.cs, src/MudBlazor/Styles/components/_navmenu.scss, src/MudBlazor/Styles/layout/_appbar.scss, src/MudBlazor/Styles/layout/_drawer.scss, src/MudBlazor/Styles/layout/_main.scss, src/MudBlazor/Themes/Models/LayoutProperties.cs
This is the first approach to add mini variant to drawer. This also cover #1360
=> Add drawer mini variant

src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsBindingExample.razor, src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/SelectedIndexTabsTest.razor, src/MudBlazor.UnitTests/Components/TabsTests.cs, src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Fix for MudTabs ' ActiveIndex Binding. #1581 .
This time I didn't forget the tests! 😁😂
=> Fix for #1581

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableFixedHeaderExample.razor, src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor, src/MudBlazor/Components/Table/MudTableBase.cs, src/MudBlazor/Styles/components/_simpletable.scss, src/MudBlazor/Styles/components/_table.scss
Adds the option to set a sticky footer on tables, as suggested on #1612
=> MudTable: Add fixed footer setting

src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
=> Fix animation for dynamic contents

src/MudBlazor.Docs/Pages/Components/Drawer/DrawerPage.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerAnchorExample.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerLeftRightExample.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerSizeTemporaryExample.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerTemporaryExample.razor, src/MudBlazor/Components/Drawer/MudDrawer.razor.cs, src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs, src/MudBlazor/Components/Layout/MudLayout.razor.cs, src/MudBlazor/Enums/Anchor.cs, src/MudBlazor/Styles/layout/_drawer.scss
There is a layout problem when drawer is opened, and changing  RTL parameter on MudLayout (try on [mudblazor.com)](https://mudblazor.com/)
=> Fix MudDrawer RTL when drawer is opened

src/MudBlazor/Styles/layout/_drawer.scss, src/MudBlazor/Styles/layout/_main.scss
=> Fix css rules for mini drawer

src/MudBlazor/Components/Drawer/MudDrawer.razor, src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
Fix for #1698
Add solution for #1693
=> Fix multiple renders for MudDrawer

src/MudBlazor/Components/Dialog/DialogReference.cs, src/MudBlazor/Components/Dialog/IDialogReference.cs, src/MudBlazor/Components/Dialog/MudDialog.razor.cs
=> Fix IDialogReference.Dialog is null

src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor, src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs, src/MudBlazor/Components/Input/MudRangeInput.razor, src/MudBlazor/Components/Input/MudRangeInput.razor.cs, src/MudBlazor/Components/Picker/MudPicker.razor, src/MudBlazor/Components/Picker/MudPicker.razor.cs
=> Add Focus, Select, SelectRange to MudPickers

src/MudBlazor/Components/Input/MudInput.razor, src/MudBlazor/Components/Input/MudInput.razor.cs, src/MudBlazor/Styles/components/_inputcontrol.scss
Follow up to #1566
Setup the right padding to 17px when `Margin="Margin.Dense"` option is selected, the same as the spinner width for that size.
=> NumericInput: Fix right padding with Margin.Dense

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
=> MudAutocomplete: Added binding to Adornment property

src/MudBlazor.Docs.Client/App.razor, src/MudBlazor.Docs.Client/MudBlazor.Docs.Client.csproj, src/MudBlazor.Docs.Client/Program.cs, src/MudBlazor.Docs.Client/_Imports.razor, src/MudBlazor.Docs.Client/wwwroot/index.html, src/MudBlazor.Docs.Server/App.razor, src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj, src/MudBlazor.Docs.Server/Pages/_Host.cshtml, src/MudBlazor.Docs.Server/Startup.cs, src/MudBlazor.Docs.Server/_Imports.razor
Added Google Analystics for Server and WASM so we can have a better overview of our website users, how many and where in the world.
=> Adding Google/Blazor Analytics

src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs, src/MudBlazor/Themes/Models/Palette.cs, src/MudBlazor/Utilities/ColorManager.cs
Removes the dependency between Palette and BaseMudThemeProvider.
=> Move color altering functions to ColorManager

src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor, src/MudBlazor/Components/Input/MudRangeInput.razor, src/MudBlazor/Styles/components/_pickerdate.scss
Fixes `DatePicker arrow icons must be flipped, icon spacing in textfield` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-724748845
=> Datepicker: fixes in RTL

src/MudBlazor.Docs/Components/NavigationFooter.razor, src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarDenseExample.razor, src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarElevationExample.razor, src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarSimpleExample.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerBreakpointExample.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerClippingExample.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerMiniCustomExample.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerResponsiveExample.razor, src/MudBlazor.Docs/Pages/Components/Grid/Examples/GridSpacingExample.razor, src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithTableExample.razor, src/MudBlazor.Docs/Pages/Components/Table/Examples/TableExample.razor, src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor, src/MudBlazor.Docs/Pages/Components/Table/Examples/TableServerSidePaginateExample.razor, src/MudBlazor.Docs/Pages/Components/ToolBar/Examples/ToolBarExample.razor, src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Content/Examples/WireframeContentLayout1.razor, src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Content/Examples/WireframeContentLayout2.razor, src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Wireframes/Examples/Layout1WireframeExample.razor, src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Wireframes/Examples/Layout2WireframeExample.razor, src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Wireframes/Examples/Layout3WireframeExample.razor, src/MudBlazor.Docs/Shared/MainLayout.razor, src/MudBlazor/Components/AppBar/MudAppBarSpacer.razor, src/MudBlazor/Components/Spacer/MudSpacer.razor, src/MudBlazor/Components/ToolBar/MudToolBarSpacer.razor
=> MudSpacer replaces MudAppBarSpacer and MudToolBarSpacer components

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
=> MudAutoComplete: close on Blur

src/MudBlazor.Docs/Pages/Features/Colors/ColorsPage.razor
Fixes a minor spelling error in src/MudBlazor.Docs/Pages/Features/Colors/ColorsPage.razor.
=> Fix spelling error

src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs
=> MudDrawer fix copy-paste mistake on side selection

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableVirtualizationExample.razor, src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor, src/MudBlazor/Components/Table/MudTable.razor, src/MudBlazor/Components/Table/MudTableBase.cs, src/MudBlazor/Components/Virtualize/MudVirtualize.razor
Closes #796
Please note that I was unable to add any meaningful test case because it dies not seem like the RenderComponent in the test project adheres to the Height parameter and therefore renders all of the rows. It works fine in the Docs example though.
=> Added Table Virtualization.

src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteRequiredTest.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectRequiredTest.razor, src/MudBlazor.UnitTests/Components/AutocompleteTests.cs, src/MudBlazor.UnitTests/Components/SelectTests.cs, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
=> Autocomplete: Added Required parameter

.azure/pipelines/ci.yml, .azure/pipelines/jobs/default-publish.yml
- As discussed with the team
- This publishes on merge to dev to dev.mudblazor.com
=> Add publish to dev merge

README.md
[![Twitter](https://img.shields.io/twitter/follow/MudBlazor?color=1DA1F2&label=Twitter&logo=Twitter&style=flat-square)](https://twitter.com/MudBlazor)
=> Adds twitter shield to readme

README.md
- Added discussions batch
- Added nuget downloads batch
- Removed gitter batch
- Added icons
- Sorted batches
- Changed colors (MudBlazor primary + secondary colors)
=> Readme: removed gitter batch, added discussions/downloads batch

src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor, src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxDenseExample.razor, src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxIconExample.razor, src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxSizeExample.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/CheckBox/CheckBoxTest4.razor, src/MudBlazor.UnitTests/Components/CheckBoxTests.cs, src/MudBlazor/Components/CheckBox/MudCheckBox.razor, src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs, src/MudBlazor/Styles/components/_checkbox.scss
- Added Size parameter to CheckBox
- Added Dense parameter as of request #1653
- Improved docs, added different icons examples
=> MudCheckBox added sizes, dense and improved docs fixed (#1653)

src/MudBlazor.UnitTests/Components/DatePickerTests.cs, src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs, src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor, src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Related to  #1961.
I added aria-labels to the content of the date picker and changed HTML to use semantic elements (div -> button)
=> Improve accessibility for Date Picker

src/MudBlazor/Components/Button/MudToggleIconButton.razor
ToggleIconBotton: added aria-pressed attribute,
=> ToggleIconButton: Improve accessibility

src/MudBlazor/Components/Alert/MudAlert.razor
=> Alert: Improve accessibility

src/MudBlazor/Components/Breadcrumbs/BreadcrumbSeparator.razor
=> Breadcrumbs: Improve accessibility

src/MudBlazor/Components/Dialog/MudDialogInstance.razor
add aria-label and role attribute
=> Dialog: Improve accessibility

src/MudBlazor/Components/Slider/MudSlider.razor
=> Slider: Improve accessibility

src/MudBlazor/Components/Switch/MudSwitch.razor
=> Switch: Improve accessibility

src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor
=> ButtonGroup: Improve accessibility

src/MudBlazor/Components/Radio/MudRadio.razor, src/MudBlazor/Components/Radio/MudRadioGroup.razor
=> Radio: Improve accessibility

src/MudBlazor.Docs/Pages/Components/ButtonFAB/Examples/FabSimpleExample.razor
add aria-label to the documentation for FAB
=> FAB: Improve accessibility

src/MudBlazor.Docs/Pages/Components/IconButton/Examples/IconButtonSimpleExample.razor
add aria-label to the documentation for icon button
=> IconButton: Improve accessibility 

src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor
=> SplitButton docs example: fix defect

src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerBreakpointExample.razor, src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerMiniCustomExample.razor, src/MudBlazor/Components/Drawer/MudDrawer.razor.cs, src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs, src/MudBlazor/Components/Layout/MudLayout.razor, src/MudBlazor/Styles/layout/_drawer.scss
Fix for #1995, and contains some additional minor fixes
=> Fix mini drawer behaviour

src/MudBlazor/Components/List/MudListItem.razor, src/MudBlazor/Components/List/MudListItem.razor.cs
=> MudList: Forwarded IconSize and AdornmentColor attributes

src/MudBlazor.Docs/Pages/Components/Button/ButtonPage.razor, src/MudBlazor.Docs/Pages/Components/Button/Examples/ButtonLoadingExample.razor
Credit goes to @mckaragoz in https://github.com/Garderoben/MudBlazor/discussions/2004#discussioncomment-937161
=> MudButton: added loading example

src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioDenseExample.razor, src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioSizeExample.razor, src/MudBlazor.Docs/Pages/Components/Radio/RadioPage.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest6.razor, src/MudBlazor.UnitTests/Components/RadioTests.cs, src/MudBlazor/Components/Radio/MudRadio.razor, src/MudBlazor/Components/Radio/MudRadio.razor.cs, src/MudBlazor/Styles/components/_radio.scss
Added dense for MudRadio
Added sizes for MudRadio
=> MudRadio - Added sizes and dense style

README.md, src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsWithBagdesExample.razor, src/MudBlazor/Components/Tabs/MudTabPanel.razor, src/MudBlazor/Components/Tabs/MudTabs.razor
Added the ability to add a badge dot to a MudTab.
=> MudTab with BadgeDot

src/MudBlazor/Components/Radio/MudRadioGroup.razor
Forwarding class, style and attributes to wrapping radiogroup div
=> Forwarding class, style and attributes to wrapping radiogroup div

src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
In my attempt to improve `MudCarousel` (#1913) I forgot to actually dispose the timer.
=> MudCarousel: Fixed timer never being disposed;

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor, src/MudBlazor/Components/Select/MudSelect.razor
=> Forwarded missing OnAdornmentClick for MudSelect and MudAutocomplete

src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectNumericCollectionExample.razor, src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
(The formatting of the "Custom converter" section was done by VS. Content has not changed)
=> MudSelect: Add sample on using numeric collection+Required+Clearable properties

src/MudBlazor/Base/MudBaseSelectItem.cs, src/MudBlazor/Components/List/MudListItem.razor.cs
I need the MenuItem to link to a page outside of my current application, which requires the ForceLoad parameter to be set on the NavigationManager.
=> MudListItem: Add ForceLoad parameter to allow redirecting outside the component router-space

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor, src/MudBlazor.Docs/Pages/Components/Table/Examples/TableServerSidePaginateExample.razor, src/MudBlazor/Components/AppBar/MudAppBarSpacer.razor, src/MudBlazor/Components/ToolBar/MudToolBarSpacer.razor
This adds an obsolete warning for MudAppBarSpacer and MudToolBarSpacer
=> MudAppBarSpacer, MudToolBarSpacer: add obsolete warning

src/MudBlazor.UnitTests.Viewer/TestComponents/Field/FieldTest.razor, src/MudBlazor/Components/Field/MudField.razor.cs
=> MudField: Fix AdornmentIcon overlaps the label when no text is set

src/MudBlazor/Components/Portal/MudPortal.razor.cs
Reverts Garderoben/MudBlazor#2253 as requested by @porkopek
=> Revert "Portal: change the visibility of the Portal before re-render to gain some ms performance"

CONTRIBUTING.md, README.md
If you have suggestions for better wording or other information to include, feel free to share! :)
=> Contributing readme: Add contributing guidelines

src/MudBlazor.Docs/Extensions/MethodInfoExtensions.cs, src/MudBlazor.Docs/Models/XmlDocumentation.cs
=> Docs, API pages:  Small modifications

src/MudBlazor/Base/MudBaseInput.cs, src/MudBlazor/Components/Field/MudField.razor.cs
=> Changed IconSize from Size.Small to Size.Medium

src/MudBlazor/Components/ColorPicker/MudColorPicker.razor, src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs, src/MudBlazor/Styles/components/_pickercolor.scss
=> MudColorPicker: fix slider in RTL

src/MudBlazor.Docs/Components/SectionContent.razor, src/MudBlazor.Docs/Pages/Components/Pagination/Examples/PaginationControlButtonsExample.razor, src/MudBlazor.Docs/Pages/Components/Pagination/Examples/PaginationItemCountExample.razor, src/MudBlazor.Docs/Pages/Components/Pagination/Examples/PaginationRectangularExample.razor, src/MudBlazor.Docs/Pages/Components/Pagination/Examples/PaginationSimpleExample.razor, src/MudBlazor.Docs/Pages/Components/Pagination/Examples/PaginationSizesExample.razor, src/MudBlazor.Docs/Pages/Components/Pagination/Examples/PaginationTableExample.razor, src/MudBlazor.Docs/Pages/Components/Pagination/Examples/PaginationVariantsExample.razor, src/MudBlazor.Docs/Pages/Components/Pagination/PaginationPage.razor, src/MudBlazor.Docs/Services/MenuService.cs, src/MudBlazor.Docs/Styles/components/_docssection.scss, src/MudBlazor.UnitTests.Viewer/TestComponents/Pagination/PaginationButtonTest.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Pagination/PaginationCountTest.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Pagination/PaginationStylesTest.razor, src/MudBlazor.UnitTests/Components/PaginationTests.cs, src/MudBlazor/Components/Pagination/MudPagination.razor, src/MudBlazor/Components/Pagination/MudPagination.razor.cs, src/MudBlazor/Styles/MudBlazor.scss, src/MudBlazor/Styles/components/_pagination.scss
Closes #165
Requires #2338 (Merged @mikes-gh)
=> Add MudPagination component (#165)

src/MudBlazor.UnitTests/Components/DatePickerTests.cs, src/MudBlazor.UnitTests/Components/NumericFieldTests.cs, src/MudBlazor.UnitTests/Components/PaginationTests.cs
Fixes tests failing caused by  #2372
=> DatePicker, NumericField, Pagination: Fix tests

src/MudBlazor.UnitTests/Components/PageContentNavigationTests.cs, src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor.cs, src/MudBlazor/Components/PageContentNavigation/MudPageContentSection.cs
i submitted this as a stand alone PR since it is a breaking change
=> Rename MudPageContenSection to MudPageContentSection (typo)

src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorOnMouseExample.razor, src/MudBlazor/Components/Menu/MudMenu.razor.cs
=> typo in PositionAtCurser

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionCheckboxExecutesCallback.razor, src/MudBlazor.UnitTests/Components/CheckBoxTests.cs, src/MudBlazor.UnitTests/Components/TableTests.cs, src/MudBlazor/Base/MudBooleanInput.cs, src/MudBlazor/Components/CheckBox/MudCheckBox.razor, src/MudBlazor/Components/Table/MudTr.razor
=> MudTable: In MultiSelection mode Checkbox now fires callback (#930)

.gitignore, src/MudBlazor.UnitTests/Components/ColorPickerTests.SetR_r=40_selectorXPosition=256.78_selectorYPosition=28.43.00.verified.txt, src/MudBlazor.UnitTests/Components/ColorPickerTests.SetR_r=40_selectorXPosition=256.78_selectorYPosition=28.43.01.verified.html, src/MudBlazor.UnitTests/Components/ColorPickerTests.cs, src/MudBlazor.UnitTests/ModuleInitializer.cs, src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
Thoughts on using snapshot testing to help verify the results of tests?
=> ColorPicker tests: add a snapshot test

src/MudBlazor.UnitTests.Viewer/TestComponents/Timeline/TimelineTest.razor, src/MudBlazor.UnitTests/Components/TimelineTests.cs, src/MudBlazor/Components/Timeline/MudTimeline.razor.cs
I've added more unit tests to put light into "dark" allays in ``MudTimeline`` and ``MudTimelineItem``. Besides, I've made some minor refactoring. **No more functionality added or bugs fixed**.
=> Increased code coverage for MudTimelineand MudTimelineItem

src/MudBlazor.UnitTests/Components/DatePickerTests.cs, src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
Fixes #2164, Fixes #2371, fixes #2510
Caused by #1976 as explained in #2164 (See https://stackoverflow.com/questions/2440043/button-in-the-form-cause-it-be-submitted-automatically)
Todo:
=> MudBaseDatePicker: fix unwanted form submit (#2164, #2371, #2510)

src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
Fixes #1916 
@henon I hope it's clear enough.
=> Table docs: add RowsPerPage explanation

src/MudBlazor.Docs/Pages/Components/Icons/Examples/ChangeIconByProgrammaticallyExample.razor, src/MudBlazor.Docs/Pages/Components/Icons/IconsPage.razor
Most of the users asking how to change the icons. This example show basics of it.
=> Docs: add example for changing icon programmatically

src/MudBlazor.Docs/Pages/Customization/DefaultTheme.razor
Now, typography parameters can be shown on DefaultTheme page. (One of the @Garderoben's request)
=> Docs: TypographyDocs For DefaultTheme Page

src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
We added a detailed MouseWheel test for numeric field.
=> NumericField: Add MouseWheel Test

.vscode/launch.json, src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableGroupLoadingAndNoRecordsTest.razor, src/MudBlazor.UnitTests/Components/TableTests.cs, src/MudBlazor/Components/Table/MudTable.razor
A grouped table currently does not display the no records and loading render fragments. This pr fixes and tests the issue.
=> Table: Fix grouped table loading and no records missing text

src/MudBlazor.Docs/Pages/Getting Started/Layouts/LayoutsPage.razor
=> Minor Spelling Correction

README.md
=> Update Readme Formatting

src/MudBlazor.Docs/Pages/Components/Grid/Examples/GridBuilder.razor, src/MudBlazor.Docs/Pages/Components/Grid/GridPage.razor
Found myself rebuilding projects a lot getting justification and breakpoints right.
Here I've added an interactive breakpoint demo to grid docs.
=> Added interactive breakpoint demo to grid docs.

src/MudBlazor.Docs/Components/DocsApi.razor
In Api pages, Icon properties shows a string path value. We change this a true Icon. (As @Garderoben's request)
=> Docs: Api Pages Path to Icons

src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
=> Docs: Template Page link fix on Installation Page 

src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectTest2.razor, src/MudBlazor.UnitTests/Components/SelectTests.cs, src/MudBlazor/Components/Select/MudSelect.razor, src/MudBlazor/Components/Select/MudSelect.razor.cs, src/MudBlazor/Components/Select/MudSelectItem.razor, src/MudBlazor/Components/Select/MudSelectItem.razor.cs
Fixes #2758 and will us allow to implement keyboard navigation in the drop-down with arrow keys
=> Select: hilight selected value in drop-down

src/MudBlazor/Components/Select/MudSelect.razor
Implemented same fix as this #1201 for autocomplete, fixes #2608
=> Select: Popover placement with select helpertext (#2608)

src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
NumericField: allow Home and End buttons (they were accidentally supressed)
=> NumericField: allow Home and End buttons (they were accidentally supressed)

src/MudBlazor/Styles/components/_select.scss
fixes #2477
It should be checked if other components would benefit from this too.
=> Select: Too long texts are truncated with ellipsis

src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetReadOnlyTest.razor, src/MudBlazor.UnitTests/Components/ChipSetTests.cs, src/MudBlazor/Components/Chip/MudChip.razor.cs, src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
=> ChipSet: enable ChipSet to be readonly (#2548)

src/MudBlazor/Styles/components/_snackbar.scss
There is an aligment text issue if the text is too long.
Fix the text alignment issue.
Below is the result. Before and After.
=> Snackbar Aligment

src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldHelperTextExample.razor, src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor, src/MudBlazor/Base/MudBaseInput.cs, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor, src/MudBlazor/Components/Input/MudInput.razor, src/MudBlazor/Components/InputControl/MudInputControl.razor, src/MudBlazor/Components/InputControl/MudInputControl.razor.cs, src/MudBlazor/Components/Picker/MudPicker.razor, src/MudBlazor/Components/Picker/MudPicker.razor.cs, src/MudBlazor/Components/Select/MudSelect.razor, src/MudBlazor/Components/TextField/MudTextField.razor, src/MudBlazor/Styles/components/_inputcontrol.scss
Added option to show HelperText only on focus.
https://user-images.githubusercontent.com/78308169/134748090-3bfc1a5e-e0b7-4f95-9c61-c18fdb7e0e0d.mp4
=> Inputs: HelperText Show/Hide On Focus/Blur

src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
=> Spelling Fix

src/MudBlazor.UnitTests.Viewer/TestComponents/Chip/ChipOnClickTest.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetReadOnlyTest.razor, src/MudBlazor.UnitTests/Components/ChipSetTests.cs, src/MudBlazor.UnitTests/Components/ChipTests.cs, src/MudBlazor/Components/Chip/MudChip.razor.cs
Fixes #2866
- implemented unit test for `OnClick` and `OnClose`
- modified ReadOnly unit test in order to test OnClose event
- Bug fix (non-breaking change which fixes an issue)
=> [Bug] Chip: Fix OnClick/OnClose causing NullReferenceException (#2866)

src/MudBlazor/Styles/components/_pagecontentnavigation.scss
Fixes cut off text of the PageContentNavigation
Before:
After:
It would probably be better to enforce a short title.
The title is too long on the following pages:
https://mudblazor.com/wasm/components/dialog#api
https://mudblazor.com/wasm/components/expansionpanels#api
https://mudblazor.com/wasm/components/checkbox#api
https://mudblazor.com/wasm/components/numericfield#api
https://mudblazor.com/wasm/components/slider#api
https://mudblazor.com/wasm/components/textfield#api
https://mudblazor.com/wasm/components/hidden#api
https://mudblazor.com/wasm/components/highlighter#api
https://mudblazor.com/wasm/components/icons#api
https://mudblazor.com/wasm/components/table#api
visually
=> PageContentNavigation: Fix cut off text

src/MudBlazor.Docs.Server/Properties/launchSettings.json, src/MudBlazor/Components/Input/MudInput.razor
fixes #2903
Manually, cursor jumps can not be tested in bUnit.
=> MudInput: fix cursor jumping for immediate multiline inputs with two-way binding on BSS

src/MudBlazor/Components/Input/MudInputAdornment.razor
=> Input: remove tabstop from input adorners

src/MudBlazor.Docs/Pages/Components/NumericField/NumericFieldPage.razor, src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
=> fix typo looses -> loses

src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarNavigationExample.razor, src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
Resolves #2856
By providing 2 snackbars (one that has the CloseAfterNavigation set and another "defaul" snackbar) the user is able to better understand the functionality. 
The instructions also give the user directions on how to see the actions, by directing them to navigate to another page within the component sidebar.
Visually tested.
=> Docs: Update SnackBar navigation example

src/MudBlazor/Components/Popover/MudPopover.razor.cs, src/MudBlazor/Components/Popover/MudPopoverService.cs, src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs, src/MudBlazor/Services/ResizeListener/BreakpointService .cs, src/MudBlazor/Services/ResizeListener/ResizeBasedService.cs, src/MudBlazor/Services/ResizeListener/ResizeService.cs
Adds support for JSDisconnectedException for net6
Compiled on the net6 branch
Fixes #2659
Maybe also has a bearing on #3064
=> Framework: Add JSDisconnected exception for net6

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
We needed to do something about the flaky Autocomplete_ChangeBoundValue test. This should make it a lot more reliable. 
Also fixed incorrect closing logic on Escape keys.
=> Autocomplete: Increased reliability of ChangeBoundValue test

src/MudBlazor.Docs/Pages/Features/Converters/ConvertersPage.razor
Fix double advert and section content entry
Visual
Before
After
=> Docs: Fix convertors page

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePagerChangeRowsPerPageTest.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePagerChangeRowsPerPageTest.razor.cs, src/MudBlazor.UnitTests/Components/TableTests.cs, src/MudBlazor/Components/Table/MudTableBase.cs
fixes #3033 
Unit test and test component added
=> Fix #3033 - RowsPerPage Parameter can now be set from code

.github/workflows/ci-net6.yml, .github/workflows/manual-deploy.yml, .github/workflows/prepare-release.yml, .github/workflows/template-pipeline.yml
Updated GitHub Workflows.
- Added `prepare-release`
- - Runs the regular build/test
- - If successful, pack nuget and publish it
- - inform try.mudblazor about new release and update
- Added `manual-deploy`
=> Updated GitHub Workflows

src/MudBlazor/Components/NumericField/MudNumericField.razor
Added missing parameter on numericfield. fixes #3285 
The PR is submitted to the correct branch (`dev`).
My code follows the code style of this project.
I've added relevant tests. (no need)
=> NumericField: HelperTextOnFocus

src/MudBlazor.Docs/Pages/Components/ButtonFAB/Examples/FabSimpleExample.razor, src/MudBlazor.Docs/Pages/Components/ButtonFAB/Examples/FabSizeExample.razor, src/MudBlazor/Components/Button/MudFab.razor, src/MudBlazor/Components/Button/MudFab.razor.cs, src/MudBlazor/Styles/components/_fab.scss
Add support for positioning an icon inside the MudFab to the left or right.
```html
<MudFab StartIcon="@Icons.Material.Filled.Chat" EndIcon="@Icons.Material.Filled.Casino" Label="Button" />
```
Added examples in the doc.
=> MudFab: Support for StartIcon and EndIcon

src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
=> MudChipSet: Remove debug messages

src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor, src/MudBlazor.UnitTests/Components/TimePickerTests.cs, src/MudBlazor/Components/TimePicker/MudTimePicker.razor
Fixes #3180
When zero was selected as the hour it added 24 hours and therefore a day to the resulting TimeSpan (#3180).
This was fixed by adding the modulo.
Functionality tested with the snippet provided in the issue.
All unit tests passed.
=> TimePicker: Fixed the picker adding a day to the timespan (#3180)

src/MudBlazor.Docs/Components/DocsApi.razor, src/MudBlazor.Docs/Components/DocsPageHeader.razor, src/MudBlazor.Docs/Components/DocsRenderBenchmark.razor, src/MudBlazor.Docs/Models/ApiLink.cs, src/MudBlazor.Docs/Models/DocsComponents.cs, src/MudBlazor.Docs/Models/MudComponent.cs, src/MudBlazor.Docs/Services/ApiLinkService.cs, src/MudBlazor.Docs/Services/DocsNavigationService.cs, src/MudBlazor.Docs/Services/MenuService.cs, src/MudBlazor.Docs/Shared/NavMenu.razor, src/MudBlazor.Docs/Shared/NavMenu.razor.cs
reduces Alert page on wasm from ~600ms to ~250ms
=> Docs: huge performance increase on wasm

src/MudBlazor.Docs/Components/DelayedContent.razor, src/MudBlazor.Docs/Components/SectionSource.razor
=> Docs: halved page load time again (wasm performance)

src/MudBlazor/Enums/InputType.cs
Addes `url` to `InputType`. `url` is a valid HTML5 input type.
resolves #3357
none
=> InputType: Added url to the InputType enum (#3357)

src/MudBlazor.Docs/Components/DocsPageSection.razor, src/MudBlazor.Docs/Components/QueuedContent.razor, src/MudBlazor.Docs/Extensions/DocsViewExtension.cs, src/MudBlazor.Docs/Services/RenderQueueService.cs, src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs, src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
=> Docs: optimized responsiveness of slow loading component pages for WASM

src/MudBlazor/Components/Input/MudInput.razor, src/MudBlazor/Components/Input/MudInput.razor.cs, src/MudBlazor/Components/NumericField/MudNumericField.razor, src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
NumericField didn't have clearable parameter, because we can't add directly like TextField, needed some style to not overlapping spin buttons. With this PR, clearable added and set clearable icon's position to show them proper for each situation.
It's a visually added feature, no change for clear method.
With spin buttons:
Without spin buttons:
=> NumericField: Add Clearable Parameter

src/MudBlazor.Docs.Client/wwwroot/index.html, src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
I would like to get rid of `'unsafe-inline'`. But we use inline style tags quite often in the docs.
=> Docs: Add content security policy

src/MudBlazor.UnitTests/Components/TimePickerTests.cs, src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
=> TimePicker: Fix OnlyHours incorrect behavior

src/MudBlazor.Docs.Client/wwwroot/index.html, src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
Fixes broken carousel example / Fixes icon page example
=> Content Security policy: Fix carousel example + Fix icon example

src/MudBlazor.Docs.Client/wwwroot/index.html, src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
Fixes contributors not fetching from github api
=> Content security policy: Fix contributors page

src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipVisiblePropTest.razor, src/MudBlazor.UnitTests/Components/ToolTipTests.cs, src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
Adds a `Hide` method to Tooltip. This is useful in specific instances where mousing away from the tooltip will not hide it, such as when dragging an element with a tooltip.
No new tests, but the method is functionally identical to the `HandleMouseOut` method, but public. Perhaps `HandleMouseOut` could be replaced or another change made so `Hide` isn't redundant?
=> Tooltip: Add IsVisible two-way binding property

src/MudBlazor.UnitTests/Components/NumericFieldTests.cs, src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
Dependabot https://github.com/MudBlazor/MudBlazor/pull/3582  bUnit update broke some tests
These tests were loosely typed parameters that had different types assigned to them causing casting errors.
Maybe theres a better way to fix this?
Or maybe the component should deal with the types of the Min Max?
By running the tests
=> Build: Update bUnit and fix tests

CONTRIBUTING.md
Add node requirement to docs.
Changing to the package `Microsoft.TypeScript.MSBuild` gives us better compilation and ES6 support.
It does however require node.
The tradeoff is acceptable because it is only required to build from source.
None
Docs change
=> Build: Add node requirement to docs.

src/MudBlazor.Docs/Pages/Components/Field/Examples/FieldBasicExample.razor, src/MudBlazor/Components/Field/MudField.razor, src/MudBlazor/Components/Field/MudField.razor.cs
Added adornment color parameters to MudField and updated docs with examples.
- Resolved issue #3562
Tested visually.
=> Added Adornment Color to MudField - resolves issue #3562

src/MudBlazor/TScripts/mudPopover.js, src/MudBlazor/TScripts/mudScrollManager.js
Fix ES6 incompatible language syntax
Fixes https://github.com/MudBlazor/MudBlazor/issues/3537
Since it is JS needs peer review and manual testing
=> Refactor: Only use ES6 language features

.github/workflows/template-pipeline.yml
Add check to build for JS language level ES6 
Keep the level of JS to ES6 for maximum browser compatibility.
=> Build: Add JS ES6 compliance check

src/MudBlazor/Styles/components/_menu.scss
Issue(wrong height of menu components) is caused not only by line-height, but by flex container too
Resolves #3018
Before: ![Знімок з 2022-01-05 20-56-22](https://user-images.githubusercontent.com/30006309/148273859-9a91fcb1-05e7-41fb-a10f-d8f916f45927.png)
After: ![Знімок з 2022-01-06 03-29-15](https://user-images.githubusercontent.com/30006309/148313527-0303f974-82f4-4963-b94b-c9d32407a76b.png)
=> Fix wrong redundant height in menu components.

src/MudBlazor/Components/Select/MudSelect.razor.cs
As diccussed in #3003. Printable characters (Example M for started with "M" items) in select didn't scroll the item correctly in some situations.
And please don't forget, we still didn't fully support multiselect printable characters scrolling.
https://user-images.githubusercontent.com/78308169/148661469-96e61d05-29ab-4882-9585-22806d521bbe.mp4
Fixes #3003 again
=> Select: Scroll Fix

src/MudBlazor.Docs/Pages/Features/Colors/ColorsPage.razor
Fixes #3761. Changed `/theming/overview` to `/overview`
=> Docs: Broken Link

src/MudBlazor.UnitTests/Components/BunitTest.cs, src/MudBlazor.UnitTests/Components/DialogTests.cs, src/MudBlazor.UnitTests/Components/SelectTests.cs, src/MudBlazor/Components/Select/MudSelect.razor.cs
This PR provides an automatically scroll to the active item when select's dropdown is open. And this complete the arrow key navigation scrolling.
Also added OnOpen and OnClose events to allow user made methods.
https://user-images.githubusercontent.com/78308169/150600554-9e0b4580-31fa-47f7-9f7d-fca94aabf582.mp4
=> Select: Scroll to selected item on open

src/MudBlazor/Components/Menu/MudMenu.razor
Fixes #1571 that right click on Menu now doesn't cause to also open browser's context menu at all.
=> Menu: Fix Right Click

src/MudBlazor.Docs/Pages/Components/Icons/IconsPage.razor, src/MudBlazor.Docs/Shared/NavMenu.razor
Checking for each language and special character is difficult. But this PR fixes the breaking that some component pages not opening due to its name (example icon and iconbutton)
Directly using ToLowerInvariant() may not be useful, so for Turkish language we need a little bit tricky way, using ToUpper() before the ToLowerInvariant().
=> Docs: Culture Title Fix

src/MudBlazor.Docs/Pages/Components/DropZone/DropZonePage.razor
Possible typo fix if I understand the context correctly on the site on DropZone Component.
- [ X] The PR is submitted to the correct branch (`dev`).
=> Typo fix on  DropZonePage Component Documentation

src/MudBlazor.Docs/Styles/core/_markdown.scss
- [  ] New feature (non-breaking change which adds functionality)
- [  ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> DOCS: Fix '@' symbol color and fix spaces 

src/MudBlazor.Docs/Pages/Components/Grid/Examples/GridBuilderExample.razor
It is possible to set sizes above 12 or below 1 when editing a MudItems in the docs in the [grid builder](https://mudblazor.com/components/grid#grid-builder):
Visually in docs.
=> Docs: Prevent grid item sizes above 12 or below 1

src/MudBlazor.Docs/Models/DocsComponents.cs, src/MudBlazor.Docs/Shared/NavMenu.razor, src/MudBlazor.Docs/Shared/NavMenu.razor.cs
=> NavMenu: Fix wrong url in turkish culture

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, CONTRIBUTING.md
Fixes links in contributing readme and issue templates
=> Contributing readme, issue templates: Fix links

src/MudBlazor.Docs/Components/DocsExploreCard.razor, src/MudBlazor.Docs/Components/DocsPageHeader.razor, src/MudBlazor.Docs/Components/SectionHeader.razor.cs, src/MudBlazor.Docs/Extensions/StringExtensions.cs, src/MudBlazor.Docs/Pages/Customization/DefaultTheme.razor, src/MudBlazor.Docs/Pages/Features/Colors/ColorsPage.razor
=> Docs: Change ToLower to ToLowerInvariant to fix visual link/naming issues (for languages like Turkish)

src/MudBlazor/Utilities/BindingConverters/NumericConverter.cs
Fixes #4066. Added additional minvalue and maxvalue check for not encounter an exception.
=> NumericField: Fix Value Out Of Bounds Exception

src/MudBlazor.UnitTests/Components/TableTests.cs, src/MudBlazor/Components/CheckBox/MudCheckBox.razor
Fixes #4077. Moved the stoppropagation parameter into the checkbox's parent component, so now stoppropagation working when label clicked properly.
- [] I've added relevant tests. (Tested manually)
=> Checkbox: StopPropagation also on label click

src/MudBlazor.UnitTests/Components/MenuTests.cs, src/MudBlazor/Components/Menu/MudMenu.razor, src/MudBlazor/Components/Menu/MudMenu.razor.cs, src/MudBlazor/Components/Menu/MudMenuItem.razor, src/MudBlazor/Components/Menu/MudMenuItem.razor.cs, src/MudBlazor/Components/Select/MudSelectItem.razor
Fixed #4063. Added touch events.
=> Menu and Select: Fix not close on mobile view

src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAggregationExample.razor, src/MudBlazor.UnitTests/Components/DataGridTests.cs, src/MudBlazor/Components/DataGrid/HeaderContext.cs
- Fixed an issue with FilterDefinitionDateTimeTest getting failures because of different time zones.
- Fixed a culture specific issue on the examples page with the aggregation example.
- Removed comment in DataGridTests.
=> Phase2 issues

src/MudBlazor.Docs/Pages/Index.razor, src/MudBlazor.Docs/Pages/Mud/Project/Roadmap.razor, src/MudBlazor/Components/Chip/MudChip.razor.cs
=> Docs: Correct typos

src/MudBlazor.UnitTests.Viewer/TestComponents/Switch/MudSwitchTest.razor, src/MudBlazor/Components/Switch/MudSwitch.razor.cs
=> Switch: Removed ripple effect when disabled (#4339)

src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/TextFieldClearableTest.razor, src/MudBlazor/Components/Input/MudInput.razor.cs, src/MudBlazor/Components/Mask/MudMask.razor.cs
=> TextField: Focus after clicking clear button (#4354)

src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithOnBackdropClickEvent.razor, src/MudBlazor.UnitTests/Components/DialogTests.cs, src/MudBlazor/Components/Dialog/MudDialog.razor.cs, src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
Resolves #4390 
Now you can add behaviour for backdrop click.
Added unit test that cheks new functionality. Looks like default functionality(close on backdrop click) already tested so I didn't add test on that.
=> Dialog: Add OnBackdropClick event (#4390)

src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
This is a micro docs fix, should be self explanatory.
=> Docs: Datepicker API MinDate text fix

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
I think this is the last PR about autocomplete close issue and about #4326.
Removed all touch events from autocomplete, because @henon already revert and fixed the popover issue. We don't need anymore about touch events, it already works in mobile.
=> Autocomplete: Fix Scrollable List Touch

src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
Spelling error on MudProgressLinear.razor.cs 
No functionality changes. All current tests pass.
Fixes #4525
=> Fixed the spelling error

src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
This is a micro fix for a tiny typo I must have made when I added this section. 😅
=> Docs: Fix typo in tabs content section

src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedExample.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedExample_Dialog.razor, src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedExample_Dialog2.razor, src/MudBlazor.UnitTests/Components/DialogTests.cs, src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
A very basic and useful improvement that doesn't change any logic of dialog.
Now users can use `MudDialog.CancelAll()` to close (cancel) all dialogs at once.
https://user-images.githubusercontent.com/78308169/175044603-8a63afca-f311-4e12-9a5c-31f870be8c17.mp4
=> Dialog: CancelAll closes all open dialogs

src/MudBlazor.Docs.WasmHost/Prerender/ICrawlerIdentifier.cs, src/MudBlazor.Docs.WasmHost/Program.cs, src/MudBlazor.UnitTests/Components/HiddenTests.cs, src/MudBlazor.UnitTests/Components/PopoverTests.cs, src/MudBlazor/Components/DropZone/MudDropZone.razor.cs, src/MudBlazor/Components/Popover/MudPopoverService.cs, src/MudBlazor/TScripts/mudPopover.js, src/MudBlazor/TScripts/mudResizeObserver.js, src/MudBlazor/Utilities/MudColor.cs
Fixes #4855 
However javascript/typescript changes may be 'breaking'
Unit tests all executed successfully
=> Fix typos of Initialized

src/MudBlazor/Styles/components/_inputcontrol.scss
Fixes #4833. Mentioned in #4814. #4084 resulted in extra margin due to the usage of the `InputControl` component around the `CheckBox` and `RadioGroup`. This PR fixes the issue with a small CSS tweak.
Tested visually.
=> Checkbox + Radio: Remove top margin on boolean inputs

src/MudBlazor.UnitTests/Components/Charts/DonutChartTests.cs, src/MudBlazor/Components/Chart/Charts/Donut.razor, src/MudBlazor/Components/Chart/Charts/Donut.razor.cs
Fixes #4495 
Center MudChart Donut in his svg viewBox.
It sets the circle svg center x and y position to half of the view box size.
unit and visually
before
after
=> Fix MudChart Donut not centered

src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewExpandOnDoubleClickExample.razor, src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTest3.razor, src/MudBlazor.UnitTests/Components/TreeViewTest.cs, src/MudBlazor/Components/TreeView/MudTreeView.razor.cs, src/MudBlazor/Components/TreeView/MudTreeViewItem.razor, src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
* Allows TreeView to expand nodes using doubleClick event, in a similar way as ExpandOnClick.
* Adds TreeViewItem OnDoubleClick EventCallback
unit
=> Add MudTreeView ExpandOnDoubleClick and MudTreeViewItem OnDoubleClick event callback

src/MudBlazor.Docs/Pages/Getting Started/Layouts/LayoutsPage.razor
Since LayoutBasicFunctionalityExample uses MyNavMenu, the name of the file containing Menu should be MyNavMenu.razor, not NavMenu.razor.
Project with correct file name compiles and runs in VS 2022, previously it didn't.
=> Corrected name of file to MyNavMenu.razor

src/MudBlazor/Styles/components/_table.scss
Resolves https://github.com/MudBlazor/MudBlazor/issues/3105
All existing tests pass. I have also tested the visual changes manually.
Before:
https://user-images.githubusercontent.com/42306093/181119123-31cb9f99-c8ac-4c05-a62b-c74362aa500e.mp4
After:
https://user-images.githubusercontent.com/42306093/181119134-d824f3cf-de5f-430f-b8e3-a8ea079a28a4.mp4
=> Table: Fixes visual bug where NoRecordsContent on stripped table changes background color on hover

src/MudBlazor.Docs/Pages/Components/Timeline/Examples/TimelineDotsStyleExample.razor, src/MudBlazor.Docs/Pages/Components/Timeline/TimelinePage.razor, src/MudBlazor.UnitTests/Components/TimelineTests.cs, src/MudBlazor/Components/Timeline/MudTimelineItem.razor, src/MudBlazor/Components/Timeline/MudTimelineItem.razor.cs
…s on each dot
tries to fix #4635
allowing customize the dot style properties using a TimeLineItem DotStyle attribute,
so the user can sets the color from a hex string (as described in the linked issue).
unit
=> TimeLineItem: Add DotStyle attribute

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableRecordComparer.razor, src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableComparerContextTest.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRecordComparerTest.razor, src/MudBlazor.UnitTests/Components/TableTests.cs, src/MudBlazor/Components/Table/MudTable.razor.cs, src/MudBlazor/Components/Table/MudTrWithValue.cs, src/MudBlazor/Components/Table/TableContext.cs
Resolves #4988. This PR adds a `Comparer` property to support record types in tables. See additional discussion on #4938 
All existing tests pass and I will add some new ones. I wanted to get this PR started so discussion can occur on it.
=> Table: Add Comparer property to support record types.

src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
=> Docs: fix typo

src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuItemCustomizationExample.razor, src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuItemIconTest.razor, src/MudBlazor.UnitTests/Components/MenuTests.cs, src/MudBlazor/Components/Menu/MudMenuItem.razor, src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Following up on @sensslen's [PR](https://github.com/MudBlazor/MudBlazor/pull/4641), I've added two more Icon properties: `IconSize` and `IconColor`:
=> MudMenuItem: Add  IconColor and IconSize properties

src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/NumericFieldTest.razor, src/MudBlazor.UnitTests/Components/NumericFieldTests.cs, src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
After fixing problems of decimal and longs, nullable's broke with "min" & "max"
For more information see discussion in PR comments #4973 
Resolve issues created with the fixes of #4971
Unit tests have been added to cover the missing cases.
=> NumericField: Resolve nullable issue introduced by #4971

src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselBindingExample.razor, src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselExample.razor, src/MudBlazor.UnitTests/Components/CarouselTests.cs, src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
=> Carousel: Allow to disable swipe gesture

src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSequenceContainsNoElementsTest.razor, src/MudBlazor.UnitTests/Components/DataGridTests.cs, src/MudBlazor/Components/DataGrid/Column.cs
Fixes #4942, 
Fixes #4924, 
Fixes #4921, 
Fixes #4551
=> DataGrid: Fix filter and several other bugs (#4942, #4924, #4921, #4551)

src/MudBlazor.UnitTests/Components/TextFieldTests.cs, src/MudBlazor/Components/Input/MudInput.razor
Fixes #5067 
Small change that removes tabstop from clear button.
visually/manually
=> Input: Remove tabstop from clear button (#5067)

src/MudBlazor/Components/DataGrid/Filter.razor.cs
=> DataGrid: Fix Broken Filter

src/MudBlazor.Docs/Pages/Customization/Theming/Typography.razor
Resolves #5040
Doc change only
=> Docs: Fixed Typography  spelling errors (#5040)

src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor, src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridObservabilityExample.razor, src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridVirtualizationExample.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridObservabilityTest.razor, src/MudBlazor.UnitTests/Components/DataGridTests.cs, src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Added a new example for Virtualization.
Added a new example for Observability.
=> DataGrid: Fix docs discrepancies and add new examples.

src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridAggregationTest.razor, src/MudBlazor.UnitTests/Components/DataGridTests.cs, src/MudBlazor/Components/DataGrid/FooterCell.razor, src/MudBlazor/Components/DataGrid/FooterCell.razor.cs, src/MudBlazor/Components/DataGrid/MudDataGrid.razor
=> DataGrid: AggregationDefinition is applied to groups

src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarRemoveExample.razor, src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
Added documentation for removing a snackbar, ref Issue #5011 
Visually by running the doc locally
=> Docs: Programatically removing a Snackbar

src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterDictionaryGuid.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterGuid.razor, src/MudBlazor.UnitTests/Components/DataGridTests.cs, src/MudBlazor/Components/DataGrid/Filter.razor, src/MudBlazor/Components/DataGrid/FilterDefinition.cs, src/MudBlazor/Components/DataGrid/FilterOperator.cs
fixes #4921.
Currently #4921 crashes because there's no operation available for columns of type System.Guid.
Exception is originated in Column.cs (line = 282)
```csharp
if (filterable)
{
filterContext = new FilterContext<T>(DataGrid);
var operators = FilterOperator.GetOperatorByDataType(dataType);
filterContext.FilterDefinition = new FilterDefinition<T>()
{
Field = Field,
FieldType = FieldType,
Title = Title,
// There are no operators for System.Guid !
Operator = operators.First()
};
}
```
This PR adds support for Guid columns in Grid FilterDefinition.
First implementation only defines 'equals' and 'not equals' operators.
Replicated sample provided by @shyambaidya in the unit tests.
unit
=> DataGrid: Support Guid for FilterDefinition

src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample2.razor
Fixes #5176 
Didn't change any logic
=> Docs: Add ChartOptions to MudChart in LineExample2 (#5176)

src/MudBlazor/Base/MudFormComponent.cs
The `MudFormComponent` `For` summary is incorrect. It says that only string values are supported for validation, but this is no longer the case.
N/A
=> Docs: Fix in Description of MudFormComponent.For

src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
=> TreeView: fix checkbox color not work (#5171)

src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuIconExample.razor
when run code in TryMudblazor the font Awesome not show the icons 
[Before add the css link of font Awesome ](https://try.mudblazor.com/snippet/wkmwONaHTiDYyNBM)
[After add the css link of font Awesome ](https://try.mudblazor.com/snippet/cOQcEDadzCNtpfxP)
=> Docs: Fix FontAwesome Icons not showing up in TryMudBlazor

src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuClickAndTouchEventsExample.razor, src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
Added docs to highlight issues such as #5170.
Resolves #5170
N/A
=> Docs: Clarification for OnClick/OnTouch in MudMenu.

src/MudBlazor.Docs.Server/Pages/_Layout.cshtml, src/MudBlazor.Docs.Wasm/wwwroot/index.html, src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml
It seems depending on your location google analytics may use a different server name to www
Note for my location it uses the server region1
```
Refused to connect to 'https://region1.google-analytics.com/g/collect?v=2&tid=G-PRYNCB61NV&gtm=2oe9c0&_p=2040949807&cid=1770473211.1632356768&ul=en-gb&sr=1440x900&_z=ccd.v9B&_s=1&dl=https%3A%2F%2Fdev.mudblazor.com%2F&sid=1663170260&sct=292&seg=1&dt=MudBlazor%20-%20Blazor%20Component%20Library&en=page_view&_ee=1' because it violates the following Content Security Policy directive: "connect-src 'self'
https://api.github.com
https://raw.githubusercontent.com/MudBlazor/MudBlazor/master/LICENSE
https://www.google-analytics.com
wss://localhost:*".
```
Checking console in browser tools to check error no longer appears after applying fix
=> Docs: Fix content security policy for different regions

src/MudBlazor.UnitTests/Components/ColorPickerTests.cs, src/MudBlazor.UnitTests/Components/TimelineTests.cs, src/MudBlazor/Components/Alert/MudAlert.razor.cs, src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs, src/MudBlazor/Components/Carousel/MudCarousel.razor.cs, src/MudBlazor/Components/Carousel/MudCarouselItem.razor.cs, src/MudBlazor/Components/Chart/MudChart.razor.cs, src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs, src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs, src/MudBlazor/Components/Drawer/MudDrawer.razor.cs, src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs, src/MudBlazor/Components/Pagination/MudPagination.razor.cs, src/MudBlazor/Components/Popover/MudPopover.razor.cs, src/MudBlazor/Components/RTLProvider/MudRTLProvider.razor, src/MudBlazor/Components/Radio/MudRadio.razor.cs, src/MudBlazor/Components/Snackbar/MudSnackbarProvider.razor.cs, src/MudBlazor/Components/Table/MudTablePager.razor.cs, src/MudBlazor/Components/Tabs/MudTabs.razor.cs, src/MudBlazor/Components/Timeline/MudTimeline.razor.cs, src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs, src/MudBlazor/Components/Typography/MudText.razor.cs
This PR names the RightToLeft boolean cascaded by the RTL provider, which resolves #4862 and others. 
Updated unit tests as needed, as a few cascaded the rtl boolean without the RTL provider.
=> RTLProvider: RightToLeft cascading parameter should be named.

.vscode/launch.json, src/MudBlazor.UnitTests.Viewer/Program.cs, src/MudBlazor.UnitTests.Viewer/wwwroot/index.html
Fix app selector in UnitTestViewer
Fix launch configuration in vscode to point to new wasm named projects
Add docs BSS launch config
Running the docs using vscode debugger and checking fix is now working
=> Docs: Fix debug in vscode

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs, src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
A recent PR (#4868) had a CSS regression that caused a width issue on the Docs search autocomplete.
N/A
=> Autocomplete: Fix CSS issue

.gitignore
Added MacOS filesystem files to the `.gitignore` file.
Based on this template: https://github.com/github/gitignore/blob/main/Global/macOS.gitignore
none
=> Exclude MacOS filesystem files

src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneKanbanExample.razor
In the KanBanNewForm class for the KanBan example, changed the error message to represent the max. string length.
None
=> DropZone: Changed KanBanNewForm class in KanBan example

src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioContentPlacementExample.razor, src/MudBlazor/Components/Radio/MudRadio.razor.cs, src/MudBlazor/Styles/components/_radio.scss
=> MudRadioButton: Fixed the content positioning

src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor, src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAdvancedExample.razor, src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridChildRowContentTest.razor, src/MudBlazor.UnitTests/Components/DataGridTests.cs, src/MudBlazor.UnitTests/Components/UserAttributes/UserAttributesTests.cs, src/MudBlazor.UnitTests/Other/CategoryAttributeTests.cs, src/MudBlazor/Components/DataGrid/CellContext.cs, src/MudBlazor/Components/DataGrid/HierarchyColumn.razor, src/MudBlazor/Components/DataGrid/MudDataGrid.razor, src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
I was looking to use the ChildRowTemplate for the DataGrid but the visibility could not be changed for each element in an easy way.
I created a new type of column, HierarchyColumn, that work similar to the SelectColumn, that basically lets the user to show the ChildRowContent for the selected row. It works the same as the Radzen Hierarchy (https://blazor.radzen.com/master-detail-hierarchy).
I have updated the AdvancedDatagridExample to include this functionality.
I have visually tested the feature, updated the existing test for ChildRowContent and created a new one (one is for ChildRowContent visibile and one when is not).
=> MudDataGrid: Added new hierarchy feature

src/MudBlazor.UnitTests/Components/DatePickerTests.cs, src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs, src/MudBlazor/Components/DatePicker/MudDatePicker.cs
Similar to IsDateDisabledFunc, the MudDatePicker component now accepts another function that applies a custom class to specific days.
Implements issue #4666. 
Only visually
=> MudDatePicker: Add support for custom classes to be applied to specific days

src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFormEditTest.razor, src/MudBlazor.UnitTests/Components/DataGridTests.cs, src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
One of my classes has a Mileage property with no setter, which causes a "Property set method not found" error. 
```csharp
public int Mileage => OdometerFinish - OdometerStart;
```
This PR fixes this issue.
Unit tests pass.
=> MudDataGrid: Check if property is writable before setting value.

src/MudBlazor.Docs/Pages/Components/Divider/DividerPage.razor
Resolves #5350 
Fixed the typo in the header in the section about the Inset Divider Type saying "Insert" instead of "Inset"
=> Docs: Fixed typo in Divider page

src/MudBlazor.Docs.Server/Pages/_Layout.cshtml, src/MudBlazor.Docs.Wasm/wwwroot/index.html, src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml, src/MudBlazor.Docs/wwwroot/JS/docs.js
=> Docs: Add workaround for google analytics interop error

src/MudBlazor.Docs.Server/_Imports.razor, src/MudBlazor.Docs.Wasm/_Imports.razor, src/MudBlazor.Docs/_Imports.razor, src/MudBlazor.UnitTests.Viewer/_Imports.razor, src/MudBlazor/Interop/EventHandlers.cs, src/MudBlazor/_Imports.razor
Use conditional compilation to remove onmouseenter onmouseleave event polyfills in net7 where native version now exist.
This allows for backward compatibility and no user code changes in net6 or net7
Run the site check using tooltip.
Run existing testsuite.
=> Events:  Use native mouse events in net7

src/MudBlazor/Components/Table/MudTable.razor.cs, src/MudBlazor/Components/Table/MudTableGroupRow.razor.cs, src/MudBlazor/Components/Table/MudTableSortLabel.razor.cs, src/MudBlazor/Components/Table/TableContext.cs, src/MudBlazor/Components/Table/TableGroupDefinition.cs
Building net6 with net7 surfaces more trim warnings.
Fixing the table ones here.
This is due to the line 
https://github.com/MudBlazor/MudBlazor/blob/be19c09a7745eb060bcd590e099049f467f49566/src/MudBlazor/Components/Table/MudTable.razor.cs#L63
I think it's useful to fix these in the dev branch and I want to check the build output on the build server.
Build net6 with net7 SDK and fix resulting warnings.
=> MudTable: Fix table trim warnings (net7 linker)

src/MudBlazor/Services/EventManager/EventManager.cs, src/MudBlazor/Services/IIJSRuntimeExtentions.cs
Additional Annotations in preparation for net7
Build net6 and net7 check for warnings
Run test suite
=> Trimming: Additional annotations

src/MudBlazor.UnitTests/Components/RadioTests.cs, src/MudBlazor.UnitTests/Services/EventListenerTests.cs
Fix a radio test that had framework version in the check.
Fix EventListener tests due to net7 having new properties in the MouseEventArgs
net6 and net7 test suite
=> Tests: Make tests net7 friendly

src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsPreventDefaultExample.razor, src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
In our SwipeArea, the compoent only works if the swipe amount is bigger than 100px. Its hardcoded and not good for all situations. 100px is big dimension for minimum swipe (Nearly 1/3 of mobile width). So we added a `Sensitivity` parameter to let users to choose minimum swipe amount they want to work. (The default is still same, so no breaking changes.)
And another addition, we added a method that gets `SwipeDelta`. With this value users can specialized their code regard to swiped amount. An example a user want to run a method for each 20px swipe amount.
Docs already updated to show and play with this new parameters:
https://user-images.githubusercontent.com/78308169/195810720-46049bbb-911a-46a1-a6a5-8fcbadf5d213.mp4
=> MudSwipeArea: Add Sensitivity and SwipeDelta

src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
Adds a missing description in the Getting Started/Installation guide about where to register Services. Each of the other tasks explains which file needs to be changed, so this follows that pattern.
=> Docs: Installation guide should specify where to register Services

src/MudBlazor.UnitTests/Components/NavLinkTests.cs, src/MudBlazor/Components/NavMenu/MudNavLink.razor, src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
Added new parameter to change NavLink -> ActiveClass
Added test to NavLinkTests
=> MudNavLink: Allow custom ActiveClass

.github/workflows/ci-cd.yml, global.json, src/.editorconfig, src/Directory.Build.props, src/MudBlazor/MudBlazor.csproj
Add a net7 build to our process using multi-targeting.
For simplicity we keep the tools and website at net6 for now.
We will keep the package versions the same so for example 6.0.19 will contain net6 and net7
Your app will choose the correct dll depending on your target framework.
Fixes https://github.com/MudBlazor/MudBlazor/issues/5712
NOTE: Warnings as errors turned off for now until we decide on a solution for the trim warnings
Build
dotnet pack
Check contents of nuget
=> Build: add net7 library (multi-targeting)

README.md
Updating the README.md to include text that indicates what versions .NET 7 are supported for
N/A
=> README: Update to reflect support for .NET 7
