src/MudBlazor/Components/Tabs/MudTabs.razor.cs

- Added "Class" property on CssBuilder for TabsClassnames; 
- Added "TabPanelClass" property on MudTabs Component for using on CssBuilder for PanelsClassnames.
Usage:
<MudBlazor.MudTabs Class="pt-4" TabPanelClass="pt-6" >
...
</MudBlazor.MudTabs>
MudTabs wasn't applying the values from Class property to element and also wasn't able to define custom classes for MudTabPanel.

Custom CSS Classes for MudTabs and MudTabPanel

---

src/MudBlazor/Components/Tabs/MudTabs.razor.cs

The ideia is about to apply custom classes for TabPanel, and not for the Active panel host. I'm fixing my mistake.

Changed TabPanelClass declaration frorm PanelsClassnames() to GetTabClass()

---

src/MudBlazor/Components/Rating/MudRatingItem.razor.cs

Hello!
Current behaviour: (looks worse "IRL", think gif capturer misses some frames)
New behaviour:
Let me know if there is anything I can change.

fixed rating flicker issue

---

src/MudBlazor/Components/Input/MudInput.razor.cs
src/MudBlazor/Components/Input/MudInputLabel.razor.cs
src/MudBlazor/Components/InputControl/MudInputControl.razor
src/MudBlazor/Components/TextField/MudTextField.razor
src/MudBlazor/Styles/Components/_input.scss
src/MudBlazor/Styles/Components/_inputcontrol.scss

- Margin dense did not work. Needed to pass through the margin prop to label und input.
- Removed multiline classes in _input.scss. Multiline is done by textarea.
- Adjusted dense margin on input-control

Fixed dense margin in mudtextfield

---

src/MudBlazor/Components/Select/MudSelect.razor

It is not possible to set MudSelect to Margin.Dense. The margin prop is not delivered to the MudInput component inside.

MudSelect; Set Margin is not possible. Margin prop should be delivered to the inner input

---

src/MudBlazor/Components/TextField/MudTextField.razor

Events onkeydown, onkeyup, onkeypress were not forwarded from MudInput to MudTextfield.

Fixed missing events (keydown, keyup, keypress)

---

azure-pipelines.yml
src/.editorconfig
src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
src/MudBlazor.UnitTests/Services/ResizeListenerServiceTests.cs
src/MudBlazor/MudBlazor.xml
src/MudBlazor/Providers/BrowserWindowSizeProvider.cs
src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
src/MudBlazor/Services/ResizeListener/ServiceCollectionExtensions.cs

I noticed `SmAndDown` didn't work properly when using `<MudHidden>`, @henon provided fixed code for this, I added unit tests. The tests were written using the old code and they indicated all 3 `*AndDown` returned incorrect values on the `ResizeListenerService.IsMediaSize` method. After replacing the code, the unit tests all indicated success.
Changes:
- Edited `.editorconfig` to specify indent_style = space and indent_size = 4 (my VS is set to tabs, needed to do this to get spaces)
- Created a new provider `BrowserWindowSizeProvider`/`IBrowserWindowSizeProvider`
- Moved `ResizeListenerService.GetBrowserWindowSize` to `BrowserWindowSizeProvider`.
- Made `ResizeListenerService.GetBrowserWindowSize` backwards compatible by calling the newly moved method in `BrowserWindowSizeProvider`
- Added …

Fix breakpoints

---

src/MudBlazor/Styles/Core/_blazor.scss

When some unhandled exception occured in app blazor show on buttom window with reload button.
But when exception happen with oppened drawer or dialog z-index for error message less then mud components therefor I can't press reload. This PR fixes this problem

Fixed z-index for blazor ui

---

src/MudBlazor.Docs/Models/DocStrings.generated.cs
src/MudBlazor.Docs/Models/Snippets.generated.cs
src/MudBlazor.Docs/Pages/Components/TextField/Code/DebouncedTextFieldExampleCode.razor
src/MudBlazor.Docs/Pages/Components/TextField/Examples/DebouncedTextFieldExample.razor
src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor.UnitTests/Generated/_AllApiPages.cs
src/MudBlazor.UnitTests/Generated/_AllComponents.cs
src/MudBlazor/Components/Input/MudDebouncedInput.cs
src/MudBlazor/Components/TextField/MudTextField.razor
src/MudBlazor/Components/TextField/MudTextField.razor.cs

This adds `MudDebouncedInput` class in order to provide `TextField `with capabilities to perform debounced searches.
`TextField `now inherits from `MudDebouncedInput`, instead from `MudBaseInput`.
The two parameters that `MudDebounceInput `adds are double `DebounceInterval `(named this way after the same property in Autocomplete) and an `EventCallback<string> OnDebounceIntervalElapsed,` that triggers when the interval has elapsed.
Also, if `DebounceInterval `is set, Immediate is set to true automatically.
Added example in `TextFieldPage`
Added tests for this new functionality in `TextField`

Debounced TextField

---

src/MudBlazor.Docs/Models/DocStrings.generated.cs
src/MudBlazor.Docs/Models/Snippets.generated.cs
src/MudBlazor.Docs/Pages/Components/Table/Code/TableInlineEditExampleCode.razor
src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor
src/MudBlazor.Docs/Utilities/SampleCommand.cs
src/MudBlazor.UnitTests/Generated/_AllApiPages.cs
src/MudBlazor/Components/Table/MudTable.razor.cs
src/MudBlazor/Components/Table/MudTr.razor

Work made:
- Changed CommitEditCommandParameter Property from string to object;
- Added (object)Item as parameter on OnCommitEditHandler void;
- Implemented row level item as CommitEditCommand.Execute, if CommitEditCommandParameter  is null;
- Added CommitEditCommand usage on Docs sample.
I would like to request a review to @henon , when possible.
Thanks.

Fixes for Table's Commit Edit Command

---

src/MudBlazor.Docs/MudBlazor.Docs.csproj

- Change the csproj to use compiled `Docs.Compiler` if available.
- Saves a couple of seconds in the dev cycle.
@henon

Use binary Docs.Compiler if available

---

src/MudBlazor.Docs/Pages/Components/Button/ButtonPage.razor
src/MudBlazor.Docs/Pages/Components/Button/Code/ButtonLinkExampleCode.razor
src/MudBlazor.Docs/Pages/Components/Button/Examples/ButtonLinkExample.razor
src/MudBlazor.UnitTests/Components/ButtonsTests.cs
src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor/Base/MudBaseButton.cs
src/MudBlazor/Components/Button/MudButton.razor
src/MudBlazor/Components/Button/MudFab.razor
src/MudBlazor/Components/Button/MudFab.razor.cs
src/MudBlazor/Components/Button/MudIconButton.razor
src/MudBlazor/Components/Element/MudElement.cs
src/MudBlazor/TScripts/window-open.js

This enables button to render the html element you want through the `HtmlTag` parameter.
Also, if the `Link` parameter is set, the button renders automatically an anchor element. Fixes #293 
If the `Target` parameter is set, the component adds automatically `rel="noopener"`, for safety.
This will also enable the creation of a file upload button, rendering a label instead of a button (#181)
Fixes #286 
Added tests and examples

Feature mud element in button

---

src/MudBlazor/Styles/core/_base.scss

This fixes #297
```
html{
height:100%
}
```
This CSS rule is preventing Blazor default scroll to top after navigation to work properly.
I found out that Blazor already has implemented the default browser behavior of scroll to top after navigate to another page (see [this](https://github.com/dotnet/aspnetcore/blob/577f1a760fb56f67f59aa1057458a1bc0c6730e8/src/Components/Web.JS/src/Rendering/Renderer.ts#L82)) , but MudBlazor CSS layout is fighting against it.
I think that `html{height:100%}` has the same effect that  `html{height:100vh}`, limiting to the size of the screen the height of the body, that already has an unnecessary `body{height:100%}` .
So, if we remove the html height setting, everything works.
I think that the basic layout has to be reconsidered to use best practices to not …

fix scroll after navigation

---

src/MudBlazor.UnitTests/Extensions/EnumExtensionsTests.cs
src/MudBlazor/Extensions/EnumExtensions.cs

Instead of having to create an extension method for each component you want to call ToDescriptionString(), which is cumbersome and prone to errors, because you must copy the code each time and you can forget it, I made the extension available to all Enum. If they have a description, returns the description; if not, returns the ToString().ToLower() instead of empty.string, because it's the expected.

Make ToDescriptionString() available to all Enum

---

src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
src/MudBlazor.Docs.Compiler/TestsForExamples.cs
src/MudBlazor.Docs/_Imports.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRowClickTest.razor
src/MudBlazor.UnitTests.Viewer/_Imports.razor
src/MudBlazor/Components/Dialog/DialogOptions.cs
src/MudBlazor/Components/Dialog/DialogParameters.cs
src/MudBlazor/Components/Dialog/DialogReference.cs
src/MudBlazor/Components/Dialog/IDialogReference.cs
src/MudBlazor/Components/Dialog/MudDialogInstance.razor
src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
src/MudBlazor/Components/Dialog/MudDialogProvider.razor
src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
src/MudBlazor/Components/Select/IMudSelect.cs
src/MudBlazor/Components/Select/MudSelect.razor
src/MudBlazor/Components/Select/MudSelect.razor.cs
src/MudBlazor/Components/Select/MudSelectItem.razor.cs
src/MudBlazor/Components/Table/MudTable.razor
src/MudBlazor/Components/Table/TableRowClickEventArgs.cs
src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
src/MudBlazor/Interfaces/IDialogService.cs
src/MudBlazor/RemovedNamespaces/Components.Select.cs
src/MudBlazor/RemovedNamespaces/Components.Table.cs
src/MudBlazor/RemovedNamespaces/Dialog.cs
src/MudBlazor/Services/DialogResult.cs
src/MudBlazor/Services/DialogService.cs

- As discussed with @henon 
- We feel for the developer it makes sense for all components to live in `MudBlazor`
- We are unlikely to encounter naming collisions and nearly all components are in `MudBlazor` already
- I have left 3 holding namespaces so it doesn't break `usings` in existing user code.
- Removed namespaces will show as unused (greyed out) in user code but will not break the compiler.
- We need to review PRs so that we don't get a proliferation of different namespaces in Components in the future.

Fix - All components should live in MudBlazor

---

src/MudBlazor.Docs.Client/wwwroot/index.html
src/MudBlazor.Docs.Server/Pages/_Host.cshtml
src/MudBlazor.Docs/MudBlazor.Docs.csproj
src/MudBlazor.Docs/Pages/Components/Button/Code/ButtonLinkExampleCode.razor
src/MudBlazor.Docs/Pages/Components/FileUpload/Code/FileUploadButtonExampleCode.razor
src/MudBlazor.Docs/Pages/Components/FileUpload/Code/FileUploadIconButtonExampleCode.razor
src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadButtonExample.razor
src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadIconButtonExample.razor
src/MudBlazor.Docs/Pages/Components/FileUpload/FileUploadPage.razor
src/MudBlazor.Docs/Shared/NavMenu.razor

This is of some interest, as it has been requested several times.
As discussed with @henon , this is a first step to have a real file upload component that encapsulates all the functionalities. But I think it is worth to show it in the documentation, because is easy to follow.
I installed a nuget package in the docs page, but it shouldn't be a problem, because the framework doesn't depend on it, just the docs page to illustrate the example.
It works both in 3.1 and in 5.0

Added FileUpload example

---

src/MudBlazor.Docs.Client/wwwroot/index.html
src/MudBlazor.Docs.Server/Pages/_Host.cshtml
src/MudBlazor.Docs/Pages/Components/Element/Code/MudElementRefExampleCode.razor
src/MudBlazor.Docs/Pages/Components/Element/ElementPage.razor
src/MudBlazor.Docs/Pages/Components/Element/Examples/MudElementRefExample.razor
src/MudBlazor.Docs/wwwroot/JS/examples.js
src/MudBlazor.UnitTests/Components/ButtonsTests.cs
src/MudBlazor/Components/Element/MudElement.cs

MudElement is now able to receive a reference (needed in buttons for ripple).
You just has to pass it like
`<MudElement @bind-Ref="myRef"/>`
The examples serve as tests and documentation

Added MudElement reference two-way binding

---

src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Components/Field/MudField.razor.cs
src/MudBlazor/Components/Input/MudInput.razor.cs
src/MudBlazor/Components/Select/MudSelect.razor
src/MudBlazor/Components/Select/MudSelect.razor.cs
src/MudBlazor/Components/TextField/MudTextField.razor.cs

This fixes #325
There was a bug when setting both placeholder and label, as they overlap. The expected is that when placeholder and label are both set, the label should shrink.
Also, MudBaseInput should not have nor Label nor Placeholder, because this allows descendants with no placeholder or no label to have one.
Some descendants should have only label, like MudSelect, others should have only placeholder, like MudInput.
I removed Label and Placeholder from MudBaseInput and reapplied only where were needed.
Before that was producing a bug on MudInput, because it allowed to have label overlapping placeholder, and MudInput should not have label.
Added tests to verify this doesn't occur any more.

Fix MudTextfield when placeholder and label are both set 

---

src/MudBlazor/Components/Menu/MudMenu.razor.cs

- These functions are obviously synchronous.
- While this technically changes the public api surface even the examples don't await a task.  It just doesn't make sense.
- i.e. I don't imagine anyone is doing `var task = await MudMenu.MenuClose();`
- What this PR will do is correct the async and return type and stop giving users CS4014 - Because this call is not awaited, execution of the current method continues before the call is completed

Fix incorrect async MenuClose() MenuOpen()

---

src/MudBlazor/Styles/components/_inputcontrol.scss

- First commit: when you try to click on a` MudTextField ` **Text variant**, in the label, the input should receive the focus and the label should shrink, but it won't, as the label will receive the click.
This fixes it.
- Second commit: This is optional, but I think it should be considered. `MudTextField `label should be text-secondary. If not, you have the same color for the text entered as for the label, which is confusing, and you don't know if it's a `MudInput `with text or a `TextField `with no text and a label.
`MudInput `with text inside (no label)
`MudTextField `with no text and with label. The user could think: _Is this field already filled?_ Imagine a large form...
`MudTextField `with a label and no text. Could be also MudInput with placeholder and no text. But the point is "no …

Fix textfield text label

---

src/MudBlazor.Docs/Style/Components/_DocsSection.scss

- Changes this (notice the right button causing overflow)
- Into this
- By adding 
```
.docs-section-content-inner {      
flex-wrap:wrap;
}
```
I don't think we have an example that needs `flex-wrap:nowrap`
It doesn't affect to the framework, just to the documentation site

Fix unresponsive flexbox in menu examples

---

src/MudBlazor.Docs/Extensions/NavigationManagerExtensions.cs
src/MudBlazor.Docs/Models/DocsComponents.cs
src/MudBlazor.Docs/Shared/MainLayout.razor
src/MudBlazor.Docs/Shared/NavMenu.razor
src/MudBlazor.Docs/_Imports.razor

This is a feature concerning user experience in documentation site.
**It doesn't affect the framework API**
The navbar expands the group or subgroup included in the link of the page.
Example:
**url**: `/components/button`
Expands the group `components` and the subgroup `buttons` 
<br/>
<br/>
<br/>
This is much more user friendly, because it saves several clicks

NavMenu expands subgroup when link points to it

---

src/MudBlazor/MudBlazor.csproj

- Follow up to removing dotnet tool webcompiler config

Fix include for non-existent file

---

src/MudBlazor/Components/Drawer/MudDrawer.razor
src/MudBlazor/Components/Layout/MudLayout.razor

- Why? See this [reference](https://stackoverflow.com/questions/58852101/bl0005-external-parameter-usage-why-is-a-warning-for-that) that also links to aspnetcore repo.
- Microsoft really dont want you to set component parameters outside the component because it can break the render tree.
- In any case the changes in this PR are logical if we are going to have other components inside MudLayout that need to be notified of RTL.
- If you wanted to really optimise you can set the value once only (for example if your audience was RTL only.
- See [Chris Sainty's post](https://chrissainty.com/understanding-cascading-values-and-cascading-parameters/) for a good in depth guide to Cascading Parameters
- Built and tested on the docs site.

Fix BL0005 RTL Support - Use cascading parameters instead

---

src/MudBlazor/Components/Snackbar/Snackbar.cs
src/MudBlazor/Components/Snackbar/State.cs

Following changes were made:
-The cursor pointer is used on snackbar as soon as an onclick handler is defined (previously, the cursor was shown only is there was not a close button, which is not correct, because we would want to have both a close button and an onclick handler)
-The Clicked method always close the snackbar, except if no onclick handler defined

Always close snackbar on click (resolves #362)

---

src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteUsageExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest1.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest2.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest3.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest4.razor

- One example fixed NOTE it might be better to provide web api for the `PeriodicTable` and `States` datasets at mudblazor.com.
- Four tests fixed -  It is common to use Task.FromResult when mocking to avoid having to test async.
- There are no more examples of async without await now.
- I have not checked in the generated code as that is disappearing soon.

Fix CS1998 Autocomplete Example and tests

---

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor

Previous version did not have a link back to UserAttributes.
added '@attributes="UserAttributes" to first div section.

Added UserAttributes to MudAutocomplete.razor

---

src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor

Currently, when you search for an icon, then remove all the text in the search field, the web app crashes: https://mudblazor.com/features/icons
This is because `String.Contains` doesn't accept null, and the SearchText is null when the text field is made empty.
I simply added a `string.IsNullOrWhiteSpace` check before the contains.

Fixed crash when searching for icons with empty/null string

---

src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
src/MudBlazor.Docs.Compiler/TestsForExamples.cs
src/MudBlazor.Docs.Server/Startup.cs
src/MudBlazor.Docs/Pages/Components/Dialog/Code/DialogScrollableExample_DialogCode.razor
src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogScrollableExample_Dialog.razor

Javascript console was reporting an error when trying to open the scrollable dialog example in docs in Blazor WebAssembly (Docs.Client)
This was due to the usage of WebClient, which is not supported on wasm platform. Code was refactored to use HttpClient.

Fixed: Scrollable dialog example in doc not working in wasm

---

src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogScrollableExample.razor
src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogSetOptionsExample.razor
src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogSetOptionsExample_Dialog.razor
src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs

Sometimes it is useful to let the dialog component decides itself some of its options. For example, if it should have a header, a close button, if it should be full width, etc.
The MudDialogInstance object received by the dialog component already had a SetTitle method, which can be used by the component to define its own title, but there was no SetOptions method to control the other options.
This PR adds a SetOptions method on the MudDialogInstance class and an usage example in the doc.
(also did a little cleanup on DialogScrollableExample to uniformize and remove some dead code)

Allow dialog options to be set from dialog component itself

---

src/MudBlazor/Components/Snackbar/CommonSnackbarOptions.cs
src/MudBlazor/Components/Snackbar/SnackbarConfiguration.cs
src/MudBlazor/Components/Snackbar/SnackbarOptions.cs

Setting ShowCloseIcon to false on global snackbar settings did not hide the close icon on the snackbars with default options (but it was still possible to hide it on a one-by-one basis by using the Options object returned by Snackbar.Add, as demonstrated in the Doc)
The problem was that all properties from global settings object were copied when a new snackbar was initialized, except the ShowCloseIcon property.
What I did:
-Moved all the copy instructions on a copy constructor on CommonSnackbarOptions class
-Added the missing line to copy ShowCloseIcon
-Some refactoring on SnackbarOptions class

Bug fix: global snackbar ShowCloseIcon not working

---

src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs

- Some easy ones.
- It was decided @henon @mikes-gh that it doesnt make sense to await `Dialog.Cancel()` or `Dialog.Close()` therefore we discard `_ =` the task at the component level.
- We wait for the event registration in the resize listener and also de-registration on dispose.

Fix CS4014 Simple

---

src/MudBlazor.Docs/Pages/Components/Rating/Examples/RatingReadonlyExample.razor
src/MudBlazor.Docs/Pages/Components/Rating/RatingPage.razor
src/MudBlazor.UnitTests/Components/RatingTests.cs
src/MudBlazor/Components/Rating/MudRating.razor
src/MudBlazor/Components/Rating/MudRating.razor.cs
src/MudBlazor/Components/Rating/MudRatingItem.razor
src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
src/MudBlazor/Styles/components/_rating.scss

Fixes #398 
- Rating items should become inactive the moment the mouse is out no matter what.
- Read only ratings show the ratings without allowing interactions. Inputs aren't rendered and events aren't even registered to save resources.

Bug fix & Read only ratings

---

src/MudBlazor/Components/Drawer/MudDrawer.razor
src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
src/MudBlazor/Styles/MudBlazor.scss
src/MudBlazor/Styles/core/_base.scss
src/MudBlazor/Styles/utilities/_scroll.scss
src/MudBlazor/TScripts/scrollto.js

- Added a parameter `LockScroll` in MudOverlay to lock the scroll when showing the overlay
- Unset the body and html heights, so scroll works
- This solves several problems related to scroll
- To be solved: the navmenu drawer does not block the body in the mobile version

Added a parameter in MudOverlay to block scroll

---

src/MudBlazor/Components/Dialog/DialogReference.cs
src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs

As discussed in PR #390, here's some code fixes to cleanup async methods. Dismiss is now sync in this version. Some dead code removed also.

Cleanup async dialog methods

---

src/MudBlazor/MudBlazor.csproj

-  This change to the csproj includes the static assets on first build.
- Since they are generated and not in the repo we include them at build time even if they were never present.
- This allows clone then start the website in one step without requiring a further rebuild

Update csproj to include static on first build

---

src/MudBlazor.Docs.Compiler/CodeBuilder.cs
src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
src/MudBlazor.Docs.Compiler/TestsForExamples.cs
src/MudBlazor/Components/Field/MudField.razor
src/MudBlazor/Components/Input/MudInput.razor
src/MudBlazor/Components/Input/MudInputAdornment.razor

- MudInputAdornment lives next to MudInput.
- However it is also used by MudField which didn't have the using statement resulting in RZ10012.
- I simplified the Internal namespace to allow for other internal components later.  I am assuming from the naming of the namespace MuInputAdornment is not intended to be used directly.
- It seemed like a good time to refactor the test usings after the test failure

Fix missing using in MudField

---

src/MudBlazor/Components/Layout/MudLayout.razor

- `FireDrawersChanged` is used to notify the parent (MudLayout) of a drawer state changed in the model.

Remove unused event in MudLayout

---

src/MudBlazor.Docs/Utilities/SampleCommand.cs
src/MudBlazor.UnitTests/Mocks/MockResizeListenerService.cs

- These 2 examples are required member to implement an interface so disable for that member only.

Fix CS0067 Unused member

---

src/MudBlazor.UnitTests/Components/FormTests.cs

As discussed in #428, here's the test for async validation in a separate PR.
NOTE: This test will fail until #428 is merged

Add test for async field validation timings

---

.azure/pipelines/jobs/default-test.yml
.vscode/tasks.json

- In #428 we discovered that the build system will try a test for an hour if it has an infinite loop.
- This change exits the individual test at 60s and enables quicker diagnosis.
- It also makes this change for vscode users.
- Please can we make the pipeline logs public as per #387

Exit tests if taking too long

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableFilterTest1.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTable.razor.cs

- As described
- Changed visibility of `FilteredItems` because I think its useful info for the end user  (and the test)
- FilteredItems is `IEnumerable` so cant my mutated and is safe.

Add filtered table test

---

src/MudBlazor.Docs.Compiler/DocStrings.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Base/MudBooleanInput.cs
src/MudBlazor/Base/MudComponentBase.cs
src/MudBlazor/Base/MudFormComponent.cs

I noticed that even if BaseInput had some null-handling for Converter property, it is widely used in other components assuming there is always a Converter. (In fact, a default Converter is always created, so the only way to NOT have a Converter would be to manually set it to null, which would make many components to throw errors)
I think it makes sense that an input component should **always** have a Converter. Also, I noticed some similarities between MudBaseInput and MudBooleanInput (each one is defining a Converter property, etc) so I wanted to define them once in a higher parent class.
In this PR:
-Converter property is guaranteed to never be null (so null checks no longer needed and have been removed)
-Converter property and other related properties (Culture, etc) have been moved to …

Move Converter property to MudFormComponent and make it mandatory

---

src/MudBlazor/Components/Chart/MudChart.razor.cs

- Base type to longer requires hiding as @Codinkat  removed it as part of https://github.com/Garderoben/MudBlazor/pull/457

Fix CS0109 Base member changed visibility

---

.vscode/tasks.json
src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj

- Adds generate coverage data to the build.
- Adds a vscode task to build test coverage report
- FUTURE: Use the coverage data to post to coveralls.io for a coverage badge.
- FUTURE: Show coverage on PR.

Add test coverage xplat

---

.vscode/tasks.json

- Hopefully this is it now
- Limit coverage to MudBlazor.dll only
- I know this is only for vscode users but it is also a good reference for command line build coverage analysis

Test coverage for MudBlazor only

---

.vscode/tasks.json
src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj

- This is purely a devops PR
- This adds CLI code coverfage report generation using [coverlets](https://github.com/coverlet-coverage/coverlet) and [ReportGenerator](https://github.com/danielpalme/ReportGenerator)
- It adds a couple of dev only packages to the `MudBlazor.UnitTests` assembly for generating reports
- It does not slow down the build.
- It does not do anything without switches i.e. `dotnet test` behaves the same.
- It does not affect the API.
- I could add a powershell script to generate and open a coverage report if people think it would be useful.
- Otherwise you can examine the vscode task to see how to produce a report

Coverage reports vscode

---

src/MudBlazor/Components/Icon/MudIcon.razor
src/MudBlazor/Components/Icon/MudIcon.razor.cs

Adding custom content to MudIcon with a viewbox different than the current default, it results an invalid html. This PR make it possible to specify the viewbox for the svg html tag.

Custom viewbox for MudIcon

---

src/MudBlazor/Extensions/TimeSpanExtensions.cs

-  As described value is never used

Remove unecessary code

---

src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelSimpleExample.razor
src/MudBlazor.Docs/Pages/Components/Table/Examples/TableRelationalExample.razor
src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
src/MudBlazor/Components/Collapse/MudCollapse.razor
src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor
src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
src/MudBlazor/Components/Table/MudTable.razor
src/MudBlazor/Components/Table/MudTable.razor.cs

Added a parameter to explicitly set max-height for MudExpansionPanel and underlying MudCollapse.
The default css value might be too low currently set at 2000px.
The max-height parameter is required for the transition animation to work correctly. the animation is affected by the max-height parameter, so a scaling of the transition-duration was implemented as well to keep the animation smooth for different values of max-height.

Enhanced MudExpansionPanel component with max-height parameter

---

.azure/pipelines/jobs/default-build.yml

- This does not affect the local dev cycle.
- This is only CI builds
- Since some considerable effort was made to eliminate the compiler warnings with some good benefits this change will prevent any more warnings. (Although failing builds can still be checked in like normal)
- The warnings had built up over a long period and you have to try quite hard to get a compiler warning now.  If you do its likely because something really does need fixing.
- Please only use #pragma as a last resort.

Don't check in compiler errors

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.razor
src/MudBlazor/Components/DatePicker/MudDatePicker.razor.cs
src/MudBlazor/Styles/components/_pickerdate.scss
src/MudBlazor/TScripts/scrollHelpers.js

- Add year to month picker closes https://github.com/Garderoben/MudBlazor/issues/209
- Gives the advantage of year selection in calendar only mode.
- Changes goto month instead of date after year selection
- Fixes https://github.com/Garderoben/MudBlazor/issues/505 jumpy scrollto
- Add tests

Add year monthpicker

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/TimePickerTests.cs
src/MudBlazor/Base/MudBasePicker.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.razor
src/MudBlazor/Components/DatePicker/MudDatePicker.razor.cs
src/MudBlazor/Components/Picker/MudPicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
src/MudBlazor/TScripts/scrollHelpers.js

- OpenTo is supposed to not change state. ie If you set a picker to open to year it should always do so.
- The current code reused the OpenTo state in its rendering logic so its initial state was lost.
- I fixed this by loading OpenTo to a private variable when opening of the picker.
- Moved MudPicker code to separate `razor.cs` file.
- Actually took a lot longer than I thought.
- Added tests.

Fixes #499 OpenTo for pickers

---

src/MudBlazor/Components/TimePicker/MudTimePicker.razor

- Fixes #513. Due to stopPropagation not being set to true overlay was receiving click and closing dialog early
- Thanks to @henon for pointer

Fixes #513 Dialog time picker closes early

---

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Styles/components/_list.scss
src/MudBlazor/TScripts/scrollHelpers.js

- When scrolls down, the autocomplete must wait until reach the end of the container until to start to scroll
- The opposite when scrolls up
- After close the menu, the scroll position must be restored to top of the container
- The scroll container must be the MudList, not the MudPopover, in order to let the items scroll alongside the parent. That's why I applied the MaxHeight of the popover to the list.

Fix autocomplete jumping on keyboard

---

src/MudBlazor/Components/Drawer/MudDrawer.razor

- IBrowserWindowSizeProvider provides functionality and wraps JSInterop

Unnecessary use of JSInterop

---

src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Base/MudFormComponent.cs
src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor.cs
src/MudBlazor/Extensions/TaskExtensions.cs

Here's an adjustment PR for small things I did previously about async calls.
But first, I realized that maybe I was misleading in previous discussions (#521), so I would like to clarify.
I said that uncaught exception will break the app. Well, not always. It depends if the task is awaited and how. In fact, the basic idea is that when an exception is thrown inside the async part of a task, it is stored in the Task object and then it's up to the caller to do whatever he wants with it.
So, to resume:
1-If a task is just invoked (ie, without await), the exception stored in the task will be ignored, so nothing will happen and execution of this task will just silently fail (not even shown in console!). So it is pretty bad and hard to debug :-(
2-If task is awaited, the IL code inserted by the …

Adjustment & clarifications on async calls

---

src/MudBlazor/Components/Alert/MudAlert.razor
src/MudBlazor/Components/Alert/MudAlert.razor.cs

Removed OnClicked since it was not really needed and contains no logic, so OnClick eventcallback is bound directly to the element (and task correctly awaited by Blazor)

Fix async calls in Alert

---

src/.editorconfig

- Closes #307 
- This adds the roslyn teams sensible defaults for coding standards
- The advantage of using `.editorconfig` is that its not enforced at build time
- We can run [dotnet format](https://github.com/dotnet/format) on build when we are ready which will format code on build.  This only does white space.
- This stops diff noise from white space.
- Initially I suggest running `dotnet format` per project when it has no pending contributions.
- The library itself we may need to do by area to prevent conflicting everyone.
- Its a bit of pain but important in the long run.

Coding standards

---

src/MudBlazor.Docs.Compiler/XmlDocumentation.cs
src/MudBlazor.Docs/Models/XmlDocumentation.cs

- Produces compiler warning in net5 so pre-empt in develop

Remove depreciated CodeBase member

---

src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor
src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxReadOnlyExample.razor
src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchReadOnlyExample.razor
src/MudBlazor.Docs/Pages/Components/Switch/SwitchPage.razor
src/MudBlazor/Base/MudBooleanInput.cs
src/MudBlazor/Components/CheckBox/MudCheckBox.razor
src/MudBlazor/Components/Switch/MudSwitch.razor

Issue #528 
I think that MudRadioGroup and MudSlider should be discussed if they needs to obtain ReadOnly mode, because the implementation can be bit trickier and probably contain javascript. I am pretty new to Blazor and there is clearly a knowledge gap. 
Propably the disable state is enough.

Implementing ReadOnly for CheckBox & Switch

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/DateRangePickerTests .cs

- Even adding a delay the tests were still failing.  We now wait an extra 5 secs and succeed early.

Fix datepicker closing delay tests

---

src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj
src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldFocusExample.razor
src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldSelectExample.razor
src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldSelectRangeExample.razor
src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
src/MudBlazor/Base/MudBaseButton.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
src/MudBlazor/Components/Input/MudDebouncedInput.cs
src/MudBlazor/Components/Input/MudInput.razor.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs
src/MudBlazor/Components/TextField/MudTextField.razor.cs
src/MudBlazor/TScripts/select.js

- Make focus and select work in net 3.1
- This is part of a pair.
- These changes are forward ported to net5 until we move.
- After that we can use JSRuntime the net5 way

Backport focus and select

---

src/MudBlazor/Base/MudBaseButton.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Components/Input/MudInput.razor.cs

- Use the old way until we switch to net5 for development.
- This will ease the transition

Forwardport net 3.1 focus and select

---

src/MudBlazor/Components/Card/MudCardMedia.razor
src/MudBlazor/Components/Card/MudCardMedia.razor.cs
src/MudBlazor/Components/Collapse/MudCollapse.razor
src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
src/MudBlazor/Components/Layout/MudLayout.razor
src/MudBlazor/Components/Layout/MudLayout.razor.cs
src/MudBlazor/Components/Progress/MudProgressCircular.razor
src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
src/MudBlazor/Components/Progress/MudProgressLinear.razor
src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
src/MudBlazor/Components/Skeleton/MudSkeleton.razor
src/MudBlazor/Components/Skeleton/MudSkeleton.razor.cs

- We said we would have code behind for all components
- This PR moves adds code behind for some of the larger components (I left the ones with small `@code`)
- None that are being worked on as far as I know.
- Added inheritance to MudComponentBase for MudCollapse

Add code behind

---

README.md
src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
src/MudBlazor.Docs/Pages/Getting Started/Installation/ManualMarkDown/MarkdownAddComponents.razor
src/MudBlazor.Docs/Pages/Getting Started/Installation/ManualMarkDown/MarkdownRegisterServicesServer.razor
src/MudBlazor.Docs/Pages/Getting Started/Installation/ManualMarkDown/MarkdownRegisterServicesWebAssembly.razor
src/MudBlazor.UnitTests.Viewer/Program.cs
src/MudBlazor.UnitTests.Viewer/Shared/MainLayout.razor
src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor.UnitTests/Components/BreadcrumbTests.cs
src/MudBlazor.UnitTests/Components/ButtonsTests.cs
src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/DateRangePickerTests .cs
src/MudBlazor.UnitTests/Components/DialogTests.cs
src/MudBlazor.UnitTests/Components/ElementTests.cs
src/MudBlazor.UnitTests/Components/FormTests.cs
src/MudBlazor.UnitTests/Components/HighlighterTests.cs
src/MudBlazor.UnitTests/Components/ListTests.cs
src/MudBlazor.UnitTests/Components/RadioTests.cs
src/MudBlazor.UnitTests/Components/RatingTests.cs
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor.UnitTests/Components/SnackbarTests.cs
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor.UnitTests/Components/TabsTests.cs
src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor.UnitTests/Components/TimePickerTests.cs
src/MudBlazor.UnitTests/Components/ToggleIconButtonTest.cs
src/MudBlazor.UnitTests/Components/TreeViewTest.cs
src/MudBlazor.UnitTests/Extensions/TestContextExtensions.cs

- Updated to reflect changes for `AddMudServices()`
- @porkopek Can you update your docs for ScrollServices please 😄 
- For the install guides I have used `<MudProviders/>` which for that senario is fine.  We need to think about configuration of the providers `<MudThemeProvider Theme="MyCustomTheme" />` for example.  If someone adds that in addition to the default providers what happens.  In `AddMudServices()` we use `TryAdd..` which only registers in the DI container once so that is covered.

Update Docs for MudServices

---

src/.editorconfig

- `default(DateTime)` is more readable that `default`

Turn off default expression refactor

---

src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsPlacementExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/KeepTabsAliveComponents/TabsKeepAliveTabTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsKeepAliveTest.razor
src/MudBlazor.UnitTests/Components/TabsTests.cs
src/MudBlazor/Components/Tabs/MudTabPanel.razor
src/MudBlazor/Components/Tabs/MudTabs.razor.cs

This is the first attempt on creating a new way to render tabs, avoind re-rendering issues on changing active tab.
The rendering of active tab is set on style (CSS) when **KeepPanelsAlive** parameter is set to true.
This work is based on #552 .

MudTabs: Render active tab by CSS (Keep Panels Alive mode)

---

src/MudBlazor/Base/MudBasePicker.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

As discussed in #572, here's the fix to manage call loops by using boolean flag in Set methods, as it was also implemented in BaseInput.

Manage call loops by update flags in Picker components

---

README.md
src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
src/MudBlazor.Docs/Pages/Getting Started/Installation/ManualMarkDown/MarkdownAddComponents.razor
src/MudBlazor.UnitTests.Viewer/Shared/MainLayout.razor
src/MudBlazor/Components/MudProviders.razor

- We should still think about the concept of `<MudProviders/>` but we need a better grasp of how the configuration will work.

Remove MudProviders

---

src/MudBlazor/Styles/components/_table.scss

The purpose of this PR is about to match the MudAutocomplete style with another input elements when it's inside a table cell.

MudAutoComplete style for Table Cell

---

src/MudBlazor/Components/Tabs/MudTabPanel.razor
src/MudBlazor/Styles/components/_table.scss

There's an error caused by me on #575 , setting diplay:default for active panel when the Parameter KeepPanelsAlive is set to true.
"default" is not a valid value for display property, and I didn't figure it before merge. 
I've changed it to display: contents and tested.
I'm so sorry for this.

Fix por PR #575 - MudTabs.KeepPanelsAlive

---

.azure/pipelines/jobs/default-test.yml

- This adds code covergage as a build artifact to the test stage of the pipeline
- With this change PRs and commits give code coverage statistics (currently 65%)
- You can also add a badge using shields.io.  The badge for this branch is
- ![Azure DevOps coverage (coverage)](https://img.shields.io/azure-devops/coverage/mikes0712/mikes/4/coverage.svg?style=flat-square)
- `![Azure DevOps coverage (coverage)](https://img.shields.io/azure-devops/coverage/mikes0712/mikes/4/coverage.svg?style=flat-square)`
- `https://img.shields.io/azure-devops/coverage/` is the type of badge
- `coverage.svg` is the branchname BTW. thats a bit confusing.  Anyway I can PR a badge with the right info

Publish coverage task

---

src/MudBlazor.Docs/Pages/Components/ToggleIconButton/Examples/ToggleIconButtonEventCallbackExample.razor
src/MudBlazor.Docs/Pages/Components/ToggleIconButton/ToggleIconButtonPage.razor
src/MudBlazor/Components/Button/MudToggleIconButton.razor
src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs

ToggledChanged event was not raised by parameter property setter, so the event was not correctly propagated.
See this example, where three components are bound to the same bool variable, but clicking on a component does not correctly update the others:
https://try.mudblazor.com/snippet/GFEFlKlr52S1wdUs24
I also enhanced the doc example to show that it is possible to force a specific state while inside the event handler.

Fix toggle icon button event propagation

---

src/MudBlazor.Docs/MudBlazor.Docs.csproj
src/MudBlazor.Docs/excubowebcompiler.json
src/MudBlazor/MudBlazor.csproj
src/MudBlazor/excubowebcompiler.json

- No MudBloazor.min.css was being output to wwwroot using the -o option
- This was working until recently it was switched to config file recently by request
- Turns out you cant mix and match command line and config file in excubo webcompiler
- So here we make sure output `Directory` is in the config file
- Please merge to net5 aswell ASAP

Fix build - excubo needs everthing in config

---

src/MudBlazor.Docs/MudBlazor.Docs.csproj
src/MudBlazor/MudBlazor.csproj

- Following on from #607.
- In this PR we add a check for css and js generation output in the wwwroot directory
- This will fail the build if output is missing
- Please be careful on the merge to net5 😉

Add build check for css and js output in wwwroot

---

src/MudBlazor/Components/CheckBox/MudCheckBox.razor
src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs

I noticed that the exact same svg element was repeated for each possible checkbox state. Now the svg element is defined only once and use a single method to define which icon to display.

Avoid element repeat in checkbox

---

src/MudBlazor.Docs/excubowebcompiler.json
src/MudBlazor/excubowebcompiler.json

- We revert to the default config file so we can see the settings
- We turn of vendor prefixing.  We should let the compiler take care of this really.
@Garderoben

Backto defaults disable vendor prefix

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs

- Recently I thought I saw DateChanged fired twice when doing some debugging.
- I wrote test to make sure it is always one after selecting a date.

Add test for DateChanged event count

---

src/MudBlazor.sln

-  Found pre-build step in .sln file added by @henon before my time
- We don't need this as we do it by MSBuild target dependencies now.

Remove docs compiler as a prebuild step in sln

---

src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj

- Easiest increase in code coverage ever
- There was a bug in coverlet introduced in 3.0.0 that wasn't counting some covered lines
- Coverage is now just over 80%

Fix coverage bug in coverlet 3.0.0 -> 3.0.1

---

src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
src/MudBlazor.Docs.Compiler/TestsForExamples.cs
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/DateRangePickerTests .cs
src/MudBlazor.UnitTests/Mocks/MockDomService.cs
src/MudBlazor/Base/MudBasePicker.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.cs
src/MudBlazor/Components/Picker/MudPicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
src/MudBlazor/Services/DomService.cs
src/MudBlazor/Services/ServiceCollectionExtensions.cs
src/MudBlazor/Styles/components/_picker.scss
src/MudBlazor/Styles/components/_pickerdate.scss
src/MudBlazor/TScripts/DOM.js

This PR addresses #578 Main changes:
- Reduce the number of renders on picker opening. This is currently one
- The date picker has a mouseover event on each day, which raises new render. This was eliminated by overriding the `ShouldRender `method.
- Datepicker days are replaced with simple html and I removed MudIconButtons. Basically I copied the rendered html, but this also improves performace.
- Range selection "animation" can be done with pure css with a small javascript. No additional renders are necessary.
- I make some changes in the timepicker razor code, because basically it looked like a lot of copy-paste. If you  don't like it, I can revert this change.
- (Also I adjusted the tests to the changes in the rendered DOM)

Picker performance improvements

---

src/MudBlazor.Docs/MudBlazor.Docs.csproj
src/MudBlazor/MudBlazor.csproj
src/MudBlazor/wwwroot/DoNotRemove.txt

- As described
- We recently stopped getting static assets css and js in the docs site F5 from clone.  We want that for a good clone F5 experience for new devs
- This restores that functionality by adding a placehoder file to keep the static assets directory alive.

Project changes for F5 from clone experience

---

src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs

Finally found that managing the Changed event inside the property setter is redondant according to Blazor lifecycle.
State propagation for multiple buttons bound to same variable is still working and is validated by a test I pushed sooner in a previous PR.

Avoid async call in ToggleIconButton property setter

---

src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Base/MudBooleanInput.cs
src/MudBlazor/Components/CheckBox/MudCheckBox.razor
src/MudBlazor/Components/Switch/MudSwitch.razor

Refactored to completely avoid async calls in property setters.
The idea is to bound the DOM element event to a separated handler instead of the property directly, as demonstrated in Microsoft documentation.
The automated tests were fixed to avoid manipulating the property directly. They are now calling the onchange event, which is more Blazor-compliant.
Also, I found that a converter change was setting the Touched state to true, which is incorrect. This is fixed by this PR (Now Touched state is set to true only by onchange handler)

Avoid async calls in BooleanInput property setters

---

src/MudBlazor.Docs/Pages/Getting Started/Wireframes/.gitignore

- All ExampleCode files now reside in Code dirs

Remove .gitignore no longer required

---

src/MudBlazor.UnitTests/Components/TreeViewTest.cs
src/MudBlazor.UnitTests/Mocks/MockDomService.cs
src/MudBlazor/Components/Collapse/MudCollapse.razor
src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
src/MudBlazor/Services/DomService.cs
src/MudBlazor/Styles/components/_collapse.scss
src/MudBlazor/TScripts/DOM.js

Fixes the height issue in MudCollapse when inner content's height become higher than 2000px. Important changes:
- switched from transition to animation
- removed max-height: 2000px

MudCollapse height fix

---

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor.UnitTests/Components/FormTests.cs
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Components/Input/MudDebouncedInput.cs
src/MudBlazor/Components/Input/MudInput.razor
src/MudBlazor/Components/Input/MudInput.razor.cs
src/MudBlazor/Components/Input/MudRangeInput.razor.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs
src/MudBlazor/Components/Table/MudTable.razor.cs
src/MudBlazor/Components/TextField/MudTextField.razor
src/MudBlazor/Extensions/ParameterViewExtensions.cs

Like #662, refactored to avoid async calls in some property setters.
Same technique: bound DOM element event to separate handler and fixed automated tests to avoid direct property access.

Avoid async calls in BaseInput property setters

---

src/MudBlazor.Docs.Compiler/ExamplesMarkup.cs
src/MudBlazor.Docs/Components/SectionSource.razor
src/MudBlazor.Docs/MudBlazor.Docs.csproj

- Cuts full build time typically by about 30%.  So for example on my machine I go from 40-43secs to 27-30secs.
- Adds Clean and Rebuild Support for the ExampleCode files.
- Also big speed gains on incremental builds.
- Tested on macOS windows vscode Visual Studio including spaces in paths.
- NOTE: when testing do a clean first if your are not a fresh clone.
- @tungi52 @henon  Would you be willing to test this in your environment?

Optimise build

---

src/MudBlazor.Docs/MudBlazor.Docs.csproj
src/MudBlazor/MudBlazor.csproj

- Remove awkward scripting and replace with native MSBuild tasks
- Didn't realise MSBuild had these native tasks.  This is much better for XPlat as it doesn't rely on the script host

Use native MSBuild tasks

---

src/MudBlazor.Docs/Styles/components/_docssection.scss

Code dialog are not visible entirely on smaller screens like 1366x768 (header and action bar are out of viewport).

Wireframe code dialog

---

src/MudBlazor.Docs/MudBlazor.Docs.csproj

- Because of the way rebuild works in VS (sequentially one project at a time) we cant delete the ExampleCode as part of the clean.
- As part of supporting VS rebuild ExampleCode was changed from include to update
- This doesn't work so we revert to include and flag rebuild to not clean the ExampleCode

Fix Example code not being included

---

src/MudBlazor/Components/Button/MudFab.razor

This preserves the old behavior before the MudIcon rework.

MudFab hides the icon if none is specified

---

src/MudBlazor.Docs/MudBlazor.Docs.csproj
src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj

- In certain circumstances when switching branches we need to clean generated files as they are outside git and wont switch with branch changes.
- This adds the 4 remaining generated files to the clean process to allow a full clean in that senario.

Add all generated files to the clean process

---

src/MudBlazor.UnitTests/Components/ButtonsTests.cs

A MudFab with no icon specified should not render an icon.

Added test to ensure MudFab with no icon specified does not render an icon.

---

.azure/pipelines/ci.yml

- Stages force sequencial processing
- Since build and test are not interdependent they shouldn't be forced to run in series
- This PR allows the jobs (on a public devops project) to run in parallel and hence halve the CI build time
- On my devops this PR took 2 mins 36 secs

Half the ci build time

---

src/MudBlazor/Styles/abstracts/_variables.scss
src/MudBlazor/Styles/layout/_main.scss

As turned out in #712 animation for main layout still breaks when both left and right drawers are open.

Fix mainlayout transition

---

src/MudBlazor/Styles/layout/_drawer.scss

I found that if you had content that overflowed, it had to overflow greater than the top drawer. 
I'm not sure of other implications so I'll leave it here, and if you think its good awesome!

Calculate the height to be 100% less the top drawer so the overflow works correctly

---

src/MudBlazor.Docs/MudBlazor.Docs.csproj
src/MudBlazor.Docs/excubowebcompiler.json
src/MudBlazor/MudBlazor.csproj
src/MudBlazor/excubowebcompiler.json

- Fixes #731 
- Remove the intermediate files from excubo builds as they were causing the final output to not be updated in certain circumstances.
- Add all the generated css and js to the clean process

Compiler fix intermediate css and js issues

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRowClassStyleTest.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTable.razor
src/MudBlazor/Components/Table/MudTable.razor.cs

Create extra parameters on the MudTable<T> to support item based classes and styles.
```html
<MudTable ItemRowClass="@(item => item.Value > 350 ? "high" : "")" 
ItemRowStyle="@(item => item.Value > 350 ? "background: blue" : "")"></MudTable>
```

Allow item based css styles and classes for Tables

---

src/MudBlazor.Docs/Models/ApiLink.cs
src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
src/MudBlazor.UnitTests/Components/TreeViewTest.cs
src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs

- Fix for #775 
- API page was not available
- Default item selection/activation does not propagated to TreeView - binding failed on first render for `ActivatedValue `and `SelectedValues`

Treeview circuit error

---

src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDatePickerExample.razor
src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsExample.razor
src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDrawerExample.razor
src/MudBlazor.Docs/Pages/Components/SwipeArea/SwipeAreaPage.razor
src/MudBlazor.Docs/Services/MenuService.cs
src/MudBlazor.Docs/Shared/MainLayout.razor
src/MudBlazor.Docs/Shared/MainLayout.razor.cs
src/MudBlazor.UnitTests/Mocks/MockDomService.cs
src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor
src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
src/MudBlazor/Enums/SwipeDirection.cs
src/MudBlazor/Interop/Touch.cs
src/MudBlazor/Interop/TouchEvent.cs
src/MudBlazor/Services/DomService.cs
src/MudBlazor/TScripts/DOM.js

In this PR I would like to share my idea how to add swipe support for MudBlazor. Basically I created a new component, called MudSwipeArea, which is simple a div with inner content. This component registers for `touchstart`, `touchend`, `touchcancel `JS events and listens for them. `touchmove `is not added, because it can generate an enormous amount of JS-Blazor calls. The main logic is on Blazor side, so I tried to avoid as much JS as possible.
On JS and Blazor side I had to add some serialization, because event arguments cannot be serialized to Blazor by default.
I also created some examples, for now just to show the main functionality.
Tests are not included, for now I have no idea how to do it.

Swipe support

---

.gitignore
src/MudBlazor.Docs.Compiler/CodeBuilder.cs
src/MudBlazor.Docs.Compiler/Paths.cs
src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
src/MudBlazor.Docs.Compiler/TestsForExamples.cs
src/MudBlazor.Docs/Models/Snippets.cs
src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj

- Because trying to do any changes to test setup requires painful strings
- Also clarifies test dependencies
- It will require a clean and build the first time this is installed

Move Example and Api tests to partial classes

---

src/MudBlazor/Styles/components/_tooltip.scss
src/MudBlazor/Styles/utilities/_scroll.scss

On smaller screen sizes there are some overlapping between `MudScrollToTop`, `MudTooltip ` and  `MudTab`. The following pictures are from the `MudTabs` component page:

MudScrollToTop and MudTooltip zindex

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableInlineEditTest.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Base/MudFormComponent.cs
src/MudBlazor/Components/Form/MudForm.razor.cs
src/MudBlazor/Components/Input/MudDebouncedInput.cs
src/MudBlazor/Components/Table/MudTableBase.cs
src/MudBlazor/Components/Table/MudTr.razor.cs
src/MudBlazor/Components/Table/TableRowValidator.cs

In #826 there is an interesting bug described. I made this PR draft, because the problem consist of several parts. First I noticed, that the `MudFormComponent `never removed itself from a form, therefore the `Remove `method of the `TableRowValidator `never called. So references stucked in the dictionary. The second problem, that `TableRowValidator ` uses strong references to `MudFormComponent`, so this prevents the components to be disposed. So the number of references are grows and grows now.
I make a fix, this works fine, the components GC-d now.
I have two questions which are considareble:
- This issue maybe affects `MudForm`. Should we fix it too?
- If there is a row validation error, I think we should prevent swiching row until the error fixed

Table commit bug

---

src/MudBlazor.Docs/Pages/Components/Tooltip/Examples/TooltipHtmlExample.razor
src/MudBlazor.Docs/Pages/Components/Tooltip/TooltipPage.razor
src/MudBlazor/Components/Tooltip/MudTooltip.razor
src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs

I had a use case where I needed to be able to pass custom HTML content to insert <br /> inside the tooltips. I added a way to pass custom HTML (or Blazor) content to the tooltip content via a RenderFragment.

Added option to pass custom HTML to a MudTooltip

---

src/MudBlazor.Docs/Models/ApiLink.cs

In `ApiLink.cs` file there is a `s_specialCaseComponents` dictionary, which contains api link names for generic components. The problem with this, if someone add new generic component, maybe forget extending the list here and navigation to API pages break. In this PR I made the current logic able to handle generic types too.

Construct api links from generic types automatically

---

src/MudBlazor/Styles/components/_progress.scss

I noticed that the background of the progress bar was not working for color other than primary and secondary. Also. the background would not change if you changed the default theme color. I wanted to fix that.
Before :
After :
I did it with a ::before pseudo element that I position absolutely. If you have a better idea to apply the transparency, I would change it gladly.

Fixed background color of linear progress bars

---

src/MudBlazor.Docs/Shared/MainLayout.razor.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Components/Chart/MudChart.razor.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
src/MudBlazor/Components/Input/MudDebouncedInput.cs
src/MudBlazor/Components/Input/MudInput.razor
src/MudBlazor/Components/Input/MudRangeInput.razor
src/MudBlazor/Components/Table/MudTable.razor.cs
src/MudBlazor/Components/TextField/MudTextField.razor

Committed refactoring on the protected events `onKeyDown`, `onKeyPress`, and `onKeyUp` inside `MudBaseInput` to follow standard nomenclature.
It also includes minor refactoring, like using `Array.Empty<T>()` instead of initializing new empty array (https://docs.microsoft.com/it-it/dotnet/fundamentals/code-analysis/quality-rules/ca1825).
This change was discussed here: https://docs.microsoft.com/it-it/dotnet/fundamentals/code-analysis/quality-rules/ca1825

Refactoring naming scheme MudBaseInput.onKey[X] to follow .NET standard

---

src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
src/MudBlazor.UnitTests/Components/MenuTests.cs
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor.UnitTests/Components/TabsTests.cs
src/MudBlazor.UnitTests/Components/TimePickerTests.cs

- The compiler is asking me to use indexer rather than enumerable methods on the testing collections.
- In fact this is how bUnit show it in their examples
- We already mix the 2 for example some use `[0]` and some use `.First()`
- It actually looks better for the intermediate stuff ie `[30]` is easier to read than `.Skip(30).First()`
- The only bit that is less readable is `.Last()` which ends up `[^1]` but its seems odd to leave `.Last()`on its own

Prefer index over enumerable methods

---

src/MudBlazor/Components/Tabs/MudTabPanel.razor
src/MudBlazor/Components/Tabs/MudTabs.razor.cs

- We need to take a harder approach to prevent exceptions in the absence of a proper cleanup event from MS

Fix #999 ignore all errors in dispose

---

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableBasicExample.razor
src/MudBlazor/Components/Table/MudTableBase.cs
src/MudBlazor/Components/Table/MudTd.razor.cs
src/MudBlazor/Styles/components/_table.scss

Possible solution for #916 
Cell text can be aligned left and right. Also added a posiibility to hide a single row on small screens.
Perhaps naming could be better so I'm open to any suggestion.

Text align for table cells on mobile

---

src/MudBlazor.Docs.Client/wwwroot/index.html
src/MudBlazor.Docs.Server/Pages/_Host.cshtml
src/MudBlazor/TScripts/mudElementReference.js

- Because Dispose completes before OnAfterRenderAsync is complete elementRef can be null.
- We need to check for null at the JS level as ElementRef is a struct in c# and cannot be null.
- I am pushing this fix through as at the moment there are a lots of navigation errors in the server logs which is not good UX
- We need to discuss this further
- There are still some other exceptions to discuss This fix will at least reduce the logs dramatically so we can see the others
Good reference found by @tungi52 
https://www.thinktecture.com/en/blazor/blazor-components-lifecycle-is-not-always-straightforward/

Stop exceptions on page leave for tabs

---

src/MudBlazor.UnitTests/Components/SnackbarTests.cs
src/MudBlazor/Components/Snackbar/Snackbar.cs

It's possible for the Timer to get disposed, then the StopTimer function to be called. This causes the exception.  The safe way to do this to null out the Timer to ensure StopTimer does nothing in this case.
This fixes issue #1059

Fix ObjectDisposedException race condition in Snackbar

---

src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTableBase.cs

This is a fix for Issue #1034.  I thought about it and the safest thing to do is to return to the first page after changing the page size. Any other option could lead you to jump to random locations.  For example, if you were on page 2 with a size of 10 (11-20).  Then changed to 5, you would just jump to "6-10", which is just strange.  Instead, it seems best to just go to the first page again.

Fix the issue with server side paging after changing page size

---

src/MudBlazor.Docs/Shared/NavMenu.razor.cs
src/MudBlazor/Components/Collapse/MudCollapse.razor.cs

For #1078 
@mikes-gh I'm pretty sure this is just a part of the problem. With this the navgroup in drawer won't collapse after refresh.

Fix mudcollapse default open state

---

src/MudBlazor.UnitTests/Mocks/MockDocsMessageHandler.cs

- At first I couldn't work out what was happening here.
- It turn out the response from the MockHttpHandler was incorrect.  I did a direct test and got failure 100%
- This error only leaked into the tests very occasionally because the call is actually async within the test so not in the test thread context.
- This fixes the HttpReponse so there in no longer an error in the async call and no possibility of exceptions from this other thread context leaking into the test thread

Fix mediatype for DialogExample

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs

We noticed an issue where the order you declare your attributes affected the rendering:
Example: https://try.mudblazor.com/snippet/GkmvaHuTsbmTXvaZ
Notice the second set of pickers, the last one does not update when the format is changed.
This PR is to update that to allow a hook for descendants to allow them to adjust their text as needed. 
I also fixed a typo.

Add date format changed hook for descendants

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
src/MudBlazor/Components/DatePicker/DateRange.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs

Fix MudDateRangePicker initial render

---

src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerBasicUsageExample.razor
src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DateRangePickerUsageExample.razor
src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerBasicUsageExample.razor
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/TimePickerTests.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
src/MudBlazor/Components/Picker/MudPicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
src/MudBlazor/MudBlazor.csproj
src/MudBlazor/Styles/components/_picker.scss
src/MudBlazor/Styles/components/_pickerdate.scss

#724 
I implemented the requested feature in a more general way: I used MudDialog as a reference and make it possible to add action buttons to all type pickers. So this change affects not only timepicker, but the date/daterange pickers too.

Add action buttons to pickers

---

src/MudBlazor.Docs/Pages/Features/Flex/FlexPage.razor

Fixed Typo in FlexPage.razor. ("have calsses") -> ("has classes").

Fixed Typo in FlexPage.razor

---

src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
src/MudBlazor/Services/Scroll/ScrollListener.cs

- A couple of places we didn't dispose of DotNetObjectReference
- Renamed another for consistency
- Reference https://blazor-university.com/javascript-interop/calling-dotnet-from-javascript/lifetimes-and-memory-leaks/
- @tungi52 @TyrenDe Can you review please

Fix dispose DotNetObjectReference

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteValidationDataAttrTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectValidationDataAttrTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/TextFieldValidationDataAttrTest.razor
src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Base/MudFormComponent.cs

I've encountered issues with validation using data attributes on my models with EditForms.
This PR allows form controls to retrieve the list of [DataValidation attributes](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0#validation-attributes) from the property targeted by simple `For` expressions, and run them during validation.
Since this is added at the `MudBaseInput` level, tests include verifications that some inputs (`MudSelect`, `MudTextField` and `MudAutocomplete`) are behaving correctly.
Those validations were previously made at the `EditForm` level (I guess), but not at the MudBlazor inputs level.
Feel free to feedback. 🥂

feat: add support of data validation attributes on properties targeted by `For`

---

src/MudBlazor/TScripts/mudElementReference.js

- Quieten down the event log.  Skipping the function is elementRef null seems a safe thing to do.

Don't raise exception if elementRef null

---

src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor/Base/MudFormComponent.cs

I've spotted the regression introduced in #1198 and fixed by 93773b8a15662dd3758313d0ebeb768d1eb7ce0c, and worked on it on my side. My PR actually did not retrieved correctly error messages from custom attributes.
This new PR fixes retrieval of error in custom attributes that returns the error message from the `ValidationResult` instead of a property hosted on the attribute itself. Moreover, it enables support of `For` & DataValidation even out of an `EditContext`.
Test included.

feat: use data attributes even if no edit form, retrieve error messages

---

src/MudBlazor.Docs/Pages/Components/Link/Examples/LinkSimpleExample.razor
src/MudBlazor.UnitTests/Components/LinkTests.cs
src/MudBlazor/Components/Link/MudLink.razor
src/MudBlazor/Components/Link/MudLink.razor.cs
src/MudBlazor/Styles/components/_link.scss

#1185 
I added a simple test too, however I don't know how to check for navigation events in bUnit. So instead I test that "href" attribute presents or not.

Add disabled property for MudLink

---

src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldSelectRangeExample.razor
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Input/MudInput.razor
src/MudBlazor/Components/TextField/MudTextField.razor

Added 3 new properteis on MudInput, associated with keyboard events:
- KeyDownPreventDefault
- KeyPressPreventDefault
- KeyUpPreventDefault
These 3 events are wired on the respective event `@onkeydown:preventDefault` on the input tag.
If true, the browser won't propagate the event on the underlying tag, for example in this case:
https://try.mudblazor.com/snippet/GEmPEdvHuYdBHBPy
If the user press the arrow up key, it won't be propagated (line 23) and thus the value won't be incremented. If the user types a number or the arrow down key, it will work as usual.
Note: #1000 requires this to implement the final piece.

Add KeyXPreventDefault on MudInput

---

src/MudBlazor/Styles/abstracts/_colors.scss

Color utility classes should have `!important` to have more specificity
This fixes #1272

Added !important to colors utility classes

---

src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithTableExample.razor
src/MudBlazor.UnitTests/Components/HighlighterTests.cs
src/MudBlazor/Components/Highlighter/Splitter.cs

- Fix `MudHighlighter` when the `Text` property is not passed or is null
- Added test to prove it
- Fixed example

Fix highlighter nulls

---

src/MudBlazor/Components/Overlay/MudOverlay.razor.cs

If several overlays are in the screen but with contradictory LockScroll values, it depended in the order they were created to work properly.
Bug fixed

Fix Overlay scroll lock when is more than one in screen

---

src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuTwoWayBindableExample.razor
src/MudBlazor.Docs/Pages/Components/NavMenu/NavMenuPage.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavMenuOneWay.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavMenuTwoWay.razor
src/MudBlazor.UnitTests/Components/NavMenuTests.cs
src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs

This addresses #1322
MudNavGroup property `Expanded` should be two-way bondable, so you can choose what happens when the nav group collapses or expands.

Added two way binding to MudNavGroup `Expanded` property

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectWithInitialValues.razor
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs

The initial selected values didn't get converted in the input initially, because when the Select called the Converter, in the Text setter, the Converter was still the DefaultConverter, not the user Converter.
This fixes it

Fix initial selected values that didn't show converted

---

src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectInteractiveExample.razor

SelectInteractiveExample.OnPostitionChange will become SelectInteractiveExample.OnPositionChange

Fix minor typo for method name in SelectInteractiveExample

---

src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesMultipleExample.razor
src/MudBlazor.Docs/Shared/MainLayout.razor.cs

I played around with the line colors in the darktheme. In my opinion it looks much better now. What do you think?
Left=new, right=old:
Tables:
Text-fields:
Divider:
Closes #1264, #1265

Darktheme color adjustments

---

src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectInteractiveExample.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/InputControl/MudInputControl.razor
src/MudBlazor/Styles/components/_inputcontrol.scss
src/MudBlazor/Styles/components/_inputlabel.scss

> Note: new InputControl container `.mud-input-control-input-container` enables relative positioning so that absolute positioning of popover works as expected.
> Closes #472
This PR is highly experimental, and I don't know how to check if it causes UI regression (though it doesn't in my end-usage project). I would be grateful if you could check it out.
Since this is UI only, I could have written E2E tests but there are no boilerplate for it, and it does not modify any logic really testable through Unit Tests
Cheers.  🥂

fix: avoid autocomplete popover to be too low

---

src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectInteractiveExample.razor
src/MudBlazor/Enums/Typo.cs

It is not possible to switch typo to default of document, and default != body1
Using for example a mudlink next to normal html text leads to different fontsizes.

Added default to Enum Typo

---

src/MudBlazor/Components/List/MudListItem.razor.cs

Fixed issue #1400
Now `MudListItem.Disabled` check if the parent `MudList.Disabled` to determine its disabled state.

Fix MudList.Disabled not working

---

src/MudBlazor.Docs/Components/DocsIconPanel.razor
src/MudBlazor.Docs/Pages/Components/Icons/Examples/IconsUsageExample.razor
src/MudBlazor.Docs/Pages/Components/Icons/IconsPage.razor
src/MudBlazor.Docs/Styles/components/_icons.scss
src/MudBlazor/Components/Icon/MudIcon.razor
src/MudBlazor/Components/Icon/MudIcon.razor.cs

Add title property to MudIcon for accessibility options.
It also fixed issue #1190, slightly reworking the page from always having 5 columns to using a flexbox with fixed width for every icon.
Every icon now also show the name in the tooltip, for when it's too long and gets truncated.

Add Title to MudIcon and fix issue #1190

---

src/MudBlazor/Components/DatePicker/MudDatePicker.cs

This is a possible fix for #1268 
I don't know changing this converter property directly is a good solution, or should I add `Clear` methods? Anyway, the problem here is that the `GetError` in the converter remains true, and this cause the validation error message in the issue.

Fix validation error for MudDatePicker

---

src/MudBlazor.UnitTests/Components/DrawerTest.cs
src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
src/MudBlazor/TScripts/mudResizeListener.js

Possible fix to #1371 and #1376
The problem here is that breakpoint change event fires two times, once after reaching md size then again when reaching sm. Delaying the event on JS side could solve this problem.

Throttle breakpoint change event

---

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableHeaderAndFooterExample.razor
src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiSelectExample.razor
src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest2B.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest6.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest6B.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRowClickTest.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTFootRow.razor
src/MudBlazor/Components/Table/MudTFootRow.razor.cs
src/MudBlazor/Components/Table/MudTHeadRow.razor
src/MudBlazor/Components/Table/MudTHeadRow.razor.cs
src/MudBlazor/Components/Table/MudTable.razor
src/MudBlazor/Components/Table/MudTable.razor.cs
src/MudBlazor/Components/Table/MudTableBase.cs
src/MudBlazor/Components/Table/MudTr.razor
src/MudBlazor/Components/Table/MudTr.razor.cs
src/MudBlazor/Components/Table/TableContext.cs
src/MudBlazor/Styles/components/_table.scss

This PR implements the proposal inside issue #1058 and it's proposed as an alternative to PR #1239 and Issue #1232 .
It provides functionality for a multi row header and footer, without requiring a new fragment and being 100% compatible with existing code.
**Existing implementation**
`MudTable.HeaderContent` requires the user to insert a list of MudTh, it automatically renders the content inside a `MudTr` component, and automatically implement a "check-all" feature in case of multi select, with an additional column on the left, and an empty column on the right in case of editable table (RowEditingTemplate != null).
**New implementation**
Created a new component `MudTHeadRow` that automatically provides all the functionality before implemented "manually" inside `MudTable` when it render a …

Add customizable Table header and footer

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/SimplifiedScrollableTabsTest.razor
src/MudBlazor.UnitTests/Components/TabsTests.cs
src/MudBlazor.UnitTests/Mocks/MockResizeObserver.cs

The test that the scroll buttons are visible or enabled when tabs are added or removed is already part of the test ```Handle_Add``` and  ```Handle_Remove_BeforeSelection``` and ```Handle_Remove_AfterSelection```. However, this test covers the case in a lighter and easier-to-understand way. 
This is proof that the "new" version of the tabs (#1321) solve issue #1389

Added test to proof #1389 is fixed

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/ActivateDisabledTabsTest.razor
src/MudBlazor.UnitTests/Components/TabsTests.cs
src/MudBlazor/Components/Tabs/MudTabs.razor.cs

Based on the discussion in #1429, I've changed the signature of the existing method**s**, to select a tab, to enable the developer to active a disabled tab.
**Before:** 
```C#
public void ActivatePanel(int index)
```
**Now:**
```C#
public void ActivatePanel(int index, bool ignoreDisabledState = false)
```
There is **no breaking change** because the new parameter is initialized with a default value, which doesn't change the existing behavior. 
The "main activation" method is changed just a bit 
```C#
if (!panel.Disabled || ignoreDisabledState)
{
....
}
```
Besides, there are two new unit tests around the activation of tabs.

adding tab activation for disabled tabs

---

src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetLateDefaultTest.razor
src/MudBlazor.UnitTests/Components/ChipSetTests.cs
src/MudBlazor/Components/Chip/MudChip.razor.cs
src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs

A fix for issue #1369 with a simple addition of a per-chip "seen" property. Leaves the existing single selection operation as it was.

Later added chips should be initially selected if they are default

---

src/MudBlazor/Styles/components/_table.scss

Applied z-index:2 to _table.scss as suggested by porkopek.

#1469 Fix for MudTable MultiSelection check-all bug

---

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

Rather self explanatory.
Solution was given in https://github.com/Garderoben/MudBlazor/issues/1415#issuecomment-824960469
Tests included.
Fixes #1415

fix(autocomplete): call the `OnBlur` method when input blurred

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipInlineTest.razor
src/MudBlazor/Components/Tooltip/MudTooltip.razor
src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
src/MudBlazor/Styles/components/_tooltip.scss

This fixes issue #1167, for which a tooltip surrounds it's content with an inline-block div by default.
Added a new property called **Inline**, which defaults to true for compatibility. Setting it to false doesn't change the display attribute of the div to inline, but keeps it a block.
This has been achieved moving the following CSS rule `display:  inline-block` into a new class, added to the container only if `Inline == true`.
Although I'm not a fan of negative logic, this is the more elegant way I found to not break compatibility (and possibly the most common scenario).
Other options I evaluated a parameter name have been:
- Block (not self-explanatory)
- DisplayBlock
- ContainerBlock
- ContainerDisplay (and setting up an enumerator that could have even more values)
I also avoided to be …

Fix MudToolTip is not flex compatible, #1167

---

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

Forward IconSize from `<MudAutocomplete>` to wrapped `<MudInput>`, just like `<MudSelect>`.

Forward IconSize from <MudAutocomplete> to wrapped <MudInput>

---

src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DateRangePickerUsageExample.razor
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs

Fixes #1530
Default format for TitleDate is now consistent with MudDatePicker (`ddd, dd MMM`) and TitleDateFormat description.

MudDateRangePicker - accepts TitleDateFormat

---

src/MudBlazor.Docs/Pages/Components/NumericField/Examples/DebouncedNumericFieldExample.razor
src/MudBlazor/Components/NumericField/MudNumericField.razor
src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
src/MudBlazor/Utilities/RuntimeLocation.cs

Fix issue #1543, onkeydown:preventDefault on the input tag wasn't set to true when pressing up/down arrows, causing double increment: the code and the browser.
This PR is draft because I noticed that there are some quirks on the restore of "preventDefault" on other inputs.

NumericField: restore preventDefault to true on up/down arrows

---

src/MudBlazor/Styles/components/_inputcontrol.scss

Fix for #1550
Add new CSS rule that adds a padding equal to the spinner buttons width (24px) to prevent overlap with them.
It mainly shows for right aligned text, but also for long numbers.

NumericInput: add right padding when overlapping with spinner buttons

---

src/MudBlazor/Styles/components/_tabs.scss

Wrong z-index in MudTabs

---

src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
src/MudBlazor/Components/NumericField/MudNumericField.razor.cs

Exception was thrown from constructor when `T` was not `int`. It happened because several numeric literals that were set to `_stepDefault` were recognized by compiler as `int`.

Fixed InvalidCastException in MudNumericField<T>

---

src/MudBlazor/Styles/components/_alert.scss

Fixes `Alert spacing of icon` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-724748845

Fixes alert spacing in RTL

---

src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample3.razor
src/MudBlazor.UnitTests/Components/ChartTests.cs
src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
src/MudBlazor/Components/Chart/Charts/Line.razor.cs
src/MudBlazor/Components/Chart/Models/ChartOptions.cs
src/MudBlazor/Components/Chart/MudChart.razor.cs

Just adds StringFormat for Y axis on Chart Options (null by default).

String format for Chart's Y axis.

---

src/MudBlazor/Styles/components/_button.scss

Fixes `Button icon position and spacing` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-724748845
Before:
After:

Fixes button spacing in RTL

---

src/MudBlazor/Styles/components/_chip.scss

Fixes `Chip icon position and spacing` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-724748845
Before:
After:

Fixes chip spacing in RTL

---

src/MudBlazor/Styles/components/_card.scss

Fixes `Card avatar spacing` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-724748845
Before:
After:

Fixes card avatar spacing in RTL

---

src/MudBlazor/Styles/components/_fab.scss

Fixes `FAB icon position` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-724748845
Before:
After:

Fixes fab button spacing in RTL

---

src/MudBlazor/Styles/components/_treeview.scss

Fixes #1596
~I changed the margin in `mud-treeview-group` from 17px to 16px because I used the class `mr-4`. Or should I add a custom css class to fix the issue?~

MudTreeView RTL support fixed

---

src/MudBlazor/Components/Menu/MudMenu.razor

The `MudOverlay` should be contained inside the `MudMenu`. Otherwise this could break css styles from components which share the same parent as `MudMenu`. For example this became a problem when I used the `:last-child` selector in the parent component in  #1484. Hard to explain but I hope you get what I mean.

MudOverlay moved inside MudMenu component

---

src/MudBlazor.Docs/Pages/Components/ButtonGroup/ButtonGroupPage.razor
src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupBasicExample.razor
src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupCustomStylesExample.razor
src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupDisableElevationExample.razor
src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupIconButtonExample.razor
src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupSizesColorsExample.razor
src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupSplitButtonExample.razor
src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupVerticalExample.razor
src/MudBlazor.Docs/Services/MenuService.cs
src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor
src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs
src/MudBlazor/Styles/MudBlazor.scss
src/MudBlazor/Styles/components/_buttongroup.scss

A new button group component that groups related buttons together. As described in #1249
Tell me what you think :)
Edit:
closes #1249

New button group component added

---

src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTablePager.razor
src/MudBlazor/Components/Table/MudTablePager.razor.cs

Back/forward navigation buttons in MudTablePager should be disabled on first/last table page

MudTablePager: Disable back/forward buttons on first/last page

---

src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

The default icon of a time picker should not be a calender icon but rather a clock icon.
[Material-ui](https://next.material-ui.com/components/time-picker/) for example also uses a different icon for time pickers.
As mentioned in #1640

TimePicker default icon changed

---

src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteUsageExample.razor
src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

If user input is not found by the search func and `CoerceValue` is set to true, the user input
will be applied to the `Value` which allows to validate it and display an error message.
Fixes #1448

Autocomplete: added CoerceValue parameter

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsAddingRemovingTabsTest.razor
src/MudBlazor.UnitTests/Components/TabsTests.cs
src/MudBlazor/Components/Tabs/MudTabs.razor.cs

To make it possible that developers can access the tabs, without opening an easy way to manipulate the collection, I've added a ```ReadOnlyList<MudTabPabel>``` to the ```MudTab``` class and linked it to the private list of tabs.
It was mentioned in #1473 and #1467

(re)Adding a public accessable property for tabpanels

---

src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteValidationExample.razor

Validation example in the official documentation for the [MudAutocomplete - Validation](https://github.com/Garderoben/MudBlazor/issues/1448).
PS : The _AutocompletePage.razor_ file is an update from the same file in the _Autocomplete: added CoerceValue parameter_ PR.

Validation example for MudAutocomplete

---

src/MudBlazor/Components/Table/MudTableBase.cs

Maybe the smallest pull request ever, but there was a missing `$` in the elevation css builder for MudTable.

Fixed string interpolation for elevation css

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Charts/LineChartWithBigValuesTest.razor
src/MudBlazor.UnitTests/Components/ChartTests.cs
src/MudBlazor/Components/Chart/Charts/Line.razor.cs
src/MudBlazor/Components/Chart/Models/ChartOptions.cs

Fixes #1591
The problem is this: you put in numbers in a line chart that are in the millions or even billions. In chart options you have YAxisTicks which defaults to 20 meaning a tick every 20 units, leading to millions of horizontal lines resulting in extreme memory consumption and render times in the minutes. 
I added a `MaxNumYAxisTicks` to chart options (defaulting to 20) and when the number of ticks is above that the tick spacing gets doubled until the resulting number of ticks is <= MaxNumYAxisTicks.
This is how the sample provided by the OP looks like now after the fix:

LineChart: Added MaxNumYAxisTicks to limit the Nr of horizontal grid lines

---

src/MudBlazor/Styles/utilities/_spacing.scss

I've noticed there are missing spacing values for both '15' and 'n15'. Incidentally found this bug while trying to use these sizes for paddings.

Missing spacing value

---

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor
src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableInlineEditCancelTest.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTableBase.cs
src/MudBlazor/Components/Table/MudTr.razor
src/MudBlazor/Components/Table/MudTr.razor.cs

Addition of a cancel button when the row is edited in a MudTable.
It is also possible to set the icon for the Cancel Edit button and for the Commit Edit button.
This should help for the [Table: Location of Cancel button in inline editing](https://github.com/Garderoben/MudBlazor/issues/679) issue.

Cancel button addition in inline editing for MudTable

---

src/MudBlazor/Components/Table/MudTableSortLabel.razor.cs

When clicking a column to sort data any exceptions raised inside async ServerData not being propagated since nothing is awaiting the callback in this case.
Changed the way how property is updated after a click to use async task.

Fix exceptions not being propagated when calling SortDirection property setter

---

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

Fix for #1683
Comparison between normal and dense:

fix autocomplete dense class

---

src/MudBlazor.Docs/Pages/Components/ToggleIconButton/Examples/ToggleIconButtonEventCallbackExample.razor
src/MudBlazor.Docs/Pages/Components/ToggleIconButton/Examples/ToggleIconButtonTwoWayBindingExample.razor
src/MudBlazor.UnitTests/Components/ButtonsTests.cs
src/MudBlazor.UnitTests/Components/IconTests.cs
src/MudBlazor.UnitTests/Components/ToggleIconButtonTest.cs
src/MudBlazor/Components/Button/MudIconButton.razor
src/MudBlazor/Components/Button/MudIconButton.razor.cs
src/MudBlazor/Components/Button/MudToggleIconButton.razor
src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs

The icon supports a "Title" parameter, used mainly for accessibility for screen reader and show a popup.
The icon buttons should implement that.
MudToggleIconButton allow to change the title based on its toggled state, the value is optional (it keeps the same if not specified)

MudIconButton and MudToggleIconButton: Add the icon title

---

src/MudBlazor.UnitTests/Mocks/MockResizeObserver.cs
src/MudBlazor/Components/Tabs/MudTabPanel.razor
src/MudBlazor/Components/Tabs/MudTabs.razor.cs
src/MudBlazor/Services/ReseizeObserver/IResizeObserver.cs
src/MudBlazor/Services/ReseizeObserver/ResizeObserver.cs
src/MudBlazor/TScripts/mudResizeObserver.js

Based on discussion #1455, I tried to reproduce the error but couldn't do so. 
Instead, I clarified a bit about the disposal methods. In addition, the javascript calls for canceling a subscription, and the unobserving of an element is now surrounding by a try-catch-block.
```C#
try { await _jsRuntime.InvokeVoidAsync($"mudResizeObserver.disconnect", _id, elementId); } catch (Exception) { }
and
try { _ = _jsRuntime.InvokeVoidAsync($"mudResizeObserver.cancelListener", _id); } catch (Exception) { }
``` 
I'm not satisfied with this solution. It'd be great to get to the gist of the matter, understanding the root cause. However, as the error likely didn't cause any harm for users, this solution seems like an appropriate balance between time invested and relevance.

a fix? for #1455

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Select/ReselectValueTest.razor
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs

MudSelect: Do not fire changed event when the same item is selected again.

---

src/MudBlazor/Styles/components/_alert.scss
src/MudBlazor/Styles/components/_badge.scss
src/MudBlazor/Styles/components/_breadcrumbs.scss
src/MudBlazor/Styles/components/_button.scss
src/MudBlazor/Styles/components/_card.scss
src/MudBlazor/Styles/components/_chip.scss
src/MudBlazor/Styles/components/_dialog.scss
src/MudBlazor/Styles/components/_divider.scss
src/MudBlazor/Styles/components/_fab.scss
src/MudBlazor/Styles/components/_iconbutton.scss
src/MudBlazor/Styles/components/_input.scss
src/MudBlazor/Styles/components/_inputcontrol.scss
src/MudBlazor/Styles/components/_list.scss
src/MudBlazor/Styles/components/_navmenu.scss
src/MudBlazor/Styles/components/_picker.scss
src/MudBlazor/Styles/components/_pickerdate.scss
src/MudBlazor/Styles/components/_pickertime.scss
src/MudBlazor/Styles/components/_radio.scss
src/MudBlazor/Styles/components/_simpletable.scss
src/MudBlazor/Styles/components/_snackbar.scss
src/MudBlazor/Styles/components/_switch.scss
src/MudBlazor/Styles/components/_table.scss
src/MudBlazor/Styles/components/_tabs.scss
src/MudBlazor/Styles/components/_treeview.scss

I changed:
`padding-left` to `padding-inline-start`
`padding-right` to `padding-inline-end`
`margin-left` to `margin-inline-start`
`margin-right` to `margin-inline-end`
`text-align: left` to `text-align: start`
`text-align: right` to `text-align: end`
where it was necessary.
That way we can easily fix all padding, margin and alignment problems without writing custom css for rtl.
These properties are supported by all browser which are supported by blazor.
https://caniuse.com/?search=padding-inline-start
https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-5.0

Fixes RTL margin, padding and alignment issues

---

src/MudBlazor/Components/Table/TableContext.cs

A separate PR for a small fix of #1702

Table: Fix initial sort label not being set for table when using InitialDirection for MudTableSortLabel

---

src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
src/MudBlazor/Components/MessageBox/MudMessageBox.razor

Fixes #1739
Changes the order of MudMessageBox action buttons from: `Yes -> No -> Cancel` to `Cancel -> No -> Yes`

Fixes #1739 - MudMessageBox action buttons order reversed

---

src/MudBlazor/Components/Input/MudInput.razor

The right padding on clear buttons is too little for filled and outlined inputs.
I added a method that returns the class string based on the variant being rendered.

Fix right margin on MudInput clear button

---

src/MudBlazor/Components/Breadcrumbs/BreadcrumbSeparator.razor

Fixes Breadcrumb seperator in RTL

---

src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/NumericFieldTest.razor
src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
src/MudBlazor.UnitTests/Utilities/BindingConverterTests.cs
src/MudBlazor/Components/NumericField/MudNumericField.razor
src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
src/MudBlazor/Components/NumericField/NumericBoundariesConverter.cs
src/MudBlazor/Utilities/BindingConverters/NumericBoundariesConverter.cs

This PR fixes an issue with NumericField, an out of bound value doesn't change on the interface when manually typed in, but it's bound value is costrained.
**How to reproduce**
https://try.mudblazor.com/snippet/wYQlOKOlWPefTgtG
This fiddler replicates the "Normal vs Immediate vs Debounced" example in the docs, but with `Min=0 Max=10` parameters.
It's easier seen on immediate, but it happens on debounced and normal (in some cases).
If you type a valid number (IE: 4) you can see change immediately both on the textbox and in the control below. If you make it invalid (IE: 40) the control value changes to 10 (maximum valid value) but the text is still 40.
**Why it happens**
NumericField declared a `DefaultConverter<string>` (forcing `InvariantCulture` to work with HTML standard specifications) …

NumericInput: fix manual input boundaries check

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest3.razor
src/MudBlazor/Components/Table/MudTableBase.cs
src/MudBlazor/Components/Table/MudTableSortLabel.razor.cs

Added a property "AllowUnsorted" to MudTable to control sorted state.
When "AllowUnsorted" is set to true (default) the behavior is same as it is now - column sort states change in order "Ascending", "Descending", "None".
But when "AllowUnsorted" is false, then when a column is clicked for sorting, the states loop between "Ascending" and "Descending" so there is always at least one sorted column used.

MudTable: Added ability to control column sorting directions ("Ascending", "Descending", "None")

---

src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayAbsoluteExample.razor
src/MudBlazor.Docs/Pages/Components/Overlay/OverlayPage.razor

Fixes #1670
For the SubTitle, I used the [first line](https://material.io/develop/ios/supporting/overlay-window).

Overlay: improved documentation

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
src/MudBlazor.UnitTests/Components/FormTests.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs

Since MudBaseDatePicker uses a CurrentCulture as a default culture perhaps it would be logical to use a default date format from the same culture.

DatePicker: Added a default date format for a DatePicker based on CurrentCulture

---

src/MudBlazor/Components/Chart/Charts/Bar.razor
src/MudBlazor/Components/Chart/Charts/Line.razor

I read online that line and bar charts should remain ltr because they display the flow of time.
`There doesn't appear to be a global consensus on charts. Line charts are almost always left-to-right.`
https://mapmeld.com/rtl-guide/
Although there are occurrences of rtl line charts. I think keeping them ltr would be the best option.

Line and Bar charts: fixes for RTL

---

src/MudBlazor/Styles/components/_inputcontrol.scss
src/MudBlazor/Styles/components/_inputlabel.scss

Fixes in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-724748845:
`Autocomplete text and position of arrow`
`Select text and arrow position` + `Select items in dropdown`
`Textfield helper text and label text`
When the `InputTpye` of `MudTextFields` is set to `InputType.Email` or `InputType.Telephone` the orientation of the textfield automatically changes to ltr. As described here: https://rtlstyling.com/posts/rtl-styling/#form-inputs

Autocomplete, Select and Textfield: Fixes for RTL

---

src/MudBlazor/Components/Card/MudCardMedia.razor.cs

If you have a razor page with a MudCardMedia and you exchange the image or the height, the component will not refresh correct.
The reason for that is, that the component is calculating the values within "OnInitialized" which is not getting invoked on any parameter change.
Best solution in this case is to avoid a "state" and not to store the values into a dedicated field.
This PR will inline the parameters of MudCardMedia into the StyleString property directly.

MudCardMedia: adapt to changing image

---

src/MudBlazor/Components/TimePicker/MudTimePicker.razor

Fixes `Time Picker AM / PM buttons` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-724748845

Timepicker: fixed in RTL

---

src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs

Fixes `Progress direction` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-724748845

MudProgressLinear : Flipped in RTL

---

src/MudBlazor.Docs/Pages/Features/RTLLanguages/Examples/RTLLanguagesTextfieldExample.razor
src/MudBlazor.Docs/Pages/Features/RTLLanguages/RTLLanguagesPage.razor
src/MudBlazor/Components/Input/MudInputCssHelper.cs
src/MudBlazor/Styles/components/_inputcontrol.scss

Implements feature request: https://github.com/Garderoben/MudBlazor/pull/1789#issuecomment-856985091
Fixes textfield adornment bug in RTL

RTL: Adds textfield docs example, fixes adornment issue

---

src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerBasicUsageExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/AutoCompleteDatePickerTest.razor
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs

Implementation of the [On the Date Picker have a today button to select today](https://github.com/Garderoben/MudBlazor/issues/1243) issue.
The ```RequiredAction``` parameter has been added to _MudDatePicker_.
If ```RequiredAction``` is set to ```false``` and _PickerActions_ are defined, selecting the day will close the _MudDatePicker_.

MudDatePicker: added AutoClose to close on date selection

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest4.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/TableContext.cs

MudTable: when used with server-sorted data, reload on sort label click in mobile view

---

src/MudBlazor.sln
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs

This PR is an attempt to enable the `MudSelect` and `MudAutocomplete` components
to behave more alike by forwarding the `OffsetX`, `OffsetY` and `Direction` attributes for `MudAutocomplete`.
`MudSelect`, `MudAutocomplete`
`<MudSelect OffsetX="true" Direction="Direction.Right" ...`
`<MudAutocomplete OffsetX="true" Direction="Direction.Right" ...`

MudAutocomplete: Forward PopOver attributes OffsetX, OffsetY and Direction

---

src/MudBlazor/Styles/components/_input.scss

Fixes #1838
Before fix:
After fix:

MudTextField: adds missing right margin to adornment start icon (#1838)

---

src/MudBlazor/Styles/components/_inputcontrol.scss

NumericField: fixes spinner position in RTL

---

src/MudBlazor.Docs/Pages/Components/Badge/Examples/BadgeInteractiveExample.razor
src/MudBlazor/Components/Badge/MudBadge.razor.cs

Fixes `Badge position` in #92
This PR obsoletes the `Left` property.

MudBadge: fixes alignment in RTL

---

src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

`MudDatePicker` and `MudTimePicker` have the `InputIcon` property.
These pickers are the only ones that have this property, all others have `AdornmentIcon`.
For MudBlazor consistency, this PR adds the `MudPicker.AdornmentIcon` property
and marks the `MudPicker.InputIcon` as `[Obsolete]` so that it can safely be removed in the future.

Add MudPicker.AdornmentIcon to replace MudPicker.InputIcon 

---

src/MudBlazor.Docs/Pages/Features/RTLLanguages/Examples/RTLLanguagesLayoutExample.razor
src/MudBlazor/Components/Switch/MudSwitch.razor

As mentioned in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-857573814
Fixes small problem caused in `RTLLanguages` docs page due to this PR.

MudSwitch: flipped in RTL

---

src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteUsageExample.razor
src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteValidationExample.razor
src/MudBlazor.Docs/Pages/Components/Select/Examples/MultiSelectCustomizedExample.razor
src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectDenseExample.razor
src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectDisabledExample.razor
src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectUsageExample.razor
src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
src/MudBlazor.sln
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Components/Select/MudSelect.razor
src/MudBlazor/Components/Select/MudSelect.razor.cs

This PR changes the following:
- MudAutocomplete: The `AdornmentIcon` attribute sets both the `OpenIcon` and `CloseIcon` attributes;
- MudAutocomplete: Switched property `CloseIcon` <> `OpenIcon` values;
- MudAutocomplete: Reversed `UpdateIcon()` state;
- MudAutocomplete: Added docs examples for `AdornmentIcon`, `OpenIcon` and `CloseIcon` attributes;
- MudAutocomplete: Removed calls to `UpdateIcon()` and added a call to `IsOpen` setter so that the icon always reflects the correct `IsOpen` state;
- MudAutocomplete: Property `CurrentIcon` is now private (**breaking**);
- MudAutocomplete: Method `UpdateIcon()` is now private (**breaking**);
- MudSelect: The `Adornment` attribute is now applied;
- MudSelect: The `AdornmentIcon` attribute sets both the `OpenIcon` and `CloseIcon` attributes;
- …

MudSelect and MudAutocomplete Adornment improvements

---

src/MudBlazor.UnitTests/Components/AppBarTests.cs
src/MudBlazor/Components/AppBar/MudAppBar.razor
src/MudBlazor/Components/AppBar/MudAppBar.razor.cs

Hi,
I've recently been using Mudblazor to write a desktop app using the Blazor Web Control in the .Net 6 preview
One of the things I tried to do was add some icons to the right hand side of the AppBar
for close / minimise / restore window
However I wanted to get rid of the right padding on the ToolBar nested inside the AppBar
I couldn't see a way to do this directly so I've modified the AppBar
to include a ToolBarClass parameter so you can do something like
```
<MudAppBar Dense="true" ToolBarClass="pr-0">
</MudAppBar>
```
I'm not sure if the parameter is ok in terms of the naming, but it's a small change.

AppBar: Add support for adding classes to the nested ToolBar

---

src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerBasicUsageExample.razor
src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerBasicUsageExample.razor
src/MudBlazor.Docs/Pages/Components/TimePicker/TimePickerPage.razor
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/TimePickerTests.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
src/MudBlazor/Components/Picker/MudPicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

This PR is a proposition to solve the [can we have "MudDatePicker" Readonly](https://github.com/Garderoben/MudBlazor/issues/1924) issue.

DatePicker and TimePicker: added ReadOnly parameter

---

src/MudBlazor.UnitTests/Components/CarouselTests.cs
src/MudBlazor/Components/Carousel/MudCarousel.razor
src/MudBlazor/Components/Carousel/MudCarousel.razor.cs

It's based on #1857 and allow some customization for Navigation and Delimiters Buttons on MudCarousel.

Carousel: added parameters for navigation and delimiter button classes

---

src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTr.razor.cs
src/MudBlazor/Components/Table/TableContext.cs

This is a proposition to fix the issue reported in [MudTable example: Cancelling inline editing can lead to wrong item in list](https://github.com/Garderoben/MudBlazor/issues/1834)

Table: Fix fo #1834, Cancelling inline editing can lead to wrong item in list

---

src/MudBlazor.Docs/Pages/Components/Avatar/AvatarPage.razor
src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarIconExample.razor
src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarLetterExample.razor
src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarSizeExample.razor
src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarVariantsExample.razor
src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
src/MudBlazor/Styles/components/_avatar.scss

This PR is a proposition for [Avatar with border](https://github.com/Garderoben/MudBlazor/issues/1798) feature request. Below is the result.

Border addition for MudAvatar

---

src/MudBlazor/Styles/components/_inputcontrol.scss

MudNumericField: fixes spinner width 

---

src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTableBase.cs
src/MudBlazor/Components/Table/MudTr.razor.cs

This PR is a proposition to answer to the [Add 'OnRowEditPreviewClick' event callback to MudTable](https://github.com/Garderoben/MudBlazor/issues/1934) feature request.

OnPreviewEditClick parameter addition for MudTable

---

src/MudBlazor/Styles/components/_avatar.scss

MudAvatar: fixes background color for outlined variants (#1987)

---

src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
src/MudBlazor/Extensions/ElementReferenceExtensions.cs

- Steps to repro.
- Open docs site
- Open Nav
-  Rapidly click between Drawer and Element
```
​ [2021-06-24T07:58:25.639Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
at MudBlazor.ElementReferenceExtensions.MudAddEventListenerAsync[T](ElementReference elementReference, DotNetObjectReference`1 dotnet, String event, String callback, Boolean stopPropagation) in C:\Users\mikes.SURCOUF\source\repos\MudBlazor\src\MudBlazor\Extensions\ElementReferenceExtensions.cs:line 56
at MudBlazor.MudDrawer.OnAfterRenderAsync(Boolean firstRender) in C:\Users\mikes.SURCOUF\source\repos\MudBlazor\src\MudBlazor\Components\Drawer\MudDrawer.razor.cs:line 264
at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
- There is …

Fix NRE in MudAddEventListenerAsync

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithParameters.razor
src/MudBlazor.UnitTests/Components/DialogTests.cs
src/MudBlazor/Components/Dialog/DialogParameters.cs
src/MudBlazor/Components/Dialog/DialogReference.cs
src/MudBlazor/Components/Dialog/IDialogReference.cs
src/MudBlazor/Services/DialogService.cs

When using parameters for dialog like this:
```c#
public partial class PackLockDialog : ComponentBase
{
// ...
[Parameter]
public DateTime? LockedDate { get; set; }
// ...
}
// ...
var parameters = new DialogParameters
{
{ nameof(PackLockDialog.LockedDate), DateTime.Today },
};
var dialogRef = dialogService.Show<PackLockDialog>(string.Empty, parameters);
```
They get re-set every time a StateHasChanged is called for the components, which use these parameters.
This PR adds a AreParametersRendered property for a DialogReference to restrict parameters setting only for the first time when the component is created.

Dialog: Fixed dialog parameters re-set on each StateHasChanged overwriting current values

---

src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs

Changed modifier for DismissAll() to public, because people may want to dismiss all dialogs that are currently displayed.
I can see no reason to hide this method from developers.

DialogProvider: Changed modifier for DismissAll() to public

---

src/MudBlazor/Components/Tabs/MudTabs.razor.cs

I think Equals() should be used instead operator for activating panel by ID.
For example now it is not possible to use strings as Ids.

MudTabs: Using Equals instead operator for activating tabpanel by ID

---

src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
src/MudBlazor/Components/Input/MudInputAdornment.razor
src/MudBlazor/Components/Input/MudRangeInput.razor
src/MudBlazor/Components/Picker/MudPicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor.cs

- Forwarded `AdornmentColor` attribute;
- Added `Variant` attribute to replace `InputVariant` attribute and marked it `[Obsolete]`.
These components are the only ones that have this attribute, all others have `Variant`;
- Changed `AdornmentIcon` default from `Icons.Filled.Event` to `Icons.Material.Filled.Event`
as usage of  `Icons.Material.Filled` seems to be the norm in the docs and `MudTimePicker` also makes use of it;
- Fixed a bug in `MudInputAdornment.razor` where `Size` would always be set to `Size.Medium`;

DatePicker: improvements regarding Variant, Adornment and Size

---

src/MudBlazor/Components/Badge/MudBadge.razor
src/MudBlazor/Components/Badge/MudBadge.razor.cs

I talked with @porkopek a couple days ago about adding an OnClick event to the MudBadge. I'm adding a draft PR as I expect there will be additional changes to make, maybe as a different CSS class for badges with a click event etc.
Not sure what happened to the commit history though...

Added OnClick event to MudBadge

---

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableServerSidePaginateExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableLoadingTest.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTable.razor
src/MudBlazor/Components/Table/MudTable.razor.cs
src/MudBlazor/Styles/components/_table.scss

- Set loading in table automatically for server side pagination
- Have text when there are no rows found / when loading in table
- table progress loader is put over the first row instead of between the first row and Thead.

Table: improve loading bar and add parameters for loading-text and no-rows-text

---

src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogOptionsExample.razor
src/MudBlazor/Components/Dialog/DialogOptions.cs
src/MudBlazor/Styles/components/_dialog.scss

Among all the possible positions for a dialog, I found that the _TopCenter_ position was missing from my point of view.
I have also added a _Position_ example in the _Dialog_ section of the official website with _TopCenter_.

MudDialog: added TopCenter, BottomCenter,  CenterLeft and CenterRight positions

---

src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarPositionExample.razor
src/MudBlazor/Components/Snackbar/Defaults.cs
src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
src/MudBlazor/Components/Snackbar/MudSnackbarProvider.razor.cs
src/MudBlazor/Styles/components/_snackbar.scss

Closes `Snackbar: Start/End options for Position` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-866619540
Requires #2040

Snackbar: added start/end position, fixed alignment bug (RTL)

---

src/MudBlazor.Docs/Pages/Components/Charts/Examples/DonutExample2.razor
src/MudBlazor/Components/Chart/MudChart.razor
src/MudBlazor/Components/Chart/MudChart.razor.cs
src/MudBlazor/Enums/Position.cs

Fixes `Donut Chart: Start/End options for LegendPosition` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-866619540

Donut chart: added start/end options for LegendPosition (RTL)

---

src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
src/MudBlazor.sln
src/MudBlazor/Base/MudFormComponent.cs
src/MudBlazor/Components/DatePicker/DateRange.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs

- Fixes #1979;
- Added default constructor: `new DateRange()` because it's just weird to call `new DateRange(null, null)`;
- Corrected some suspicious code in `MudDateRangePicker.HasValue()`;
- Added unit tests; 😄

DateRangePicker: Fix initializing DateRange with null values

---

src/MudBlazor.Docs/Pages/Components/Tabs/Examples/CustomDynamicTabsExample.razor
src/MudBlazor.Docs/Pages/Components/Tabs/Examples/DynamicTabsSimpleExample.razor
src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/SimpleDynamicTabsInteractionTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/SimpleDynamicTabsTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/SimpleDynamicTabsTestWithToolTips.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsWithHeaderTest.razor
src/MudBlazor.UnitTests/Components/DynamicTabsTests.cs
src/MudBlazor.UnitTests/Components/TabsTests.cs
src/MudBlazor/Components/Tabs/MudDynamicTabs.razor
src/MudBlazor/Components/Tabs/MudDynamicTabs.razor.cs
src/MudBlazor/Components/Tabs/MudTabs.razor
src/MudBlazor/Components/Tabs/MudTabs.razor.cs
src/MudBlazor/Components/Tabs/TabHeaderPosition.cs
src/MudBlazor/Styles/components/_tabs.scss

Inspired by request in #1568, the PR introduces two ```RenderFragements``` for MudTabs that can add additional content in the header panel and the header of each tab panel.
Besides ```MudDynamicTabs``` using this new fragment to render an add and remove button. For each operation, a Callback needs to be supplied. 
Unit tests and updates of the docs are provided as well. 
Design is still missing. I guess @Garderoben and @porkopek are the experts on this matter.

MudTabs with additional header content

---

src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselBindingExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Carousel/CarouselBindingTest.razor
src/MudBlazor.UnitTests/Components/CarouselTests.cs
src/MudBlazor/Base/MudBaseItemsControl.cs
src/MudBlazor/Components/Carousel/MudCarouselItem.razor.cs

This is a Fix for #1922  
- Implemented IDisposable for MudCarouselItem, that fixes DataBinding ItemsSource parameter with phsycal Items from MudBaseItemsControl;
- Updated Carousel DataBinding example with Add and Delete actions;
- Added some tests.

Carousel: Allow to add and remove items (#1922)

---

src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsPositionExample.razor
src/MudBlazor/Components/Tabs/MudTabs.razor.cs
src/MudBlazor/Styles/components/_tabs.scss

Closes `MudTabs: Start/End options for Position` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-866619540

MudTabs: added start/end options for Position (RTL)

---

src/MudBlazor.Docs/Pages/Components/Tooltip/Examples/TooltipPostionExample.razor
src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
src/MudBlazor/Enums/Placement.cs
src/MudBlazor/Styles/components/_tooltip.scss

Fixes `MudTooltip: Left/Right options for Placement + End should not be right in RTL, same with Start` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-866619540

MudTooltip: added start/end options for Placement (RTL)

---

src/MudBlazor.Docs/Components/DocsApi.razor
src/MudBlazor.Docs/Components/DocsBinding.razor
src/MudBlazor.Docs/Components/DocsObsolete.razor
src/MudBlazor.Docs/Extensions/MethodInfoExtensions.cs
src/MudBlazor.Docs/Models/ApiMethod.cs
src/MudBlazor.Docs/Models/ApiProperty.cs

Implementation of the  [API documentation improvements](https://github.com/Garderoben/MudBlazor/issues/1805) issue.
**Changes**
* A _Method_ section has been added.
* _Obsolete_ methods are displayed.
* _Obsolete_ properties are displayed.
* If the component does not have a method, the _Methods_ section is not displayed.
* An icon is shown when the property is bindable in both directions.
* An icon is shown when the property is unidirectional.
* Simple _EventCallbacks_ are displayed as an empty string in the _Default_ column.
**Notes**
* All API pages have been tested without failure.
* The following methods are not displayed. Should they be present in the Methods section?
```C#
* ToString
* GetType
* GetHashCode
* Equals
* SetParametersAsync
* ReferenceEquals
```
* The list of properties …

Docs, API pages: Add public methods and general improvements

---

src/MudBlazor.Docs/Pages/Components/Tabs/Examples/CustomDynamicTabsExample.razor
src/MudBlazor.UnitTests/Components/DynamicTabsTests.cs
src/MudBlazor/Components/Tabs/MudDynamicTabs.razor.cs
src/MudBlazor/Components/Tabs/MudTabs.razor.cs

After the design work @Garderoben a unit test is added to check if class names are applied as intended, besides the ```InternalClassName``` has now only a getter and a description. Just a tiny improvement

Tabs: Restructure property 'InternalClassName' and add a unit test

---

src/MudBlazor.Docs/Pages/Components/Typography/Examples/TextAlignmentExample.razor
src/MudBlazor/Components/Typography/MudText.razor.cs
src/MudBlazor/Enums/Align.cs

Closes `MudText: Start/End options for Align` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-866619540
LTR:
RTL:

MudText: add start/end options for Align (RTL)

---

src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioContentPlacementExample.razor
src/MudBlazor/Components/Radio/MudRadio.razor.cs
src/MudBlazor/Enums/Placement.cs
src/MudBlazor/Styles/components/_radio.scss

Closes `MudRadio: Left/Right options for Placement` in #92

MudRadio: add left/right options for Placement (#92)

---

src/MudBlazor/Components/Snackbar/SnackBarMessageState.cs
src/MudBlazor/Components/Snackbar/Snackbar.cs

This PR improves the fade effect by replacing the `DateTime` with a `Stopwatch` which measures more accurately.
For one `MudSnackbar` it really does not matter as both return `500 ms.`
`Stopwatch`'s addition is when multiple `MudSnackbars` are being faded.
Some numbers for the "Open Filled Variants" screenshot, fade in, fade out respectively:
DateTime/Stopwatch : 500|500 ms.
DateTime/Stopwatch : 503|497 ms.
DateTime/Stopwatch : 505|495 ms.
DateTime/Stopwatch : 507|493 ms.
DateTime/Stopwatch : 508|492 ms.
DateTime/Stopwatch : 500|500 ms.
DateTime/Stopwatch : 509|491 ms. 
DateTime/Stopwatch : 516|484 ms.
DateTime/Stopwatch : 519|481 ms.
DateTime/Stopwatch : 523|477 ms.
Notice the maintained component order which improves the fading.
Before
After
Before
After

Snackbar: Improve fade effect with stopwatch

---

src/MudBlazor.Docs/Extensions/MethodInfoExtensions.cs

Trying to solve the following issue :
> I looked at dev.mudblazor.com and you seem to be lowercasing Task ValueTask etc not which is not correct. They are not aliases

Docs, API pages: Add public methods and general improvements : Modifications

---

src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuDirectionExample.razor
src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuOffsetExample.razor
src/MudBlazor.Docs/Pages/Components/Popover/Examples/PopoverLocationExample.razor
src/MudBlazor/Components/Popover/MudPopover.razor.cs
src/MudBlazor/Enums/Direction.cs

Closes `MudMenu: Start/End options for Direction` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-866619540
Closes `MudMenu: Start/End options for Offset` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-866619540
Closes `MudPopover: Start/End options for Direction` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-866619540

MudMenu, MudPopover: add start/end options for Direction (#92)

---

src/MudBlazor.Docs/Pages/Features/RTLLanguages/Examples/RTLLanguagesLayoutExample.razor
src/MudBlazor.Docs/Pages/Features/RTLLanguages/Examples/RTLLanguagesTextfieldExample.razor
src/MudBlazor.Docs/Pages/Features/RTLLanguages/ManualMarkDown/RTLLanguagesMarkdownRtlProvider.razor
src/MudBlazor.Docs/Pages/Features/RTLLanguages/RTLLanguagesPage.razor
src/MudBlazor.Docs/Shared/MainLayout.razor
src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs
src/MudBlazor/Components/Layout/MudLayout.razor
src/MudBlazor/Components/Layout/MudLayout.razor.cs
src/MudBlazor/Components/RTLProvider/MudRTLProvider.razor
src/MudBlazor/Components/RTLProvider/MudRTLProvider.razor.cs

Closes  #1954
Closes `Dialog + Snackbar: explain in docs RTL page + apply RTL in docs` in https://github.com/Garderoben/MudBlazor/issues/92#issuecomment-866619540
Drawer support isn't working at the moment. I think its not possible to keep the `RightToLeft` property in `MudLayout` for backwards compability. Maybe someone has a solution.

Added MudRTLProvider, removed RightToLeft property from MudLayout (RTL)(BREAKING CHANGE)

---

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs

Task.Delay is covered by WaitForAssertion

Autocomplete: Remove unnecessary Task.Delay

---

src/MudBlazor/Styles/components/_tabs.scss

MudTabs: fix padding/margin in dynamic tabs (RTL)

---

src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarHtmlInMessageExample.razor

Added a counter to see the order of snackbars when button is clicked multiple times.

Snackbar docs: Added a counter to the "HTML in messages" example

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest4b.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Extensions/TableExtensions.cs

I would like to add a unit test for this variation but that would require an IQueryable source to apply it against, and there doesn't seem to be support for that in the code base.  Any suggestions?

Table: add IQueryable variation for table orderBy extension

---

src/MudBlazor/Components/AppBar/MudAppBar.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor

It should fix this
This happens when you write a search in autocomplete and immediately delete it. The Portal is not disposed and it's created a new one

Portal: dispose portal in autocomplete in the right way

---

src/MudBlazor/Services/Scroll/ScrollListener.cs

This PR changes changes method `ScrollListener.Subscribe()` to `async void` (which is allowed for events),
in order to prevent the usage of `Task.Run()`, which is not recommended in single thread scenario's.

Changed method ScrollListener.Subscribe to async to avoid Task.Run

---

src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs

This PR changes changes method `ResizeListenerService.Start()` to `async void` (which is allowed for events),
in order to prevent the usage of `Task.Run()`, which is not recommended in single thread scenario's.

Changed method ResizeListenerService.Start to async to avoid Task.Run

---

src/MudBlazor.Docs/Pages/Components/Alert/AlertPage.razor
src/MudBlazor.Docs/Pages/Components/Alert/Examples/AlertCloseExample.razor
src/MudBlazor.Docs/Pages/Components/Alert/Examples/AlertPositionExample.razor
src/MudBlazor.Docs/Pages/Components/Alert/Examples/AlertSimpleExample.razor
src/MudBlazor.sln
src/MudBlazor/Components/Alert/AlertTextPosition.cs
src/MudBlazor/Components/Alert/MudAlert.razor
src/MudBlazor/Components/Alert/MudAlert.razor.cs
src/MudBlazor/Styles/components/_alert.scss

Here is a PR proposing the following for the _MudAlert_ component:
* Different ```AlertTextPosition``` : _Center, Start, End, Left and Right_
* Close option with ```ShowCloseIcon```
* ```CloseIconClicked``` EventCallback can be used to get the event when the _Close Icon_ is clicked
* ```CloseIcon``` parameter gives the possibility to define the icon for the _Close Icon_
* The official documentation has been updated to propose examples. See the screenshot below.

MudAlert: add TextPosition and Close option

---

src/MudBlazor/Styles/components/_overlay.scss

Fixes #2203
Before fix:
After fix:

MudOverlay: change cursor on hover  (#2203)

---

src/MudBlazor.Docs/Pages/Components/Timeline/Examples/TimelineModeExample.razor
src/MudBlazor/Components/Timeline/MudTimeline.razor.cs
src/MudBlazor/Enums/TimelineMode.cs
src/MudBlazor/Styles/components/_timeline.scss

Adds `start/end` options, fixes alignment issue

MudTimeline: Add rtl support

---

src/MudBlazor/Base/MudBaseItemsControl.cs

It's written in MudBaseItemsControl's class, and shoudn't reffer to any component.

Fix for SelectedIndex text on Docs for MudCarousel and MudTimeline

---

src/MudBlazor.Docs/Services/GitHubApiClient.cs

Increased to max contributors gotten from to API (per page) from the default 30 to the maximum of 100 to show all contributors on the 'Meet the team' docs page

Increased max contributors

---

src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
src/MudBlazor/Styles/components/_dialog.scss

Fixes #2201
Before fix:
After fix:

MudDialog: Fix close button dialog button alignment in RTL (#2201)

---

src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTableBase.cs

Closes #1861
The current `NavigateTo` method only allows to navigate to the `first`, `last`, `previous` and `next` page.
This method allows you to specify a page number index.
This is required for `MudPagination`

MudTable: Add navigate to page method

---

src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateTimeMinValueDatePickerTest.razor
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
src/MudBlazor/Extensions/DateTimeExtensions.cs

Fixes #2319
This is a fix for [#2319](https://github.com/Garderoben/MudBlazor/issues/2319).
Here are the modifications / remarks : 
* Fixed exception with ```DateTime.MinValue```
* Fixed ```StartOfWeek``` method in DateTime extension for another exception when using ```DateTime.MinValue```
* Fixed when trying to go to the past when the year is 0001 and it is January
* An empty disabled button has been added for Sunday because the first day in January for the year 0001 is Monday
* A test has been added to validate the case of the exception
* The implementation has been done in a way that inherited code and logic should not be affected

DatePicker: Fix exceptions when binding against Date.MinValue #2319

---

src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
src/MudBlazor.UnitTests/Components/DialogTests.cs
src/MudBlazor.UnitTests/Components/DynamicTabsTests.cs
src/MudBlazor.UnitTests/Extensions/IRenderedComponentExtensions.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

in these cases the `as` should be a cast, since if it isnt of that type it would be a null ref

fix some incorrect as usages

---

src/MudBlazor/Utilities/BindingConverters/DateConverter.cs

before this change the default was ignored since it was always set in the constructor

fix NullableDateConverter default

---

src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
src/MudBlazor/Utilities/MudColor.cs

This PR contains two fixes
Currently, the hue value is not stable when a color is selected in the spectrum mode.
This is the result of the different color spaces between HSL and RGB. For the same RGB colors multiple HSL exists and vice versa. I have introduced a new constructor of ``MudColor`` to accept a color where the H value is copied. This constructor is used, in the ``MouseClick`` event handler. 
Besides, there is a new unit test to cover this behavior. 
The selector only changes if a click outside of the selector circle itself is registered.
The selector has now a click event handler and the handling involves that the offset values are relative values. 
```
private void SetSelectorBasedOnMouseEvents(MouseEventArgs e, bool offsetIsAbsolute)
{
_selectorX = (offsetIsAbsolute == true ? …
```

MudColorPicker fixing unstable hue value in spectrum mode and enable click inside the selection circle

---

src/MudBlazor.UnitTests.Viewer/TestComponents/AvatarGroup/AvatarGroupRemoveTest.razor
src/MudBlazor.UnitTests/Components/AvatarGroupTests.cs
src/MudBlazor/Components/Avatar/MudAvatar.razor.cs

Closes #2434.
Also adds a test to demonstrate the issue. This wouldn't have passed before my `IDisposable` fix.

MudAvatar: add IDisposable to dispose properly

---

src/MudBlazor.Docs/Pages/Components/Table/Examples/TabPagerExample.razor
src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTablePager.razor
src/MudBlazor/Components/Table/MudTablePager.razor.cs
src/MudBlazor/Components/Table/TablePagerTextPosition.cs
src/MudBlazor/Enums/HorizontalAlignment.cs
src/MudBlazor/Styles/components/_table.scss

Here are the list of modifications. This gives you the ability to customize what information will be displayed and where it will be displayed.
* Property to hide the Page Number  with ```HidePageNumber```
* Property to hide the Pagination with ```HidePagination```
* Property to define the elements position with ```HorizontalAligment```
* Better vertical alignment of all information in the ```MudTabPager``` (blue line on the attached screenshot)
* There is now a space separation on the left edge for better display (orange square on the attached screenshot)
* ```DisableRowsPerPage``` parameter is now _obsolete_. It has been replaced by the ```HideRowsPerPage``` parameter
* An example has been added in the documentation

MudTabPager : Customization & Alignment

---

src/MudBlazor.Docs/Pages/Components/Alert/AlertPage.razor
src/MudBlazor.Docs/Pages/Components/Alert/Examples/AlertAlignmentExample.razor
src/MudBlazor.Docs/Pages/Components/Alert/Examples/AlertCloseExample.razor
src/MudBlazor.Docs/Pages/Components/Alert/Examples/AlertPositionExample.razor
src/MudBlazor/Components/Alert/MudAlert.razor.cs

* The ```AlertTextPosition``` parameter is replaced by the ```ContentAlignment``` parameter.
* The ```AlertTextPosition``` parameter still works but is marked as _Obsolete_.
* The example in the official documentation has been updated as well.

MudAlert : AlertTextPosition parameter replacement by ContentAlignment parameter

---

src/MudBlazor/Components/Typography/MudText.razor

MudText with Typo.inherit was not created due to missing case in switch statement.

Fixed invisible MudText with Typo.inherit

---

src/MudBlazor/Components/NavMenu/MudNavLink.razor
src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs

Issue: #2052.
in `<MudNavLink>` reuse OnClickHandler from `MudBaseSelectItem` which handles Command

MudNavLink: re-use OnClickHandler from MudBaseSelectItem 

---

src/MudBlazor.UnitTests/Components/MudThemeProviderTests.cs
src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
src/MudBlazor/Utilities/MudColor.cs

Providing a fix for the issues mentioned in #2468 and #2526. 
The ``MudColor`` class used the logic provided for by the ``ColorManager`` for handling HSL values. There was a complicating expression of simple ceiling functions. I replaced it with ``Math.Ceiling(...)``. Besides, I added unit tests for MudThemeProvider for different cultures. It is not a very smart way of testing the output of ``MudThemeProvider`` but it is a beginning.

MudThemeProvider: fix #2468 and #2526. fixing culture issues 

---

src/MudBlazor/Components/Progress/MudProgressCircular.razor

We're fixing MudProgressCircular to look unfinished even it has max value
Before:
After:

Fix MudProgressCircular looking not full value

---

src/MudBlazor.Docs/Pages/Components/Hidden/Examples/HiddenExample.razor
src/MudBlazor.Docs/Pages/Features/Breakpoints/BreakpointsPage.razor
src/MudBlazor.Docs/Pages/Features/Display/DisplayPage.razor
src/MudBlazor.Docs/Pages/Features/Flex/FlexPage.razor
src/MudBlazor.UnitTests/Components/DrawerTest.cs
src/MudBlazor.UnitTests/Mocks/MockResizeListenerService.cs
src/MudBlazor.UnitTests/Services/ResizeListenerServiceTests.cs
src/MudBlazor/Components/Grid/MudItem.razor
src/MudBlazor/Components/Table/MudTableBase.cs
src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
src/MudBlazor/Enums/MaxWidth.cs
src/MudBlazor/Enums/Width.cs
src/MudBlazor/Services/ResizeListener/Breakpoint.cs
src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
src/MudBlazor/Styles/abstracts/_variables.scss
src/MudBlazor/Styles/components/_dialog.scss
src/MudBlazor/Styles/components/_grid.scss
src/MudBlazor/Styles/components/_table.scss
src/MudBlazor/Styles/layout/_container.scss
src/MudBlazor/Styles/utilities/_borders.scss
src/MudBlazor/Styles/utilities/_display.scss
src/MudBlazor/Styles/utilities/_flex.scss
src/MudBlazor/Styles/utilities/_spacing.scss
src/MudBlazor/TScripts/mudResizeListener.js
src/MudBlazor/Themes/Models/Breakpoints.cs

Added an XXL breakpoint for larger screen sizes (+2560).
Tested on my local machine as follows:
```xml
<MudGrid>
<MudItem xs="12" xxl="6">
<MudPaper>
Block 1
</MudPaper>
</MudItem> 
<MudItem xs="12" xxl="6">
<MudPaper>
Block 2
</MudPaper>
</MudItem>     
</MudGrid>
```
On `<2560` screen size this correctly displays 2 separate rows:
And on `+2560` screens, they are displayed on the same row:
Closes #2270

Added XXL  breakpoint

---

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

Fixes #2617 
A call to `ToggleMenu` is not being triggered when clicking away from the `MudAutocomplete` component. `ToggleMenu` is where the call to `CoerceTextToValue` happens. I found that `IsOpen` was being set to false whenever the search function returned an empty list, but this didn't actually do anything, from what I could tell. So, removing this one line fixes this issue.
I looked into adding it to `OnInputBlurred`, but that doesn't work because when a selection is made it also triggers `OnInputBlurred`, as the comment by @henon pointed out.)

MudAutoComplete: Fix CoerceText not working on empty search results (#2617)

---

src/MudBlazor/Components/Select/MudSelect.razor
src/MudBlazor/Components/Select/MudSelect.razor.cs

Solves duplicate issues: #2452, #2593.
Detail: Added if block visible check for selectable items to make sure they show/hide correctly. (Closing popover may not be sufficient against inputs)
Before:
https://user-images.githubusercontent.com/78308169/132133795-7cf56751-f23f-4099-ab59-7112fd94da17.mp4
After:
https://user-images.githubusercontent.com/78308169/132133811-e2174c99-644b-4f22-bea2-17e46f826282.mp4
fixes #2452
fixes #2593.

Select: Prevent item click when drop-down is closed in multi-selection mode

---

src/MudBlazor/Components/Menu/MudMenu.razor

This is the same approach in #2647, this time implement on MudMenu.
I create a temporary example described on #2509 and it seemed to solve this. @henon 
But we should notice that, this approach doesn't solve all issues. Ex. having two menus when clicking a menu on AppBar still remains (Maybe these related to Portal).
fixes #2509

Menu: Prevent item click when drop-down is closed

---

src/MudBlazor.Docs/Pages/Components/Pagination/Examples/PaginationTableExample.razor

I think it's about MudPagination can't wrap and it causes the MudTable not fit in small screens.
Pagination example will revised that it can seem on mobile properly. And it also have full width to see the table full on bigger screens.
Before (Mobile)
After (Mobile)
Before (Desktop)
After (Desktop)

Docs: optimize table pagination example for mobile

---

src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
src/MudBlazor/Components/NumericField/MudNumericField.razor.cs

As we discussed in #2643, nullable MudNumericField's value didn't set to null, instead of it showed 0.
This PR should fix that and #2678 . When it's nullable value is 0 it goes automatically to null.
Also it works with HideSpinButtons, arrow keys and shift + mousewheel properly.
Non-nullable fields not affected this.
https://user-images.githubusercontent.com/78308169/132679252-cb29c5f6-5321-4c5b-b594-db7b03580396.mp4
fix #2678

NumericField: Nullable Fix

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest3.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest4.razor
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs

fixes #2651
Two tests have been added to check the two cases reported in the problem.
They are both related to the initialization of the component and the incorrect icon of the _Select All_ feature.

MudSelect : SelectAll fix for #2651

---

src/MudBlazor.UnitTests.Viewer/Pages/Index.razor

As @JohanArleth talks about it in #2643, the test viewer didn't work without xl size because of drawer overlay and AppBar position.
This PR should solve this.

TestViewer: fixed AppBar / Drawer problem

---

src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerValidationTest.razor
src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs

As described #1428 I've set the internal `_value` to the range's end-date so it fullfills the `Required` condition.
Maybe @henon can take care of this as he initially added the `Required`-feature for `DateRangePicker`s in the first place.

DateRangePicker: Not updating validation-status

---

src/MudBlazor.Docs/Pages/Components/Chip/ChipPage.razor
src/MudBlazor.Docs/Pages/Components/Chip/Examples/ChipBasicExample.razor
src/MudBlazor.Docs/Pages/Components/Chip/Examples/ChipOutlinedExample.razor
src/MudBlazor.Docs/Pages/Components/Chip/Examples/ChipTextExample.razor
src/MudBlazor.Docs/Pages/Components/ChipSet/ChipSetPage.razor
src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetSelectedColorExample.razor
src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetVariantsExample.razor
src/MudBlazor/Components/Chip/MudChip.razor.cs
src/MudBlazor/Styles/components/_chip.scss

MudChip and MudChipSet
Variant.Text did nothing and "broke" the component when used.
Added variant.text css, removed most selected css and instead swap between Filled and Text variant if they are used.
Added the possibility to set the SelectedColor only affects the MudChip is its used with a ChipSet
Updated both Chips and ChipSet pages.

MudChip - Added Variant.Text, SelectedColor option and updated docs.

---

src/MudBlazor/Components/Radio/IMudRadioGroup.cs
src/MudBlazor/Components/Radio/MudRadio.razor
src/MudBlazor/Components/Radio/MudRadio.razor.cs
src/MudBlazor/Components/Radio/MudRadioGroup.razor
src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs

When MudRadioGroup and MudRadio types are different, there are no exception thrown, but the radios didn't work, so user may not understand what is the exact problem.
This PR solves this and use the same strategy which MudSelect has.
fix #1307

RadioGroup: Enforce same generic type on child radios

---

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableBasicGroupingInitiallyCollapsedExample.razor
src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTableGroupRow.razor.cs
src/MudBlazor/Components/Table/TableGroupDefinition.cs

Tables using simple grouping can now have all groups collapsed by default. This helps users view only the information they want in large tables. 
fixes #2683

Table: Add default collapse option to basic table grouping

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithReturnValue.razor
src/MudBlazor.UnitTests/Components/DialogTests.cs
src/MudBlazor/Components/Dialog/DialogReference.cs
src/MudBlazor/Components/Dialog/IDialogReference.cs
src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs

Until now the API was quite un-intuitive, especially for getting the return value from the dialog reference. I added overloads and shorthand functions with which you can do it without needing to study the docs.
In the dialog, for returning data:
Until now: `MudDialogInstance.Close(DialogResult.Ok("Closed via OK"))`
Shorthand: `MudDialogInstance.Close("Closed via OK"))`
Outside for getting the return value:
Until now (ughhh):
```csharp
// note how Result looks like the blocking property of Task  *facepalm*
var result = await dialogReference.Result; 
var rv=result.Data as string;
```
Shorthand:
`var rv = await dialogReference.GetReturnValueAsync<string>();`
@Garderoben @mikes-gh You like?

Dialog: improved the API for passing return values

---

src/MudBlazor/Components/Menu/MudMenu.razor

fix #1571.
While on working we need to decide another thing. In current or previous versions, user may have right click on their context menu and browser's context menu opens over their context menu. I think it is unnecessary, should we disable all to make sure menu works clear?

Menu: prevent browser's context menu in WASM on right click menus

---

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiSelectExample.razor

I've removed any reference to "selectedItems2". It was not used in the example. "selectedItems1" has been renamed to "selectedItems".

Unnecessary Declaration of selectedItems2.

---

src/MudBlazor.Docs/Pages/Components/List/Examples/ListSelectionExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListSelectionInitialValueTest.razor
src/MudBlazor.UnitTests/Components/ListTests.cs
src/MudBlazor/Components/List/MudList.razor.cs
src/MudBlazor/Components/List/MudListItem.razor.cs

Adds SelectedValue and allows to pre-select a value in the list by setting its value via a two-way binding.
`object SelectedValue` can be used to pre-select the initial list item and/or manipulate the selection from outside. MudListItem now has a parameter `object Value` for the selection value. All values have to be unique for now, so if you want to use the selection make sure to assign Value in the items.
kinda fixes #1295: Though generics are not what we want in MudList, we do it with type `object` instead. 
fixes #2553
fixes only partially #1779, so we'll not link this issue. It will stay open. will allow us to get #2758 done.

List: add SelectedValue which allows to pre-select list items via value

---

src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/NumericField/MudNumericField.razor
src/MudBlazor/Components/Select/MudSelect.razor
src/MudBlazor/Components/TextField/MudTextField.razor
src/MudBlazor/Components/TextField/MudTextField.razor.cs

TextField: add Clear() method which works even while focused

---

src/MudBlazor/Components/NumericField/MudNumericField.razor

fix #2743.
As @Yomodo said. Mouse wheel function didn't worked on Firefox. It's my bad because i didn't try it with firefox. With a little research, i found that firefox didn't support onmousewheel event on new versions, it use "onwheel" event instead. So we simply add a additional event to work this function in firefox.

NumericField MouseWheel function fix for Firefox

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePagerInfoTextTest.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTablePager.razor.cs

* changed Info to show '0-0 of 0' instead of '1-0 of 0' when filter does not match anything
* added Viewer and bUnit-tests
As it can be tested here: https://dev.mudblazor.com/components/table#table-with-pagination-and-filtering
When filtering for something not matching anything, the info-label will show `1-0 of 0` which should be `0-0 of 0`.

TablePager: fix showing wrong info-text when filter returns no rows

---

src/MudBlazor.UnitTests/Components/TimePickerTests.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

Added functionality for closing the TimePicker.
In Normal mode or OnlyMinutes closes after a user either click directly on a minute or on mouse up on a selected minute.
In OnlyHours mode closes after a user either click directly on a hour or on mouse up on a selected hour.
fixes #2087

TimePicker: Fixed close after selected minutes/hours (#2087)

---

src/MudBlazor.UnitTests/Components/BadgeTests.cs
src/MudBlazor/Components/Badge/MudBadge.razor
src/MudBlazor/Components/Badge/MudBadge.razor.cs

This is basically offering and easy option to hide the badge based on a new Visible parameter.
Before 
After
Also added tests checking the number of span created. 
3 spans when visible (default behavior) vs 1 span when hidden.
resolves #2796

MudBadge: Add Visible parameter (#2796)

---

src/MudBlazor/Components/Select/MudSelect.razor.cs

fix #2092.
MudSelect inherits MudFormComponent and it's reset method.
However this method is insufficient with MultiSelect MudSelect. So when users implement a `selectComponent.Reset()` they may have unexpected results. So we override this method to work properly.
MudSelect also has a ClearAsync method. I think we can use both of them: ClearAsync is a Task and its async, Reset is void and sync.
In summary, since we cannot delete the reset method from MudFormComponent, we override it for MudSelect 🙂 if it's ok, we can talk about MudAutocomplete, it is a little bit different because it didn't have ClearAsync.

Select: Reset clears SelectedValues

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableInlineEditSortTest.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTable.razor.cs
src/MudBlazor/Components/Table/MudTableBase.cs

Makes a copy of the sorted table data for use when the table enters editing mode. To keep the sort action from occurring while editing with a `RowEditingTemplate`.
Resolves #1575
Prior to this change, when using an edit row template and changing the column that is currently sorted, the row can move even as far as not being on this page.
TableInlineEditSortTest - TDD unit test fails on DEV but successful on this branch
1. Navigate to /components/table#inline-edit-mode
2. Click on a row (such as the third row which contains Argon)
3. Edit the Name field which is sorted by default (such as changing it to "bbbArgon" which currently moves it down below Barium)
4. Notice that the position is maintained until the row is committed
https://www.loom.com/share/187d46194efb4e318016f175bfb32202

Table: prevent changing sort while row editing

---

src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
src/MudBlazor/Styles/components/_checkbox.scss

fix #2899.
We change the CheckBox cursor from pointer to default when it is readonly.

CheckBox: Default Cursor when readonly

---

src/MudBlazor.Docs/Pages/Components/Avatar/AvatarPage.razor
src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarImageExample.razor
src/MudBlazor.UnitTests/Components/AvatarTests.cs
src/MudBlazor/Components/Avatar/MudAvatar.razor
src/MudBlazor/Components/Avatar/MudAvatar.razor.cs

Resolves #2893 
Added Alt property to MudAvatar so that when an Image is used, it is possible to set the alt property of the img element.
Lighthouse accessibility test

Added capability to set alt property when Image is used in MudAvatar

---

src/MudBlazor.Docs.Server/Properties/launchSettings.json
src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
src/MudBlazor.UnitTests/Mocks/MockKeyInterceptor.cs
src/MudBlazor/Components/Input/MudInput.razor
src/MudBlazor/Components/Input/MudInput.razor.cs
src/MudBlazor/Components/NumericField/MudNumericField.razor
src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
src/MudBlazor/Extensions/ElementReferenceExtensions.cs
src/MudBlazor/MudBlazor.csproj
src/MudBlazor/Services/KeyInterceptor/IKeyInterceptor.cs
src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
src/MudBlazor/Services/KeyInterceptor/KeyInterceptorOptions.cs
src/MudBlazor/Services/Scroll/ScrollManagerException.cs
src/MudBlazor/Services/ServiceCollectionExtensions.cs
src/MudBlazor/Services/ServiceConfiguration.cs
src/MudBlazor/TScripts/mudKeyInterceptor.js
src/MudBlazor/Utilities/Exceptions/GenericTypeMismatchException.cs
src/MudBlazor/Utilities/RuntimeLocation.cs

KeyboardInterceptor allows to preventDefault specific key strokes directly on the javascript side.
The service significantly improves NumericField which needed some very complex key-handlers to work (and even then it worked only so-so. Before forbidden characters (like [a-z]) were added briefly visible in the text box before being removed by the cleanup logic. With this new interceptor service the keys are prevented and will never show up. 
fixes #2592
**Using the new KeyboardInterceptor**
The interceptor service binds itself against an element reference of the component (in this example `_self`). That means you need a ref to a top-level div of the component you want the interceptor to work on. It attaches a mutation observer to that DOM node to check for re-arrangements of the elements …

Services/NumericField: Add KeyboardInterceptor service

---

src/MudBlazor.Docs/Models/ApiLink.cs

This is a fix for the API section of the chip documentation page. Each component documentation page has a section that displays the API links of the component and its related components. However, this is missing from the chip documentation page because of the way the links are generated.
Before:
After:

Docs: Fix missing API section on chips page

---

src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs

Using null-conditional access operator to access value and _rangeText in the setter of RangeText. This is necessary to not run into a Null Pointer Exception if Editable is set to true and the user manually deletes both dates or if the Clear() is called on the DateRangePicker and the user manually enters a new date.
Fixes #2915 
Manually checked that no Null Pointer Exception occurs anymore and added unit tests

DateRangePicker: Added null safe access to value and _rangeText in the setter of RangeText

---

src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelExpandedMultipleWithoutMultipleExpansionSetTest.razor
src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs

Resolves infinite loop created by cascading StateHasChanged calls. Removes parent logic from child ExpansionPanels and relocates it to the parent ExpansionPanel and removes unneeded state change in addPanels. Indirectly adds support internally for multicasting IsExpanded change events.
resolves  #2763
Test added to existing component test file utilizing a view that would otherwise cause the testing framework to enter the originally detected infinite loop.

ExpansionPanels: Resolves infinite loop created by cascading StateHasChanged calls

---

src/MudBlazor.Docs.Client/MudBlazor.Docs.Client.csproj
src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj
src/MudBlazor.Docs/MudBlazor.Docs.csproj
src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
src/MudBlazor.UnitTests/Components/HiddenTests.cs
src/MudBlazor.UnitTests/Components/PopoverTests.cs
src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
src/MudBlazor.UnitTests/Services/BreakpointServiceTests.cs
src/MudBlazor.UnitTests/Services/EventListenerTests.cs
src/MudBlazor.UnitTests/Services/ResizeBasedServiceTests.cs
src/MudBlazor.UnitTests/Services/ResizeObserverTests.cs
src/MudBlazor/MudBlazor.csproj

Seems updating to rc2 on the net6 branch causes MudPopover tests to fail. 
@just-the-benno @Garderoben

Update to net6 rc.2

---

src/MudBlazor.UnitTests/Components/MudThemeProviderTests.cs
src/MudBlazor.UnitTests/Utilities/BindingConverterTests.cs
src/MudBlazor.UnitTests/Utilities/MudColorTests.cs

Due to the current CultureInfo() constructor usages, unit tests are prone to fail if a test-running-machine has custom regional settings. 
`float1.Culture = new CultureInfo("en-US");`
CultureInfo constructor has an optional **[useUserOverride](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.useuseroverride?view=net-5.0)** parameter which uses default culture settings of .net if false, and uses Windows user's custom regional settings if true. The problem is, it is **true** by default. So, all the tests with CultureInfo() constructors depend on potential custom user settings. 
Always set 'useUserOverride' parameter to 'false' with CultureInfo constructors in unit test bodies in order to avoid the problem, and make tests more robust.
`float1.Culture = new …

Tests: Fix user regional settings dependent unit tests

---

src/MudBlazor/Styles/layout/_appbar.scss
src/MudBlazor/Styles/layout/_drawer.scss

Mini drawer does not act as it expected when DrawerClipMode.Docked is used. This PR tries to solve this problem.
Manually.

Fix mini drawer when clipmode is docked

---

src/MudBlazor/Styles/layout/_drawer.scss

The Mini mode drawer when "closed" or in mini mode, it still received the higher z-index even when it should not. resulting in overlapping content. I changed so it only applies the z-index change if the mini drawer is "open".
**Issue can be seen here:**
Manual/Visual testing.

Drawer: Fixed mini mode drawer's z-index when "closed"

---

src/MudBlazor.Docs/Pages/Customization/Theming/Examples/TypographyDefaultFontExample.razor
src/MudBlazor.Docs/Pages/Customization/Theming/Examples/TypographySettingsExample.razor
src/MudBlazor.Docs/Pages/Customization/Theming/Overview.razor
src/MudBlazor.Docs/Pages/Customization/Theming/Typography.razor
src/MudBlazor.Docs/Services/MenuService.cs
src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
src/MudBlazor/Themes/Models/Typography.cs

Before when changing the default theme's typography you had to specify all property's even if you only wanted to change one of them.
Before example:
```
Typography = new Typography()
{
Default = new Default()
{
FontFamily = new[] { "Robot", "Helvetica", "Arial", "sans-serif" },
FontSize = ".875rem",
FontWeight = 400,
LineHeight = 1.43,
LetterSpacing = ".01071em"
},
H1 =.....
```
And if you wanted the change the font from `Robot` to something else you had to do it for all types `Default`, `H1`, `H2` etc..
Now its possible to only change the one you actually want to change, and all typos use the `Default` typos FontFamily unless specified, this way you don't have to change it on all 14.
```
Typography = new Typography()
{
Default = new Default()
{
FontFamily = new[] { "Poppins", …
```

Theme: Typography defaults and documentation

---

src/MudBlazor.Docs/Components/DocsApi.razor
src/MudBlazor.Docs/Components/DocsTypeInfo.razor
src/MudBlazor.Docs/Models/ApiProperty.cs

This commit adds a tooltip with the possible enum constants for enum type properties. It implements, at least in large part, point no. 3 of the https://github.com/MudBlazor/MudBlazor/issues/1020 issue.
I checked visually several properties. I checked it on: Blazor Server and WebAssembly, desktop and mobile.
The tooltip looks like this:

Docs: Add tooltips for enum types showing enum constants

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs

MudBaseDatePicker sets the Culture and Format on the default converter.
The CurrentCulture is used, and the CurrentCulture ShortDateFormat is used for the Format.
When DateFormat is set the converters Format is replaced.
When DateForamt is not set but Culture is set on the component this led to the unexpected behavior
of the CurrentCulture date format being used instead of the culture that was set (as reported in #2962).
With this change, setting the culture also leads to a Format change unless the DateFormat property has been set.
The Terminology “touched” is used for the private field to match the Touched property terminology.
Fixes #2962

DatePicker: Fix setting culture not leading to DateFormat change (#2962)

---

src/MudBlazor.UnitTests/Components/PopoverTests.cs
src/MudBlazor/Components/Popover/MudPopoverService.cs

There is an exception in docs website logs that relates to `MudPopoverService` setup.
I think this is because `OnAfterRenderAsync` may continue to run after browser has disconnected
The exception is cosmetic because the browser connection is already closed.
However it is good to get it out of the logs so we can see real exceptions.
```
Microsoft.JSInterop.JSDisconnectedException:
at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS (Microsoft.AspNetCore.Components.Server, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
at Microsoft.JSInterop.JSRuntime.InvokeAsync (Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
at Microsoft.JSInterop.JSRuntime+<InvokeAsync>d__16`1.MoveNext (Microsoft.JSInterop, …
```

PopoverService:  may be initializing when browser is disconnected

---

src/MudBlazor/Services/Scroll/ScrollEventArgs.cs

Fixes #3185 by changing the type of the properties ScrollTop, ScrollLeft from int to double.
On systems using display scaling, scrollTop may give you a decimal value.
I'm going to add test for MudScrollOnTop component.

MudScollToTop: Fix data types in ScollEventArgs class (#3185)

---

src/MudBlazor.Docs/Components/DocsPage.razor
src/MudBlazor.Docs/Components/DocsPage.razor.cs
src/MudBlazor.Docs/Components/DocsPageHeader.razor
src/MudBlazor.Docs/Components/DocsRenderBenchmark.razor

We have a way to measure docs page render times now:
This is the base line, showing WASM render times to be way too high, BSS times are acceptable:
```
BSS:
components/alert rendered in 80,573ms
components/appbar rendered in 58,1864ms
components/avatar rendered in 82,9861ms
components/badge rendered in 132,3375ms
components/breadcrumbs rendered in 52,4078ms
WASM:
components/alert rendered in 600ms
components/appbar rendered in 496ms
components/avatar rendered in 546ms
components/badge rendered in 571ms
components/breadcrumbs rendered in 515ms
```
Temporarily the measurement is shown right on the top of the page.
Note, to get a true measurement you need to do a warm-up. You need to click a few times between Alert and AppBar to get a representative measurement.
So far I found this: (the …

Docs: Add render performance measurement in test environments

---

src/MudBlazor/TScripts/mudKeyInterceptor.js

Changed javascript mudKeyInterceptor to use "replace" instead of "replaceAll" to improve compatibility with older browsers, that causes Blazor to crash.
The changes don't cause change of behaviour when the `pattern` parameter is a `RegExp`, like in this case.
Solves issue #3348
Tested running the application that was crashing using the new code, and running all existing tests.

MudKeyInterceptor: improve compatibility with older browser

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest5.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTableSortLabel.razor.cs
src/MudBlazor/Components/Table/TableContext.cs

This PR fixes incorrect usage of async code path when clicking `MudTable` labels to sort data.
Also fixed double callback for `ServerData` in the same case.
All standard tests apply and passed.
This PR was created based on 5.2.0 tag.

Table: Fixed incorrect async code path for label sorting

---

src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogKeyboardNavigationExample.razor
src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogKeyboardNavigationExample_Dialog.razor
src/MudBlazor.Docs/Pages/Components/Dialog/ManualMarkdown/MarkdownDialogParameters.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogOkCancel.razor
src/MudBlazor.UnitTests/Components/DialogTests.cs
src/MudBlazor.UnitTests/Mocks/MockKeyInterceptor.cs
src/MudBlazor/Components/Dialog/DialogOptions.cs
src/MudBlazor/Components/Dialog/MudDialogInstance.razor
src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs
src/MudBlazor/Services/KeyInterceptor/IKeyInterceptor.cs
src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
src/MudBlazor/TScripts/mudKeyInterceptor.js

This PR improves MudDialog: Pressing ESC closes MudDialog, if close by backdrop click is possible. (closes #3379)
I noticed a difficulty or a bad ux: If there is a component with popover within a dialog and its popover is also closeable by ESC (like MudSelect, Picker), pressing escape does not close the popover, instead the dialog closes. 
To prevent this I had to extend the mudkeyinterceptor with a possibility to update a keyoption:
Example-situation:
- Focused a MudSelect nested in MudDialog, the popover opens (and sets StopDown to ` StopDown = "Key+none"` to stop propagation, otherwise the dialog would close)
- Pressing ESC should now close only the Popover (and sets StopDown to ` StopDown = "none"`)
- Pressing ESC a second time should now close the dialog
There are other components …

Dialog: Close on ESC

---

src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelAsyncExample.razor
src/MudBlazor.Docs/Pages/Components/ExpansionPanel/ExpansionPanelPage.razor
src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor
src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs

If the main body of a MudExpansionPanel is async loaded as a result of the panel being expanded, the opening animation won't work correctly. This PR fixes that.
Visually, as a part of updated documentation.

MudExpansionPanel: Let Changed handler run before actually expanding.

---

src/MudBlazor.Docs/Models/MudIcons.cs
src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor.cs
src/MudBlazor.Docs/Styles/components/_icons.scss

Try scroll here fast, or in general jump with scrollbar: https://dev.mudblazor.com/features/icons#icons
i made two solutions this and this trash: https://github.com/MudBlazor/MudBlazor/pull/3371
But now i finally got the hybrid one working as it should and it just feels so much better.
Current dev one have like 20ms WASM benchmark but it does not work at all when it comes to scrolling, i got this one down to ~50ms so still pretty good.
One downside from this solution is that its not really a flex box / css grid, hence each row and its columns is not always 100% the same width, it can be seen when resizing but its a very minor issues.
fixes #3308

Docs: Icon page implemented blazor virtualization hybrid

---

src/MudBlazor.Docs/Components/DocsApi.razor
src/MudBlazor.UnitTests/Other/CategoryAttributeTests.cs
src/MudBlazor/Attributes/CategoryAttribute.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
src/MudBlazor/Components/Dialog/MudDialog.razor.cs
src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
src/MudBlazor/Components/Element/MudElement.cs
src/MudBlazor/Components/Main/MudMainContent.razor
src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
src/MudBlazor/Components/RTLProvider/MudRTLProvider.razor.cs

The PR contains the following improvements to the https://github.com/MudBlazor/MudBlazor/pull/3413:
1. Adds a test that checks if all component properties have the category attribute.
2. Adds missing categories for properties of: MudDialog, MudDialogInstance, MudElement, MudMainContent, MudRTLProvider, MudDateRangePicker, and NumericField.
3. Changes the displayed name from "Group by class" to "Group by inheritance" in a "button switch".
visually
Screenshot of the changed label on desktop:
Screenshot of the changed label on mobile:

API documentation: Group properties by meaning - improvements

---

src/MudBlazor.Docs/Components/DocsApi.razor
src/MudBlazor.Docs/Models/DocStrings.cs

Reduces computational complexity of the `CheckIsTwoWayProperty()` and `GetPropertyDescription()` methods from O(n) to O(1), which speeds up all https://mudblazor.com/api/ pages both on Wasm and Blazor server side.
On my computer it reduces https://localhost/wasm/api/table time from about 3 seconds to well under a second.
- visually
- checked programmatically that the original and changed methods return the same result for each property of each MudBlazor class
Before - "Rendered in 1828 ms":
Now - "Rendered in 289 ms":
To see the rendered time I go to https://localhost:44399/wasm/components/table page and then click on a Table link in the "Pages" section, like on https://dev.mudblazor.com/.

API documentation: huge performance increase on wasm

---

src/MudBlazor.Docs/Pages/Components/MessageBox/MessageBoxPage.razor

Docs: Added a note in Message Box Page regarding its dependency on Dialog service and linked Dialog Configuration section.
Added a Note on Message Box dependency on Dialog Service. 
I have spent more than 3 hours wondering why my message box was too wide, I have checked my css files any div formatting without considering global configuration for MudDialog.
I was under the impression that Message Box and Dialog are separate components and have no relation with each other. I only figured it out after downloading MudBlazor and checking the code for Message Box component.
If the information was provided in the Message Box page it would have saved me a lot of time.

Docs: Add a note in MessageBox page regarding its dependency on DialogService

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsWithPrePanelContent.razor
src/MudBlazor.UnitTests/Components/TabsTests.cs
src/MudBlazor/Components/Tabs/MudTabs.razor
src/MudBlazor/Components/Tabs/MudTabs.razor.cs

Implementing a new render fragment is placed between the toolbar and panels. This is comparable to the address line in modern browsers where there is a space between tabs and the actual content.
I've created a unit test to validate the base functionality and all other unit tests pass. Currently, there is no example for the docs, but the visual implications are zero, If the ``RenderFragment`` is not set, there is no change in the DOM for the existing tabs.

adding pre panel rendering to tabs

---

src/MudBlazor/Components/Picker/MudPicker.razor.cs

In my opinion, the `AllowKeyboardInput` prop is not necessary. It just changes the appearance of the cursor. We can change the cursor based on `Editable`. See https://github.com/MudBlazor/MudBlazor/discussions/3447
Before:
After:
visually

DatePicker: Obsolete AllowKeyboardInput parameter

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/TestInlineDialog.razor
src/MudBlazor.UnitTests/Components/DialogTests.cs
src/MudBlazor/Components/Dialog/MudDialog.razor.cs

Fixes #3128. Inline dialog should't be opened soon after setting IsVisible property because all other properties may not have been initialized yet, moved to OnAfterRender.
Added unit test. Currently it's ignored like InlineDialog_Should_UpdateIsVisibleOnClose, don't know if CI supports that.
✔️ The PR is submitted to the correct branch (dev).

Dialog: Fix Class, Style and Tag properties ignored in inline dialog

---

src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs

From the context of a `MudSelect<T>` object, there's no way to get the collection of child `MudSelectItem<T>`'s without relying on CSS selectors (which should be treated as an internal implementation detail).
This PR adds a getter to the `MudSelect<T>`'s component API to obtain a read-only collection of the `MudSelectItem<T>`'s contained within.
A unit test for this feature has been added to ensure that the number of options within the component match the test case.

MudSelect: add Items which returns the MudSelectItems

---

src/MudBlazor.Docs.Compiler/DocStrings.cs
src/MudBlazor.Docs/Components/DocsApi.razor
src/MudBlazor.Docs/Models/DocStrings.cs

Fixes #3567. Descriptions of methods are now read from `DocsStrings.generated.cs` like descriptions of properties. The name of the method description field in the `DocsStrings.generated.cs` file is long and ugly, but it works.
I used Selenium to check that all pages in Wasm have the same content as currently in Blazor server side. The used test: https://github.com/MudBlazor/MudBlazor/discussions/3595.

API documentation: Add method descriptions on Wasm

---

src/MudBlazor.Docs/Pages/Components/Carousel/CarouselPage.razor
src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselBindingExample.razor
src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselExample.razor
src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselTemplatesExample.razor
src/MudBlazor/Components/Carousel/MudCarousel.razor
src/MudBlazor/Components/Carousel/MudCarousel.razor.cs

In the previous pull request #3463 we deprecated the term "Delimiter" in favour of "Bullet".
I replaced the tests but not the docs.

Docs, Carousel: Replace "Delimiters" with "Bullets"

---

src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomCheckboxExample.razor
src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor

Added a docs example to show how custom handling of checkbox state can be implemented in MudTreeView component, as per issue #2550. A couple of users indicated they'd have found it useful if this was in the docs. 
Documentation only
Hope this is OK folks - my very first PR :)

Docs: added example of custom checkbox handling for MudTreeView (#2550)

---

src/MudBlazor/MudBlazor.csproj
src/MudBlazor/tsconfig.json

Fixes #3537
The project's build system has been modified to output **ES6 compatible JavaScript**, thus producing a reliable solution for the issue detailed in #3537 as well as defending against future possible issues stemming from usage of bleeding edge JavaScript features.
This allows you JavaScript Wizards to continue writing code the way you like it (with modern idioms) while offering an extra layer of protection against browsers with incomplete or absent coverage of your favorite features.

Output ES6 compatible JavaScript to support older browsers

---

src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldNativeInputsExample.razor
src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
src/MudBlazor/Components/Input/MudInput.razor.cs
src/MudBlazor/Enums/InputType.cs

TextField: Add HTML5 input types

---

src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuBorderedExample.razor
src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuColorExample.razor
src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuDenseExample.razor
src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuMarginExample.razor
src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuRoundedExample.razor
src/MudBlazor.Docs/Pages/Components/NavMenu/NavMenuPage.razor
src/MudBlazor.UnitTests/Components/NavMenuTests.cs
src/MudBlazor/Components/NavMenu/MudNavMenu.razor.cs
src/MudBlazor/Styles/components/_navmenu.scss

Updated NavMenu to give the users some customization / variant options built in without using any css.
All this was hardcoded before to Primary color when it comes to the active one.
Adds some styling options to MudNavMenu, as a first update.
New features:
To showcase this in a picture i display them all with hover on so you can see the different auto margin options.
Manually when making the examples.

NavMenu: Added color, border, rounded, margin, dense options

---

src/MudBlazor/MudBlazor.csproj

tsconfig.json was showing up in projects consuming the library, causing those projects to error on build. This change stops tsconfig.json from being included in output, which fixes the problem. Build Action remains 'Content' which is required for tsconfig.json.
The PR is submitted to the correct branch (`dev`).

Exclude tsconfig.json from output

---

src/MudBlazor/Components/NumericField/MudNumericField.razor.cs

Fixes #3651 - Numeric field with debounce interval doesn't apply change when the field loses focus.
Update the value before updating the text formatting on losing focus (on blur) of debounced numeric fields.
Unit tests all pass. Also tested via demo in docs.
- No Tests Added

NumericField: Fix not updating value from text on blur when debounced

---

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor.UnitTests/Components/TextFieldTests.cs

FluentAssertions 6.3.0 fixes incorrect use of Equals.
We have a few instances of this incorrect usage
Behaviour change described here https://github.com/fluentassertions/fluentassertions/issues/1705
Run tests

Tests: Fix incorrect use of Equals

---

src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerBasicUsageExample.razor
src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerKeyboardNavigationExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/TimePicker/AutoCompleteTimePickerTest.razor
src/MudBlazor/Components/Picker/MudPicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor.cs

Added a `context` parameter to `PickerActions` to simplify creation of action buttons for pickers without the need to reference the picker itself.
All standard tests apply.
This is how `PickerActions` was used before this PR:
```html
<MudDatePicker @ref="_picker" Label="With action buttons" @bind-Date="date" AutoClose="@autoClose"> // note the usage of @ref
<PickerActions>
<MudButton Class="mr-auto align-self-start" OnClick="@(() => _picker.Clear())">Clear</MudButton> // @ref needed here
<MudButton OnClick="@(() => _picker.Close(false))">Cancel</MudButton> // @ref needed here
<MudButton Color="Color.Primary" OnClick="@(() => _picker.Close())">Ok</MudButton> // @ref needed here
</PickerActions>
</MudDatePicker>
```
After this PR:
```html
<MudDatePicker Label="With action buttons" …
```

Picker: Add 'context' parameter to 'PickerActions' to simplify creation of actions

---

src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs

Added these methods to better control the panel.
Added two unit tests.

ExpansionPanels: Added ExpandAll and CollapseAll methods

---

src/MudBlazor.Docs/Components/DocsApi.razor
src/MudBlazor.Docs/Components/DocsTypeInfo.razor
src/MudBlazor.Docs/Components/EnumSwitch.razor
src/MudBlazor.Docs/Extensions/TypeNameHelper.cs
src/MudBlazor.Docs/Models/DocStrings.cs
src/MudBlazor.UnitTests/Other/CategoryAttributeTests.cs

Examples:   `Int32` changed to `int`, `Nullable<DateTime>` changed to `DateTime?`, and `Converter<Nullable<DateTime>, String>` changed to `Converter<DateTime?, string>`. More info: https://github.com/MudBlazor/MudBlazor/discussions/3520.
The code uses https://github.com/benaadams/Ben.Demystifier/blob/main/src/Ben.Demystifier/TypeNameHelper.cs (Apache License). The speed of new and old method is the same. I tested automatically each page, and then I tested manually the differences: all changes are correct except of type of `MudDialogInstance.Close(T returnValue)` method parameter, but it isn't important.
- The `Properties`, `EventCallbacks`, and `Methods` properties were called respectively: 4, 6, and 6 times per one page, but should be only once which will speeds up the code **about two …

Docs API: Shorter string representation of types, faster code, and other smaller changes

---

src/MudBlazor.Docs/Styles/pages/_landingpage.scss
src/MudBlazor.Docs/Theme/Theme.cs

Fixes gradients of apps on the landing page in firefox
Firefox (Left before / right after):
Chrome (Left before / right after)

Landing page: Fix gradients of apps in firefox

---

src/MudBlazor.Docs.Client/wwwroot/index.html

Hot reload was blocked by content security policy
Made the change.
cd .\src\MudBlazor.Docs.Client\
dotnet watch
Hot reload now works 😄 
https://user-images.githubusercontent.com/16208742/149388268-b76a21be-7a8a-42b7-8791-7feaefdca9b4.mov

Build: Allow hot reload to connect via web sockets

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectTest1.razor
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs

Fixes #3469. Added missing base call in select OnBlur event.
https://user-images.githubusercontent.com/78308169/145673732-65837ed8-c3b2-47fd-bf69-c97ba2cbb7f7.mp4

Select: OnBlur Fix

---

src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectCustomConverterExample.razor
src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectVariantsExample.razor
src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
src/MudBlazor.UnitTests/Components/SelectTests.cs

This is necessary because Stackoverflow is full with questions about how to use Select. Also our Pizza example was misleading because it did not implement the overrides. 
- Added a note to the select page about custom types that they need to override Equals, GetHashCode and ToString. 
- Added a good example of that in the first example so it is guaranteed **not** to be overlooked.
Also fix test regression introduced by #3531

Docs: Better examples how to use MudSelect with custom types

---

src/MudBlazor.UnitTests/Components/DialogTests.cs
src/MudBlazor/Components/Dialog/MudDialog.razor.cs

Revert regression by PR #3252
Fixes #3701
The intended improvement by #3252 will have to be implemented differently, I don't know yet what exactly the problem is/was that prompted the code change.

Dialog: reverting regression by #3252. Issue #3701

---

src/MudBlazor/Styles/components/_table.scss

Fixes #698
CSS changes for `MudTable` that adjust pager element styling to improve vertical centering.
Tested visually with existing test components.
Before:
After:

MudTable: Align pager elements vertically

---

src/MudBlazor/Styles/components/_breadcrumbs.scss

`MudBreadcrumbs`: This re-introduces spacing between icon and text, as it appears that the selector `.mud-breadcrumb-item > a > svg.mud-svg-icon-root` in `_breadcrumbs.scss` was invalid.
This also vertically aligns the icon and text.
Tested visually, see before/after below.
Before:
After:

Breadcrumbs: Adjust icon spacing, vertically center

---

src/MudBlazor/Styles/components/_table.scss

A little add-on to  #3774, noticed that the left caption was also not centered vertically. Turns out one of the classes had `align-items: center;` but needed `display: flex;`, after adding that, the `margin-top` from `.mud-table-pagination-information` could be removed.
Sorry to re-visit this again :grin: but I thought I'd try my best to fully resolve this while I am paying attention to it.
This just leaves the number select about 2px down from center, but, I can't see a good way to resolve that in a way that doesn't implicitly depend on the font size, and also without un-centering the chevron.
Visually, see screenshot below. Changed "Rows" to "R0ws" via browser inspector just to give a better frame of reference.

MudTable, MudDataGrid: Center pager caption text

---

src/MudBlazor.Docs.Compiler/DocStrings.cs

Until now all XML tags were removed from the documentation of properties and event handlers before displaying on the API documentation pages. This PR displays important information contained in the `<see cref="..." />` tags.
It fixes description of the following properties:
MudCarousel.BulletsColor
MudDrawer.OpenMiniOnHover
MudDrawer.PreserveOpenState
MudInput.HideSpinButtons
MudTable.HeaderContent
MudTable.FooterContent
and the following event handlers:
MudInput.OnDecrement
MudInput.OnIncrement
Fixes #3770.
Tested automatically using https://github.com/MudBlazor/MudBlazor/discussions/3595.

Docs API: Add information from <see cref="..." /> tags

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormIsTouchedNestedTest.razor
src/MudBlazor.UnitTests/Components/FormTests.cs

MudForm: Add bool parameter override for ResetForm to not call EvaluateForm if user chooses
Regression fix for forcing validation on MudForm.Reset() introduced between Version="5.1.5" to Version="6.0.2" was the forcing of validation on MudForm.Reset(). Now with the MudForm.Reset(bool evaluateForm = true) a user can choose the behavior with the default behavior being to EvaluateForm
Unit tested

MudForm: Add bool parameter override for ResetForm 

---

src/MudBlazor/Styles/components/_simpletable.scss

`MudSimpleTable` cell padding is uneven, this PR fixes it.
Changed the component CSS to remove the right padding bias for dense. Removed the `-inline-` too as they are even now.
Fixes #3798 
Visually tested.
Before
After
I've not committed the visual test, the test is just a copy of the try mudblazor of the issue.

Fixed MudSimpleTable uneven horizontal padding

---

src/MudBlazor.Docs/Pages/Components/Badge/Examples/BadgeBasicExample.razor
src/MudBlazor/Components/Badge/MudBadge.razor.cs
src/MudBlazor/Styles/components/_badge.scss

When no color was set or Default Color was used the badge did not have any background color at all.
Added color to the badge if default color is used.
Before:
After:

Badge: Fixed default color

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs

Fixes #2345. When we change datepicker's date with input, date changed, but shown date in popover did not follow the changed date's section and showed the old section.
Added test.
https://user-images.githubusercontent.com/78308169/154761101-85dff69d-b040-4deb-ba96-87fa43350f4d.mp4

DatePicker: Fix editable DatePicker not opening to current date 

---

src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectUsageExample.razor
src/MudBlazor.UnitTests/Mocks/MockScrollServices.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs
src/MudBlazor/Services/Scroll/ScrollManager.cs
src/MudBlazor/TScripts/mudScrollManager.js

fixes #3847
This patch fixes issues with the scroll manager. It correctly selects the current value in a `MudSelect` component. Also it fixes the **Home** and **End** keyboard navigation.
It uses a new implementation of the `scrollToList`. The complex calculations where removed, since an element reference is known an the browser knows the position.
A more general approach to support `Virtualize` within `MudSelect` requires much more rethinking and refactoring. Scrolling to the correct element with Virtualized items is not possible, since the items are not known to MudSelect. However, it is working as before, but just still not scrolling.
I think that should be a new component. I have some ideas here, but this will be part of a separate pull request.
The `MudAutoComplete` component had to …

Select: fix scroll to selected item when list is long

---

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

By default, clicking an autocomplete will select its text contents, which can be annoying when trying to edit portions of the typed text. This PR adds a `DisableSelectOnClick` property that when set to true will disable this behavior.
This has been tested visually. I don't think bunit can test whether a text input is selected or not.

Autocomplete: Add `DisableSelectOnClick` property

---

src/MudBlazor/Components/Mask/MudMask.razor.cs

Fixes #3921 
As described in #3921 above, editing a masked textfield inline in a table is a poor experience. Clicking anywhere in the field will "jump" the cursor to position 0, though the arrow keys could be used to move through the mask. See this try.mudblazor for an example of the issue: https://try.mudblazor.com/snippet/GumQawPkLXPfXone
I believe the click on the textfield causes additional renders to the internal mask, which causes the caret position to be set:
https://github.com/MudBlazor/MudBlazor/blob/dev/src/MudBlazor/Components/Mask/MudMask.razor.cs#L177
From what I can tell, the internal `_caret` is reset back to 0 regardless of the value returned from `OnCaretPositionChanged`: https://github.com/MudBlazor/MudBlazor/blob/dev/src/MudBlazor/Components/Mask/MudMask.razor.cs#L374 …

MudMask: Fix cursor jumping in table inline edit mode.

---

src/MudBlazor.Docs/Pages/Features/Masking/Examples/RegexMaskEmailExample.razor
src/MudBlazor.Docs/Pages/Features/Masking/MaskingPage.razor
src/MudBlazor.UnitTests/Utilities/Mask/RegexMaskEmailTests.cs
src/MudBlazor/Utilities/MaskAlgorithms/RegexMask.cs

Add a predefined Email RegexMask.
Also cleaned up the other predefined RegexMask.
This is a mask discussed in #3937 
Created new unit test in RegexMaskEmailTests.cs

RegexMask: add predefined Email mask

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogRender.razor
src/MudBlazor.UnitTests/Components/DialogTests.cs
src/MudBlazor/Components/Dialog/DialogReference.cs
src/MudBlazor/Components/Dialog/MudDialogProvider.razor
src/MudBlazor/Services/DialogService.cs

A timing issue with opening a MudDialog after another in an async method causes unwanted behaviour.
This is fixed by this PR by rendering only the uncompleted MudDialog tasks.
https://try.mudblazor.com/snippet/wEQwuGbhGNHIKbeT  <- Check Console
```csharp
private async Task ButtonOnClick() 
{
var dialog = DialogService.Show<Dialog1>("Dialog1");
await dialog.Result;
var dialog2 = DialogService.Show<Dialog2>("Dialog2");
await dialog2.Result;
}
```
The first awaiting of dialog.Result causes the second Dialog.Show but without closing the first dialog.
So both dialogs are rendered with the .Add (the first dialog is rendered and initailized again, but without parameters as they are marked as already set by `AreParametersRendered`!). After this the first dialog gets removed from the _dialogs …

MudDialog: Rendering only uncompleted MudDialog tasks

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FieldValidationWithoutRequiredFormTest.razor
src/MudBlazor.UnitTests/Components/FormTests.cs
src/MudBlazor/Base/MudFormComponent.cs

When a field is backed by a state service, the initial render works, the value is then modified, validated and saved in the state. When navigating from and to the same page, the field value can be set by the state first, causing a validation, before the cascading parameter `Form` is affected. As the `Form` is required, the validation crash and shows the following message.
Unit tests have been written.

MudFormComponent : Fix field validation when triggered before a required cascading parameter

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteSyncTest.razor
src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Components/Popover/MudPopover.razor.cs

Fixes #3640.
With `MudAutocomplete` and a non-async `SearchFunc` in server-side Blazor, the popover would not open on initial click, because the popover handler was always already locked (for fragment update) before `OnSearchAsync`  was called. This introduces some minor optimizations which has the side-effect of preventing this issue from occurring.
Tested with local server-side Blazor app, as I don't think this could be reproduced in WASM or, bUnit for that matter.  
I did add a bUnit test for this in any case.
Recording to show behavior after changes, which seems to match the current behavior:

`MudAutoComplete`: Fix initial open with server-side, non-async search

---

src/MudBlazor.UnitTests/Components/ProgressLinearTests.cs
src/MudBlazor/Components/Progress/MudProgressLinear.razor

Re-order elements to render child content after the completed part of the progress bar.
fixes #4072
Tested visually with the progress bar with child content in the samples set to 75% to verify that the progress bar does not hide the text anymore.
Unit test was adjusted to check for changed order.
Before:
After:

MudProgressLinear: Fix completed bar rendering over child text (#4072)

---

src/MudBlazor.UnitTests/Components/ToolTipTests.cs
src/MudBlazor/Components/Tooltip/MudTooltip.razor

I wanted to have the tooltips visible for keyboard users.
And it didn't show up on navigating with a keyboard.
I have visually tested it and edited the tests.
https://user-images.githubusercontent.com/36532695/156384454-7ca69747-778a-4f35-9af7-f0909a312f65.mp4

Added onfocusin, now keyboard users also get the mudtooltip

---

src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor

The style attribute in MudFocusTrap was missing an `@`. So the string Style was used as Style.
Added an `@`
Fixes #4070 
visually

Added missing @ for style in MudFocusTrap

---

src/MudBlazor.UnitTests/Components/PaginationTests.cs
src/MudBlazor/Components/Pagination/MudPagination.razor

Added default English aria-labels for paginator.
Simply added `aria-label` attributes for the paginator buttons and numbers for WCAG compliance. This is discussed in #2233 and #2187. No functional changes.
Manual inspection of test files

Pagination : Add default English aria-labels

---

src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldAdornmentsExample.razor
src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
src/MudBlazor.UnitTests/Components/TimePickerTests.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
src/MudBlazor/Components/Input/MudInput.razor
src/MudBlazor/Components/Input/MudInputAdornment.razor
src/MudBlazor/Components/Input/MudRangeInput.razor
src/MudBlazor/Components/Picker/MudPicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/TextField/MudTextField.razor
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

Added a parameter to the `Adornment` component to handle a label to be used as an `aria-label` when the Adornment is an Icon Button. Also found text in date picker for `aria-labels` and added similar text for the `open date picker` Adornment Button in the date picker.
A step in the progress towards WCAG (accessibility) compliance. This is discussed in #2233 and #2187. The jury is still out on hour to internationalize this. For now the standard found in the `DatePicker` was to use generic English text. There is no functional change, it only addresses accessibility. The Text Field docs page has been updated to implement this in the Adornments section and the Section Header updated to explain it's use. If a `AdornmentLabel` is not used for a button implementation, the `aria-label` will …

Add AriaLabel params for Adornment Buttons for WCAG Standards

---

src/MudBlazor.Docs/Pages/Components/Table/Examples/TableBasicGroupingExample.razor
src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiGroupingExample.razor
src/MudBlazor/Components/Table/MudTable.razor

MudTable Grouping to have support for Virtualization. Currently, Mud table have this feature which was added now for Grouped rows
[Note]  Already create a [PR4022](https://github.com/MudBlazor/MudBlazor/pull/4022) which I have deleted now.  This will follow the proper guidance
Resolves #4008 
Tested Visually 
-  [x] New feature (non-breaking change which adds functionality)
-  [x]  Bug fix (non-breaking change which fixes an issue)

MudTable: Fix to include Virtualiation in a grouped rows (#4008)

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest1.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DatePickerValidationTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerValidationTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Field/FieldTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormIsValidTest3.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/NumericFieldTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectRequiredTest.razor
src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor/Base/MudComponentBase.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
src/MudBlazor/Components/Field/MudField.razor
src/MudBlazor/Components/Input/MudInputLabel.razor
src/MudBlazor/Components/Input/MudInputLabel.razor.cs
src/MudBlazor/Components/InputControl/MudInputControl.razor
src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
src/MudBlazor/Components/NumericField/MudNumericField.razor
src/MudBlazor/Components/Select/MudSelect.razor
src/MudBlazor/Components/TextField/MudTextField.razor

Added responsive handling of field's that include an "id" `UserAttribute` and propagates it to the "for" attribute on the associated label
A step in the progress towards WCAG (accessibility) compliance. This is discussed in #2233 and #2187. There is no functional change, it only improves accessibility. When a field, textField, autocomplete, select, datePicker, daterangepicker includes an HTML attribute for "id" the associated label generates an HTML "for" attribute.
Manually inspected on the following test components with a respective id placed in the tests:
- autocomplete: AutocompleteTest1
- date range picker: DateRangePickerValidationTest
- date picker: DatePickerValidationTest
- field: FieldTest
- numeric field: NumericFieldTest
- select: SelectRequiredTest
- text field: …

Label: added "for" attribute when input "id" attribute is set for WCAG Standards

---

src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerGoToDateExample.razor
src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerMoveToDateExample.razor
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs

We just fixed DatePicker date when dropdown opens in last release. But we have still issues in static picker etc. And i also think we can not cover all possible situations.
So the best way is adding a basic, simple method in API: `MoveToDate`
With this basic version, just called and date scrolls and shows the DatePicker's date (if it not null)
With the overrided version, user can set a date whatever they want and go to this date with or without submitting.
- Can add Today button in picker actions easily,
- Navigate MinDate or MaxDate with one click.
- Can use for possible situations when date changed but the visual did not. So solves all possible visual bugs. (Its not about StateHasChanged because visual is controlled by PickerMonth property) …

DatePicker: Navigate programmatically with GoToDate

---

src/MudBlazor/Components/Select/MudSelect.razor.cs

Fixes #4218. There was a bad code that set _isOpen directly when clicked select's item. We change it to the close menu, so it fires OnClose event properly.

Select: OnClose Fix that not fired when SelectItem clicked

---

src/MudBlazor/Styles/components/_simpletable.scss
src/MudBlazor/Styles/components/_table.scss

This PR fixes a missing top right border radius for MudTable, MudSimpleTable, and presumably MudDataGrid when using the FixedHeader feature.  The issue is initially only present when the scrollbar is not visible however on more extreme border radius settings the table header cell background can be seen with or without the scroll bar.
Demonstrated here.
https://try.mudblazor.com/snippet/QaQmkdFDygPwuJVy
I've applied the equivalent style on `:first-child` to `:last-child` for these components.
visually
Before:
After:

CSS Fix: MudTable and MudSimpleTable missing border radius

---

src/MudBlazor.UnitTests/Components/TimePickerTests.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

If MudTimePicker is editable entering an empty string was considered invalid. This resulted in a error message on screen. This fix allows an empty string to be entered resulting in a null TimeSpan.
Fixes #3121
There was already an unit test testing for entering a empty string. This unit test has been expanded by testing on the error state after conversion from string to TimeSpan?.

MudTimePicker: Fix empty string throwing error (#3121)

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/TimePickerTests.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

Fixes #4271.
Calling Clear() now didn't close picker if AutoClose is false.
And datepicker's AutoClose test misses the [Text] attribute and don't behave like a test, we added it.
https://user-images.githubusercontent.com/78308169/160247847-b95dad9e-d2ad-44e3-b082-3d36dc48fefc.mp4

DatePicker and TimePicker: Clear shouldn't close the picker when AutoClose is false

---

src/MudBlazor/Components/List/MudListItem.razor.cs
src/MudBlazor/Components/Select/MudSelect.razor
src/MudBlazor/Components/Select/MudSelect.razor.cs
src/MudBlazor/Components/Select/MudSelectItem.razor

Fixes #4284.
MudSelect has MudList inside itself, but select and list both have their own onclick implementations. Something deep of the click we have conflicts and select didn't work on touch. So we did:
1. Added OnClickHandlerPreventDefault parameter to MudListItem (not onClickPreventDefault, we prevent Mud code). If its true we bypass the list click code and directly continue with OnClick event.
2. In MudSelect set all ListItems prevent to true (to be sure just work select code)
3. Removed all touch events on select (they caused to fire events twice)
Tested both BSS and WASM
https://user-images.githubusercontent.com/78308169/160392996-9d87d8cb-88d2-43f3-957e-018874345451.mp4

Select: Multiselect Touch Fix

---

src/MudBlazor.Docs.Server/Properties/launchSettings.json
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
src/MudBlazor/Components/Popover/MudPopover.razor.cs

Fixes #4303.
First of all this is the not final solution about this issue. There is really a deeper bug when occures complex things happened.
I believe this bug is about timing. So we can fix it with control event timing.
So;
1. Added `ontouchend` event both list item and overlay in autocomplete. I don't know the exact reason, but ontouchend fires before onclick and helps the timing problem.
2. You can ask why we didn't use ontouchstart. Because if we use touchstart, it fires first and closes the popover in autocomplete. And then click event starts and if there is something behind the popover, clicks it. We don't want this.
3. The only problem about touchend is calling same method twice with click event. So we checked the touch event and if user touches the component, the code understand …

Autocomplete: Fix menu staying open on BSS and mobiles

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTestRequiredValue.razor
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs

Fixes #4328
MudSelect When Required=true and MultiSelection=true Required Value check now works. Fixed by overriding `HasValue` method in MudSelect.
Test Added To SelectTests
`MultiSelectWithRequiredValue`

Select: Required now also works when MultiSelection="true" (#4328, #4346)

---

src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor
src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxBasicExample.razor
src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxColorExample.razor
src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioGroupColorExample.razor
src/MudBlazor.Docs/Pages/Components/Radio/RadioPage.razor
src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchColorExample.razor
src/MudBlazor.Docs/Pages/Components/Switch/SwitchPage.razor
src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
src/MudBlazor.UnitTests/Components/SwitchTests.cs
src/MudBlazor/Components/Button/MudIconButton.razor.cs
src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
src/MudBlazor/Components/Radio/MudRadio.razor.cs
src/MudBlazor/Components/Switch/MudSwitch.razor
src/MudBlazor/Components/Switch/MudSwitch.razor.cs
src/MudBlazor/Styles/abstracts/_colors.scss
src/MudBlazor/Styles/components/_buttongroup.scss
src/MudBlazor/Styles/components/_checkbox.scss
src/MudBlazor/Styles/components/_iconbutton.scss
src/MudBlazor/Styles/components/_switch.scss

Added parameter to control the "`UnCheckedColor`" of `MudCheckBox`, `MudSwitch` and `MudRadio` i took the opportunity to kickstart the CSS class cleanup and removed all component specific color classes and instead use the provided CSS utility theme classes.
This could be done before by simply changing the Color of the component by the users but not for `MudSwitch` so i decided to add it to `MudCheckBoix `and `MudRadio `as well to streamline the form/input components.
To not break things `UnCheckedColor` is null by default for `MudCheckBox` and `MudRadio` but set to `Color.Default` for `MudSwitch`.
fixes #4340
Visual/manually in docs.
Tests are coming...

CheckBox, Radio, Switch: UnCheckedColor and CSS cleanup

---

src/MudBlazor/Styles/components/_popover.scss
src/MudBlazor/Styles/components/_tooltip.scss

I noticed some weird behaviour that prevents clicking or triggering the hover state on some parts of elements only.
I boiled it down to some tooltip's invisible elements (`<div id="popovercontent-[id]">`) that are always on top of other elements sometimes.
This is frustrating for users as it happens that some 5% of the times one of the clickable elements (that randomly has this popover invisible on top) is clicked, the app does nothing so the final app seems unresponsive for no reason.
Fixes  #4345
This is a CSS only fix, it was tested in the browser, as per the screenshots below, it can be seen that the rectangle does not block the button any more.
It's hard to depict in pictures but the invisible square can be seen when inspecting the element in chrome:
And after the fix (I was hovering …

MudTooltip - removed invisible overlay rectangle when not visible

---

src/MudBlazor.Docs/Pages/Components/List/Examples/ListColorExample.razor
src/MudBlazor.Docs/Pages/Components/List/ListPage.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListSelectionInitialValueTest.razor
src/MudBlazor.UnitTests/Components/ListTests.cs
src/MudBlazor/Components/List/MudList.razor.cs
src/MudBlazor/Components/List/MudListItem.razor
src/MudBlazor/Components/List/MudListItem.razor.cs
src/MudBlazor/Styles/components/_select.scss

I remade @mckaragoz PR #4329 as it broke the hover and had wrong selected color by default. But mostly i did it to implement the usage the utility classes instead of adding more component specific CSS that we already have.
The docs Example is copied from @mckaragoz PR.
Also fixes a null issue with MudListItem when using Nested list and no parent List is present.
@mckaragoz sorry that i highjacked your PR but after i reviewed it and tested it, it was just so much faster for me to do it myself than show you/explain, please take your time and see what i did differently and especially for the ColorTest i added.
unit | visually

List: Added selected color & fixed parent null issue

---

src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorExample2.razor
src/MudBlazor.UnitTests/Components/MenuTests.cs
src/MudBlazor/Components/Menu/MudMenu.razor
src/MudBlazor/Components/Menu/MudMenu.razor.cs

Inconsistent MouseEvent/MouseLeave event handler causes flickering (destroys element and recreates) while the mouse moves between menu and popover,
note the _isMouseOver is not set when entering the menu
All tests passed

Menu: Fix MouseEnter/MouseLeave event handler inconsistency

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest7.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/TableContext.cs

This fixes #3320. See this comment on that issue for more details on the results of the bug: https://github.com/MudBlazor/MudBlazor/issues/3320#issuecomment-1067634856
This is due to how the TableContext handles subscribing and disposing of table row instances. In short, the issue resulted because rows are disposed after their replacements are subscribed. This PR adds a check to ensure the `MudTr` passed to the `Remove` method on `TableContext` is indeed the instance currently stored in the Rows dictionary.
Unit tests + manually.

Table: Fix check-all not selecting all items after filtering in multiselect mode.

---

src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsContentExample.razor
src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
src/MudBlazor/Components/Tabs/MudTabPanel.razor
src/MudBlazor/Components/Tabs/MudTabs.razor

As discussed in #3913 and #4015, the existing "embedded" tooltip of the MudTabs component is limited as it is impossible to specify properties for the Tooltip, such as color. This PR is a demo/test of a possible solution to this problem that provides a `TabContent` render fragment on each `MudTabPanel`, which is rendered accordingly by the parent `MudTab` component if it exists.
This is the solution originally proposed by @Garderoben https://github.com/MudBlazor/MudBlazor/pull/3913#issuecomment-1036982747
This is a breaking change as it makes the existing `Tooltip` property obsolete and any text provided to this property will be ignored.
Other components that similarly use tooltips may need similar changes for consistency.
This has been tested visually thus far, tests will ultimately need …

Tooltip: Add TabContent render fragment to MudTabPanel

---

src/MudBlazor/Components/InputControl/MudInputControl.razor
src/MudBlazor/Styles/components/_navmenu.scss

Fixed the border style alignment of the NavMenu
Border style was set to right edge by using 
`border-right-style: solid; border-right-width: 2px;`
It's now fixed by using inline styles of the border:
`border-inline-end-style: solid; border-inline-end-width: 2px;`
visually
Before: 
After:

NavMenu: Fix border stle for RTL layout

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Button/IconButtonTest.razor
src/MudBlazor.UnitTests/Components/ButtonsTests.cs
src/MudBlazor.UnitTests/Components/ToggleIconButtonTest.cs
src/MudBlazor/Components/Button/MudFab.razor
src/MudBlazor/Components/Button/MudFab.razor.cs
src/MudBlazor/Components/Button/MudIconButton.razor

Add and fixes the Title property for Icons.
Fixes issue #2818 and adds the Title property to MudFab.
The affected components are:
- MudFab
- MudIconButton (and all components that rely on it, passing a Title property)
- MudToggleIconButton
Update unit tests to look for the title property on the button tag instead of the SVG, as well as visually.

Fix Title property for MudIconButton

---

src/MudBlazor.UnitTests/Components/PopoverTests.cs
src/MudBlazor/Components/Popover/MudPopoverProvider.razor
src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
src/MudBlazor/Components/Popover/MudPopoverService.cs
src/MudBlazor/Components/Render/MudRender.razor
src/MudBlazor/TScripts/mudPopover.js

Recursive popovers caused infinite render loop because the popup provider did re-render all popups when only a single popup requested to be re-rendered due to a fragment update. This could be seen in the dev.4 nuget or on https://dev.mudblazor.com/components/popover#popover-inception before this PR is merged.
The solution was to encapsulate every popup that is rendered as child of the popupprovider in a `<MudRender>` which is a new component with the sole purpose of allowing us to keep an element reference to it and force a render of only that popup when its fragment changed without re-rendering the entire popup provider and the other popups. 
Caused by #4375 which fixes a bug that did mask this bug. 
Manual

Popover: fix endless render loop for recursive popups

---

src/MudBlazor/Services/ResizeListener/BreakpointService .cs
src/MudBlazor/Services/ResizeListener/ResizeBasedService.cs

In a project, I recently encountered an issue regarding MudHidden. 
Currently, the code looks like
```csharp
var existingOptionId = Listeners.Where(x => x.Value.Option == options).Select(x => x.Key).FirstOrDefault();
try
{
await _semaphore.WaitAsync();
...calling js and do other stuff
}
finally
{
_semaphore.Release();
}
```
Because the ``existingOptionId`` is read before entering the semaphore (and there is another semaphore for removing items from the dictionary ``Listeners`` it creates a condition where the option id once valid is invalid at the time, the value is read from the dictionary. Therefore the ``<MudHidden>`` relying on the service will fail with a message like
I've restructured the service a bit. Firstly, there is only one semaphore for both subscribing (adding to the …

BreakpointService: Fix race condition causing invalid state

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs

Resolves visual issue with Date Picker when using Fixed Values.
It was pointed out by @Garderoben  in #2990
PR contains the key part of #3490 without adding any new parameters.
Instead of hiding these displays alltogether, it is just made impossible to switch to those views (For example, the button click does not do the action
Unit  test were adapted to reflect the changed visuals
Manual visual tests were done.
It is 100% non breaking, because the fixed values feature is not yet released.
Before (dev) 
After (PR)

DatePicker: Fixed Values - Don't hide year / date in toolbar

---

src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

I noticed an odd error when clearing an autocomplete in `OnParametersSetAsync` that was coming from within the Mudblazor.dll. I investigated the source and it looks like the `_elementReference` can be null when `Clear` is called, which results in a `NullReferenceException`. 
All existing tests pass as expected.

Autocomplete: Ensure _elementReference is not null when Clear() is called.

---

src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs

Disconnect event handlers in Dispose method of MudDialogProvider.
This fixes a problem that dialogs do not close when using multiple layouts within an application.  When using multiple layouts and at least one includes <MudDialogProvider/> then multiple instances of MudDialogProvider are created during the lifetime of the app.  Previously these instances weren't being disposed correctly which is what causes the issue.
Fixes #4508
Tested with MudBlazor app on local system.

MudDialog: Fix dialog not closing when using multiple layouts (#4508)

---

src/MudBlazor.UnitTests/Components/MaskTests .cs
src/MudBlazor/Components/Mask/MudMask.razor.cs

Fixed missing functionality on mudTextfield with mask and ctrl+backspace shortcut.
Issue fix #4510 
Unit Test added + visible on docs

MudMask: Ctrl+Backspace clears textfield #4510

---

src/MudBlazor/Components/Select/MudSelect.razor.cs
src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs

This fixes #4060, the problem is caused by the transient `KeyInterceptor` holding a reference to the component via the `KeyUp/Down` events.
Since it is not disposed until the scope is also disposed, and the scope is disposed when the Blazor connection is, rather than the page, it hangs around and can't be collected.
Tested manually, using https://github.com/lachlanwgordon/MudBlazorMemoryLeakRepro and triggering a GC to confirm.
I don't know how to test this automatically, so have not added a unit test.

Select: Fix memory leak caused by key interceptor (#4060)

---

src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneCanDropTest.razor
src/MudBlazor.UnitTests/Components/DropZoneTests.cs
src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs

This sets the _transaction to null in MudDropContainer.CommitTransaction and MudDropContainer.CancelTransaction before the TransactionEnded event is fired. This is changed because if the component is re-rendered, there is still an active transaction, but _canDrop is set to false by the handler method MudDropZone.Container_TransactionEnded (if ApplyDropClassesOnDragStarted is set to true). This is why the NoDrop css classes are getting applied.
Fixes #4516
Visually in the Docs app + new unit test.

MudDropZone: Fix NoDropClass not being removed after drop if ItemDropped handler is executed asynchronously (#4516)

---

src/MudBlazor.UnitTests/Components/DropZoneTests.cs
src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor.cs

Adds check for transaction in progress in DragEnter handler in MudDynamicDropItem.
This fixes a NullReferenceException that is thrown when DragEnter is called by dragging a not tracked item onto MudDynamicDropItem.
Fixes #4506 
Tested with MudBlazor Docs app on local system and added unit test.

MudDropZone: Fix NullReferenceException when dragging not tracked item onto MudDynamicDropItem (#4506)

---

src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneDraggingTestCantDropSecondZoneTest.razor
src/MudBlazor.UnitTests/Components/DropZoneTests.cs
src/MudBlazor/Components/DropZone/MudDropZone.razor.cs

The internal indices were always updated after a drag drop operation. Now they are only updated if the drag drop operation was successful.
Fixes #4311
Visually in the local Docs app and by unit test.

MudDropZone: Fix keeping elements order when you drag one out of the MudDropZone (#4311)

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest6.razor
src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

This PR adds a `<MoreItemsTemplate>` render fragment to the autocomplete. The component has a means of limiting the items displayed but provides no indication to the user that the list of items may be truncated. This PR provides a means of displaying a render fragment in the number of items returned from the `SearchFunc` is greater than the `MaxItems` count.
For example:
```csharp
<MudAutocomplete T="string" Label="US States" @bind-Value="value1" SearchFunc="@Search1"
ResetValueOnEmptyText="@resetValueOnEmptyText"
CoerceText="@coerceText" CoerceValue="@coerceValue" MaxItems="10">
<MoreItemsTemplate>
<MudText Align="Align.Center">
Not all items are shown.
</MudText>
</MoreItemsTemplate>
</MudAutocomplete>
```
My biggest caveat is the items `IEnumerable` must be enumerated twice, once to …

Autocomplete: Add MoreItemsTemplate RenderFragment.

---

src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs

Clicking the overlay on a dialog that has been opened using `Show` may throw an error due to `_dialog` being null.
This is a regression from #4413.
As far as I can tell `_dialog` being null is not a bug, as the `Register` [method](https://github.com/MudBlazor/MudBlazor/blob/dev/src/MudBlazor/Components/Dialog/MudDialog.razor.cs#L198) is only called when using an inline `MudDialog`.
The original error can be reproduced here: https://try.mudblazor.com/snippet/mOcQOJvKVYHXdiox
Manually, and tests pass.

Dialog: Fix error thrown when clicking dialog overlay

---

src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DatePickerStaticTest.razor
src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs

With basic static picker we have no problem. But when static picker has picker actions render fragment, clicking on days has no effect. As a workaround need to add `AutoClose="true"` but autoclose parameter has no sense with static picker.
Before (Date doesn't change on first picker)
https://user-images.githubusercontent.com/78308169/170724404-ea3a7306-0a6c-43d5-8ad6-71360cb06f7c.mp4
After
https://user-images.githubusercontent.com/78308169/170724504-0d61daf3-f38a-41a6-b135-039064b70968.mp4
Unit test added.

DatePicker: Update date when clicking on days in static picker with picker actions

---

src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompletePresentationExtrasExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest7.razor
src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

This PR adds a `NoItemsTemplate` that is shown when no items are returned from the `Search` function. Example:
```csharp
<MudAutocomplete T="Element" Label="Periodic Table Element" @bind-Value="value2"
SearchFunc="@SearchEmpty" ToStringFunc="@(e=> e==null?null : $"{e.Name} ({e.Sign})")"> 
<NoItemsTemplate>
<MudText Align="Align.Center" Class="px-4 py-1">
No items found
</MudText>
</NoItemsTemplate>
</MudAutocomplete>
```
I have also added a docs section for both the `NoItemsTemplate` and the `MoreItemsTemplate` (#4566) render fragments.
This PR additionally closes #4668.
Unit

Autocomplete: Add NoItemsTemplate render fragment

---

src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
src/MudBlazor/Components/MessageBox/MudMessageBox.razor
src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs

MessageBox has a weird behavior before: when you open a messagebox, it still focus on the button which opens messagebox, so when you press enter, it doesn't confirm the messagebox, instead of open a second, third messagebox.
So we simply added a focustrap into messagebox actions, so now when messagebox opens, it directly focus on yes button.
Also we added a cancel option with pressing "Escape".
The left one is old, and the right one is new behavior.
https://user-images.githubusercontent.com/78308169/175053273-7bbb8dce-8f03-4d88-9448-35ecce2d8b59.mp4

MessageBox: Add Keyboard Navigation and Fix Initial Focus

---

src/MudBlazor/Utilities/ExpressionExtensions.cs

`GetFullPathOfMember` under `ExpressionExtensions` is currently internal, meaning it cannot be used for custom `IFormComponent` implementations. This is a very niche usage but I am working on an adaptation of [TinyMCE.Blazor](https://github.com/tinymce/tinymce-blazor) and need the component to implement `IFormComponent` as well as use fluent validation. At present, I must copy this entire extension method in order to use it in my project. The other utilities are public, so I don't think there is a good reason for this one to be internal.
Not applicable

Extensions: Make GetFullPathOfMember method public

---

src/MudBlazor.Docs/Pages/Components/Form/Examples/MudFormExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormFieldChangedTest.razor
src/MudBlazor.UnitTests/Components/FormTests.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Base/MudBooleanInput.cs
src/MudBlazor/Base/MudFormComponent.cs
src/MudBlazor/Components/DataGrid/DataGridRowValidator.cs
src/MudBlazor/Components/Form/MudForm.razor.cs
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
src/MudBlazor/Components/Table/TableRowValidator.cs
src/MudBlazor/Interfaces/IForm.cs
src/MudBlazor/Utilities/FormFieldChangedEventArgs.cs

This PR adds a `FieldChanged` event to the MudForm. Example usage:
```csharp
<MudForm FieldChanged=@((e) => Console.WriteLine($"Value changed: {e.NewValue}. Component type: {e.Field}"))>
<MudTextField T="string" Label="Username" Required="true" RequiredError="User name is required!"/>
</MudForm>
```
It will fire whenever a `MudFormComponent` value changes. I believe I have accounted for all components which inherit `MudFormComponent`.
A few caveats:
* The Rating and Slider components do not inherit from `MudFormComponent` and are not covered by this PR.
* I needed to modify `IForm`, which means the `FieldChanged` method of that interface is ignored in the Table validators which inherit `IForm`. However, this was already the case for the `Update` method.
One potential issue: MudTextFields …

MudForm: Add FieldChanged event

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteAdornmentChange.razor
src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

The adornment icon of the autocomplete doesn't change after the initial render until said autocomplete is opened or closed.
I simply changed the field used in background to a property, so that every render will get the proper icon no matter what.
I added a unit test to validate the bug and tested manually too.

Bugfix autocomplete when changing adornment icon

---

src/MudBlazor/Services/JsEvent/JsEvent.cs
src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs

This resolves the issue discussed in #4565. What I have done is added a check on `_isDisposed` in both `JSEvent.cs` and `KeyInterceptor.cs` before `Connect` and `Subscribe` calls. I additionally caught all `JSException`s on KeyInterceptor as the `_isDisposed` check was insufficient to stop the error in #4565.
I think this a clean way of handling this edge case.
All existing tests pass and the issue in #4565 is resolved.

MudMask: Fix crash when navigating quickly on a page containing a mask

---

src/MudBlazor.Docs/Pages/Mud/Project/Releases.razor

Before:
After:
I tried my best regex skills (ie copy/pasting from stackoverflow 😂)

Docs: fix links in Releases page

---

src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerDataQuickFilterTest.razor
src/MudBlazor.UnitTests/Components/DataGridTests.cs
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs

Fixed the issue with ServerData not been filtered properly.
Renamed name of variable, from `n` to `page` to give it more semantic meaning.
Also fixed some whitespaces.
Note: This isn't fixing the issue with multiple QuickFilters been executed multiple times. I will take a look in the future.

DataGrid - QuickFilter in GetItemsOfPage

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Mask/ReadonlyMaskedTextFieldTest.razor
src/MudBlazor.UnitTests/Components/MaskTests .cs
src/MudBlazor/Components/Mask/MudMask.razor.cs

MudTextField with mask should respect Readonly property.
If readonly is true, no paste/keyboard backspace events should work.
Problem seems to be located inside MudMask, some events do not check Readonly value.
fixes #4866.
unit

MudTextField with mask should respect Readonly property

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableContextRecordTest.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTrWithValue.cs
src/MudBlazor/Components/Table/TableContext.cs

Resolves #4691 and #4904 (duplicate).
Record types would break various table functions as identical records would be treated at the same object by the TableContext Dictionary. This PR resolves this by using a HashSet of records that uses both the T value and the MudTr row to determine equality.
All existing tests pass. I could duplicate a handful of the existing tests and replace the class type with record types to specifically test records, but the existing tests cover the replacement of the Dictionary with a HashSet.

Table: Fix KeyNotFoundException with records in MudTable

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogToggleFullscreen.razor
src/MudBlazor.UnitTests/Components/DialogTests.cs
src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs

fixes #4860.
Error seems to be caused by recursively computing the Class property of the MudDialogInstance through the CssBuilder,
which causes the different classes generated by the options to accumulate one after one indefinitely.
Added a unit test based on the example exposed by @wrkntwrkn in #4860.
unit

MudDialog fullscreen/window toggle error

---

src/MudBlazor.UnitTests/Components/DatePickerTests.cs
src/MudBlazor.UnitTests/Components/TimePickerTests.cs
src/MudBlazor/Components/Picker/MudPicker.razor
src/MudBlazor/Components/Picker/MudPicker.razor.cs

This PR adds a clear button to the various MudPickers for consistency with the rest of the library.
**However, this makes it possible to clear a Readonly Picker.** Is this desired behavior?
Visually, I can add a unit test if necessary.
An example from the Basic Usage section of the Date Picker docs page:
When empty, the clear button is not shown:
It also works for the time picker and color picker:

MudPicker: Add clear button

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormResetTest.razor
src/MudBlazor.UnitTests/Components/FormTests.cs
src/MudBlazor/Components/Picker/MudPicker.razor.cs

Resolves #3852. Calling Form.Reset() does not clear the values of pickers within the form. See: https://try.mudblazor.com/snippet/GkmmYBQrpNSDdMnz
I am adding a unit test.

MudPicker: Value should reset when Form.Reset() is called.

---

src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
src/MudBlazor/Utilities/BindingConverters/DefaultConverter.cs

Fixes #4945
By default `int.TryParse` (and others) do not accept the thousands separator where float/double do accept them, I think we should have parity between them.
Manually

DefaultConverter: Add AllowThousands flag to all integer type TryParse calls

---

src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
src/MudBlazor/Components/NumericField/MudNumericField.razor.cs

Fix decimal precision and overflows when using increment / decrement
To resolve issue #4971
Added support to handle Decimal differently as it has support more precision with bigger numbers, but we must keep double as default since of the floating precision of double.
Resolved unhandled exceptions when "stepping" up a value above or below the MIN/MAX value of the primitive data type
New units tests has been added to verify the changes

 NumericField: Fix decimal precision and overflows

---

src/MudBlazor/Components/Dialog/DialogReference.cs
src/MudBlazor/Components/Dialog/IDialogReference.cs
src/MudBlazor/Interfaces/IDialogService.cs
src/MudBlazor/Services/DialogService.cs

Fixes #4822
Few notes:
I have added annotation for both `IDialogService` and `DialogService`. This might sound counterintuitive, but if you only mark your implementation with `DynamicallyAccessedMembers` and will use an interface that doesn't have it, then your type will be trimmed. This works vice-versa, if you mark your interface, but someone will cast it to the implantation class and call a method that doesn't have it, your type will get trimmed. At this point, the trimming analyzer is really dummy, so I played it safe and put it everywhere.
I did some cosmetic changes. Also, I removed default parameters for this signature
```CSharp
IDialogReference Show<TComponent>(string title, DialogParameters parameters = null, DialogOptions options = null) where TComponent : ComponentBase;
``` …

DialogService: Fix for trimming

---

src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj

Resolves #5019.
I still think that Docs shouldn't be published as trimmed to production since it uses a lot of reflection, but if it's someone's use case, then we should disable `System.AggressiveAttributeTrimming`, because Docs relies on `System.ObsoleteAttribute` for documentation.
Disabling `AggressiveAttributeTrimming` in `MudBlazor.Docs.Wasm` also influences `MudBlazor.Docs.WasmHost`.
The rest technical description is in the issue ticket.
Compiling with `PublishTrimmed` and checking the docs visually.

Disable AggressiveAttributeTrimming for MudBlazor.Docs.Wasm

---

src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest1.razor
src/MudBlazor.UnitTests/Components/RadioTests.cs
src/MudBlazor/Components/Radio/MudRadioGroup.razor
src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs

Fixes #4916.
With #4084, class and style parameters moved to another element in the component. Now we added extra InputClass and and InputStyle parameters the previous place.
So if a user already had their custom classes or styles (if its about flex or etc), only need change:
Class => InputClass
Style => InputStyle
The upper radiogroup has Class and below radiogroup has InputClass `d-flex justify-space-between`

RadioGroup: Add InputClass and InputStyle for backward compatibility

---

src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs

I added the `KeyboardEnabled` bool parameter to MudCheckBox that, when false, disabled the keyboard controls established in  #2929. 
It is tested with a unit test, deriving off of the keyboard unit test.

CheckBox: Add ability to disable keyboard input

---

src/MudBlazor.UnitTests/Services/IIJSRuntimeExtentionsTests.cs
src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
src/MudBlazor/Components/Popover/MudPopoverService.cs
src/MudBlazor/Services/EventManager/EventManager.cs
src/MudBlazor/Services/IIJSRuntimeExtentions.cs
src/MudBlazor/Services/JsEvent/JsEvent.cs
src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
src/MudBlazor/Services/ReseizeObserver/ResizeObserver.cs
src/MudBlazor/Services/ResizeListener/BreakpointService .cs
src/MudBlazor/Services/ResizeListener/ResizeBasedService.cs
src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
src/MudBlazor/Services/ResizeListener/ResizeService.cs
src/MudBlazor/Services/Scroll/ScrollListener.cs
src/MudBlazor/Services/Scroll/ScrollSpy.cs

Before this PR, each service handled exceptions for JS interop separately. This PR tries to start the process of centralizing it and providing a single point for future changes. 
There have been two options for the implementation: Either the creation of a new service or extension methods. For service, I need to create it and wrap the calls, announce it to the DI container and replace ``IJSRuntime`` throughout the library with this new service.  With the Extention method approach, I still need to write the wrapper, but that's about it. Besides, users can use this method more quickly and effectively in their own code. 
The wrapper itself is quite simple
```csharp
try
{
await jsRuntime.InvokeVoidAsync(identifier, args);
return true;
}
catch (JSException)
{
return false;
}
catch …
```

JsInteropSerivce: Centralizing JS error handling part one

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest5.razor
src/MudBlazor.UnitTests/Components/SelectTests.cs
src/MudBlazor/Components/Select/MudSelect.razor.cs

fixes #4848.
The MudSelect attributes are set in the same order as they are processed.
```razor
<MudSelect T="string" SelectedValues="SelectedValues" MultiSelection="true">
```
In this case (as noted in associated issue #4848), the SelectedValues setter sets the text when the MultiSelection attribute is still false.
This fix makes sure that MultiSelection property setter updates the text if needed.
unit

Select: Update Text when switching to MultiSelection

---

src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTablePager.razor

Added default English aria-labels for TablePager.
Simply added aria-label attributes for the table pager buttons for WCAG compliance. The changes made were basically the same as the changes that were made to the Pagination component in the [4120](https://github.com/MudBlazor/MudBlazor/pull/4120) pull request.
Manual inspection of test files

TablePager: Add default English aria-labels

---

src/MudBlazor.UnitTests/Components/DataGridTests.cs
src/MudBlazor/Components/DataGrid/FilterDefinition.cs

Change expression builder in order to use efcore to filter DataGrid with Types bool, DateTime and numbers.
Currently with those types EFcore retrun an error.
see (https://github.com/MudBlazor/MudBlazor/issues/5126 ) 
original PR(#5137)

 DataGrid: Change expression builder for nullables bool, DateTime and numbers Type (#5126) 

---

src/MudBlazor/Components/DataGrid/MudDataGridPager.razor
src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs

Added functionality to disable user interaction with `MudDataGridPager`. I have added a new `Disabled` property to `MudDataGridPager` which, when set to `true`, disables user interaction with the backward/forward buttons and the part of the pager which allows the user to change the page size. This is a useful setting to prevent users from changing pages at unintended times (for example, while data is already being retrieved from the server for a previous page request).
resolves #4984
Tested visually. There are no existing Unit Tests for the MudDataGridPager component, so I did not add or modify any.

DataGrid: Added functionality to disable user interaction with MudDataGridPager

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverDuplicationTest.razor
src/MudBlazor.UnitTests/Components/PopoverTests.cs
src/MudBlazor.UnitTests/Mocks/MockPopoverService.cs
src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
src/MudBlazor/Components/Popover/MudPopoverService.cs
src/MudBlazor/Components/Popover/PopoverOptions.cs
src/MudBlazor/TScripts/mudPopover.js

resolves #5064
Adding multiple `MudPopoverProviders` can lead to issues such as #5064. This PR will check for duplicate `.mud-popover-provider` tags and throw an error if two or more are found. This feature can be disabled with `PopoverOptions.ThrowOnDuplicateProvider`.
Tested manually.

PopoverProvider: Throw exception when duplicate providers detected

---

src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridColumnCultureExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCultureEditableTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCultureSimpleTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCulturesTest.razor
src/MudBlazor.UnitTests/Components/DataGridTests.cs
src/MudBlazor/Components/DataGrid/Column.cs
src/MudBlazor/Components/DataGrid/Filter.razor
src/MudBlazor/Components/DataGrid/Filter.razor.cs
src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
src/MudBlazor/Components/DataGrid/MudDataGrid.razor
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs

resolves #5138.
Adds a culture property to DataGrid.Column,
to allow specific formatting settings by each column.
This property is used for displaying/editing numbers in the datagrid body
and in the filtering inputs.
unit

DataGrid: Add Culture property to DataGrid Column

---

src/MudBlazor/Styles/components/_switch.scss
src/MudBlazor/Styles/components/_treeview.scss

Conflict with .mud-treeview-item .mud-icon-button {
padding: 4px;
}

Treeview: Fix conflicting iconbutton css selectors

---

src/MudBlazor.UnitTests/Components/DataGridTests.cs
src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
src/MudBlazor/Components/DataGrid/MudDataGrid.razor
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs

fixes #4743.
When DataGrid's SetSortAsync is called directly (not from the headerCell events),
Header indicator direction is not updated correctly.
This changes propagates the dataGrid's current sort definitions to all headers indicators, through a new headerCell SortDirection property (bound to current _initialDirection variable).
unit

DataGrid: Update sort indicator from SetSortAsync

---

src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerContainerTest1.razor
src/MudBlazor.UnitTests/Components/DrawerTest.cs
src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs

When a MudDrawer is shown, classes are added to its container to make space for it.  If the Drawer is removed from the page (not just closed) the classes are left behind.
This can be a problem if you have a layout component that includes MudLayout, and some pages with Drawers and some pages without.  When navigating from a page with a Drawer to a page without a Drawer, classes are left behind making space for a drawer that doesn't exist.
The fix is simply to call StateHasChanged after removing a MudDrawer from a MudDrawerContainer.  This updates the classes.
Fixes #4363
Added a new unit test.
Tested in my local project.

MudDrawerContainer: Call StateHasChanged after removing Drawer to ensure classes are updated (#4363)

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionVirtualizedTest.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTable.razor

fixes #5190
Really simple fix that makes MudTr preserve checked state when virtualized.
unit

MudTable: Preserve checked state when virtualized and MultiSelection="true"

---

src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterUntilNextBoundaryExample.razor
src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithCustomStyleExample.razor
src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithListExample.razor
src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithListMultipleExample.razor
src/MudBlazor.Docs/Pages/Components/Highlighter/HighlighterPage.razor
src/MudBlazor.UnitTests/Components/HighlighterTests.cs
src/MudBlazor/Components/Highlighter/MudHighlighter.razor
src/MudBlazor/Components/Highlighter/MudHighlighter.razor.cs
src/MudBlazor/Components/Highlighter/Splitter.cs

Resolves #4621 and resolves #3129.
Currently `MudHighlighter` can only highlight a single fragment of text.
This PR adds support to highlight multiple fragments by adding an enumerable property, which comes in handy when implementing multiple-word search features on pages.
Additionally, in the second commit (so in case you don't want it, you can exclude it easily from the PR) I avoided some simple allocations in the `MudHighlighter` type.
I implemented additional unit cases in `HighlighterTests.cs` file.
API change:
```diff
public partial class MudHighlighter
{
+    /// <summary>
+    /// The fragments of text to be highlighted
+    /// </summary>
+    [Parameter] 
+    [Category(CategoryTypes.Highlighter.Behavior)]
+    public IEnumerable<string> HighlightedTexts { get; set; }
}
``` …

MudHighlighter: Support multiple highligted texts

---

src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs

fixes #5280.
It adds 'mud-width-full' to autocomplete container div when MudBaseInput.FullWidth == true
unit

MudAutocomplete: Fix FullWidth

---

src/MudBlazor.Docs/Pages/Components/Form/Examples/LabelAttributeExample.razor
src/MudBlazor.Docs/Pages/Components/Form/FormPage.razor
src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
src/MudBlazor.UnitTests/Components/PickerTests.cs
src/MudBlazor.UnitTests/Components/SwitchTests.cs
src/MudBlazor.UnitTests/Components/TextFieldTests.cs
src/MudBlazor.UnitTests/Extensions/ExpressionExtensionsTests.cs
src/MudBlazor.UnitTests/Utilities/DisplayNameLabelClass.cs
src/MudBlazor/Attributes/LabelAttribute.cs
src/MudBlazor/Base/MudBaseInput.cs
src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/Switch/MudSwitch.razor.cs
src/MudBlazor/Extensions/ExpressionExtensions.cs

As pointed out in the discussion on #5225, using the `[Display]` attribute to generate form inputs automatically may have side effects and controlling this setting globally is infeasible at this time. The solution is a custom `[Label]` attribute that will not interfere with other uses of `[Display]`.
Unit tests updated

MudForm: Add LabelAttribute to replace DisplayAttribute

---

src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor

- Added the DialogFocusExample_Dialog, so users have it easier to see how to use the property.
- Centered the Open Dialog button, to keep all buttons the same
- Formatted the DialogPage, to keep code formating uniform
Visually

Docs: Add page tab to dialog focus trap example

---

src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridFilteringExample.razor
src/MudBlazor.UnitTests/Components/DataGridTests.cs
src/MudBlazor/Components/DataGrid/DataGridFilterCaseSensitivity.cs
src/MudBlazor/Components/DataGrid/FilterDefinition.cs
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs

This pull request add the possibility to define the case sensitivity when filtering string values. I have added the parameter FilterCaseSensitivity to the MudDataGrid to do so. The default behavior is not changed.
It is been tested updating existing unit tests and visually.

MudDataGrid: Added the case sensitivity when filtering string columns

---

src/MudBlazor/Components/Table/MudTable.razor
src/MudBlazor/Components/Table/MudTablePager.razor

In the vein of #5370, this issue prevents a `MudForm` containing a `MudTable` from validating the internal `MudSelect` components. Marking them as `Standalone=false` will disable all validation behavior and prevent "For is null" errors.
Existing test still pass.

MudTable: Wrap internal MudSelect in Standalone=false cascading value

---

src/MudBlazor.Docs/Pages/Components/Button/ButtonPage.razor

Under the elevation header on the [Button doc page](https://mudblazor.com/components/button#filled-buttons-elevation), the text button example was displayed instead of the elevation example.
Before
After

Docs: fix incorrect component rendered for button elevation example

---

src/MudBlazor/Components/DataGrid/MudDataGrid.razor
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
src/MudBlazor/Components/Virtualize/MudVirtualize.razor
src/MudBlazor/Components/Virtualize/MudVirtualize.razor.cs

Add overscan parameter in MudDataGrid to be able to avoid as much as possible the empty area of the virtualization when scrolling.  
For that i had to add the parameter to the MudVirtualize component too.   
I'm working on a GitGraph using the DataGrid and the feed back is not really good when i'm scrolling my graph is hided.
It's just a replication of Blazor virtualization component parameter.

MudDataGrid, MudVirtualize: Add parameter OverscanCount

---

src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListDenseInheritanceTest.razor
src/MudBlazor.UnitTests/Components/ListTests.cs
src/MudBlazor/Components/List/MudListItem.razor
src/MudBlazor/Components/List/MudListItem.razor.cs

Fixes #4861 
> When specifying Dense="true" for MudList, the items in the NestedList are not dense.
The issue comes from the fact that the MudListItem adds the `mud-list-item-dense` CSS class only if its `Dense` parameter or the parent MudList `Dense` parameter value is `true`, but since the NestedList is encapsulated in a new MudList which don't define the `Dense` parameter, all the MudListItem's in the NestedList are ignoring it.
I defined the `Dense` parameter of the new `MudList` using the exact same logic that is used to add the `mud-list-item-dense` CSS class to the MudListItem
By correcting this issue, I may have found something more about the `Dense` parameter and maybe other properties like that in general.
By the way the CSS class is added (which I used to fix the issue just to …

MudList: Nested Lists inherit Dense setting (#4861)

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest8.razor
src/MudBlazor.UnitTests/Components/TableTests.cs
src/MudBlazor/Components/Table/MudTable.razor.cs
src/MudBlazor/Components/Table/MudTableBase.cs
src/MudBlazor/Components/Table/TableContext.cs

This PR fixes a bug where removing items from the Items collection would not remove them from the SelectedItems hashset, leading to odd behavior. For example, if all items are selected and an item is removed, the header checkbox will uncheck, as the number of selected items becomes *greater* than the items.
unit

MudTable: Ensure selection is updated when items are removed

---

src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormAutomaticValidationTest.razor
src/MudBlazor.UnitTests/Components/FormTests.cs
src/MudBlazor/Base/MudFormComponent.cs
src/MudBlazor/Components/Form/MudForm.razor.cs
src/MudBlazor/Interfaces/IFormComponent.cs

Resolves #5370 
This PR modifies the Form and base FormComponent to only set `Validation` if `For` is already set. This prevents "For is null" errors from occurring when the user did not intend to set `Validation` in the first place.
I have added a unit test.

MudForm: Only set Validation if For is set

---

src/MudBlazor/Components/Form/MudForm.razor.cs

Due to the logic of the `MudForm`, any components which are added following the form's initialization will not receive the Validation rule of the form. This PR resolves this by moving the Validation set logic to the Form `Add` method, so it is set on the subscription of a form control.
All existing unit tests pass. If desired, I can add a unit test for the scenario of showing a form control after form initialization. Previously, validation would not be set.

MudForm: Assign Validation to Form controls on subscribe

---

src/MudBlazor/Components/Drawer/MudDrawer.razor
src/MudBlazor/Components/Drawer/MudDrawer.razor.cs

I was looking at trimming I saw that MudDrawer was using. JSInterop for mouse events when better solutions exists.
This can be removed without loss of functionality and reduces complexity.
This simplifies MudDrawer
Also as a side affect
Fixes https://github.com/MudBlazor/MudBlazor/issues/4608
Run test suite
Visual between dev.mudblazor.com and my local docs.
Set breakpoint on Event to check code is executing
@henon this also raises the question of the future of 
https://github.com/MudBlazor/MudBlazor/blob/4c58658ccef766bd58333cce4fbd9e40e23db8c3/src/MudBlazor/Extensions/ElementReferenceExtensions.cs#L81
Which is now only used in `MudCollapse`.
The reflection used to pass parameters to event registration doesn't seem to be trim friendly and I think we or users can use other methods with …

MudDrawer: Remove event listeners

---

src/MudBlazor.UnitTests/Components/CollapseTests.cs
src/MudBlazor/Components/Collapse/MudCollapse.razor
src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
src/MudBlazor/Interop/EventHandlers.cs

I was looking at trimming I saw that MudCollapse was using. JSInterop for animation events when better solutions exists.
This can be removed without loss of functionality and reduces complexity.
This simplifies MudCollapse
Run test suite
Visual between dev.mudblazor.com and my local docs.
Set breakpoint on Event to check code is executing
@henon This is the last use of AddEventListener ElementReferenceExtension.
I realise its public API but I would suggest we don't want our users using JSInterop unecessarily when other better soluitions exist
I therefore propose we remove this functionality since it is no longer used in the library.

MudCollapse: Remove event listeners

---

src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedTest.razor
src/MudBlazor.UnitTests/Components/DataGridTests.cs
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs

fixes #5404.
When DataGrid.ExpandAllGroups is called, it does not persist current _groupExpansions,
so when items source changed, current group expansions are not preserved.
unit

MudDataGrid: ExpandAllGroups (persist group expansions)

---

src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEventCallbacksTest.razor
src/MudBlazor.UnitTests/Components/DataGridTests.cs
src/MudBlazor/Components/DataGrid/MudDataGrid.razor
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs

Add onmousedown callback parameter on DataGrid row to be able to handle the middle and right click.
With only the onclick callback parameter I can't subscribe to the right click event.
I've tested it on my own project.

MudDataGrid: Add onmousedown callback parameter on DataGrid row

---

src/MudBlazor.UnitTests/Mocks/MockScrollServices.cs
src/MudBlazor/Services/Scroll/ScrollManager.cs
src/MudBlazor/TScripts/mudScrollManager.js

This PR adds a `ScrollIntoView` method, which was previously missing from the `ScrollManager`. The closest existing equivalent is `scrollToFragment`, but this function accepts an elementId rather than a CSS selector. This implementation takes the first instance of the CSS selector and scrolls it into view, if it exsists.
If desired, this functionality could be used to implement a scroll to error feature on the MudForm.
None. I do not see any tests for the other scroll manager methods either. Should these be excluded from coverage?

ScrollManager: Add ScrollIntoView

---

src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAdvancedExample.razor
src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridDetailRowExample.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridHierarchyColumnTest.razor
src/MudBlazor.UnitTests/Components/DataGridTests.cs
src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
src/MudBlazor/Components/DataGrid/MudDataGrid.razor
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs

Resolves #5500 and also the problem brought up in #5273 
I have brought back the old `ChildRowContent` behavior as it was until 6.0.16. 
**The only change from that behavior is that, by default, the `ChildRowContent` will span for all the datagrid width.**
I have also added the possibility to disable the toggle button in the `HierarchyColumn`.
It is a func so it works indipendently for each row.
I have also added a new section in the DataGrid Examples since now we have some functionalities in the `HierarchyColumn`.
Unit tested and visually tested.

MudDataGrid: Fix HierarchyColumn behavior

---

src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormFieldChangedPickerTest.razor
src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormFieldChangedTest.razor
src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
src/MudBlazor.UnitTests/Components/FormTests.cs
src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
src/MudBlazor/Components/DatePicker/MudDatePicker.cs
src/MudBlazor/Components/Picker/MudPicker.razor.cs
src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs

This PR grew out of its original scope. It started as a refactoring of the FieldChanged event triggering, which is more appropriately placed in each picker component than in the Picker base class. This fixes a DatePicker bug in #4801 where the FormFieldChanged event would not fire when selecting a date.
However, I realized that the ColorPicker does not override `StringValueChanged`, which results in this bug:
https://try.mudblazor.com/snippet/GuGcblYVBfPxlilE
Try pasting a value like `#180f6fff`. It will only update the string value. If you use the color picker popup, both the string and MudColor values are updated. 
This was fixed by implementing `StringValueChanged` like so, but it breaks a unit test:
```csharp
protected override Task StringValueChanged(string value)
{
Value = new …
```

Picker: Improve test coverage and fix ColorPicker bug

---

src/MudBlazor.Docs/Pages/Customization/DefaultTheme.razor
src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesCustomExample.razor
src/MudBlazor.Docs/Theme/Theme.cs
src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
src/MudBlazor/Themes/Models/Palette.cs
src/MudBlazor/Themes/Models/PaletteDark.cs
src/MudBlazor/Themes/MudTheme.cs

CustomTheme: Use custom dark mode without having to define all default settings.
In the current version we have to define the dark mode like the version below. All settings are copied from the internal function `Palette.ConvertToDarkTheme` and only a couple are changed for my theme.
```
MudTheme _myTheme = new ()
{
PaletteDark = new Palette()
{
Primary = (MudColor) "#9dbc21",//(MudColor) "#776be7",
Black = (MudColor) "#27272f",
Background = Colors.Grey.Darken4,//(MudColor) "#32333d",
BackgroundGrey = (MudColor) "#27272f",
Surface = Colors.Grey.Darken3,//(MudColor) "#373740",
DrawerBackground = (MudColor) "#27272f",
DrawerText = (MudColor) "rgba(255,255,255, 0.50)",
DrawerIcon = (MudColor) "rgba(255,255,255, 0.50)",
AppbarBackground = (MudColor) "#27272f",
AppbarText = (MudColor) …
```

Theming: Easier customization of dark mode

---

src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFormFieldChangedTest.razor
src/MudBlazor.UnitTests/Components/DataGridTests.cs
src/MudBlazor/Components/DataGrid/MudDataGrid.razor
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs

This PR adds a `FormFieldChanged` event to the DataGrid. It directly passes the event args from the internal MudForm, and is only supported in the Form edit mode.
I have added a unit test.

DataGrid: Add `FormFieldChanged` event

---

src/MudBlazor/Components/Snackbar/SnackbarMessage.cs

Fixes https://github.com/MudBlazor/MudBlazor/issues/5695
Due to new dynamic behaviour of the SnackBarMessage where it now uses potentially 1 of 2 components at runtime I have added trimming annotations to support this senario
Publish to
https://mudblazor-test.azurewebsites.net/components/snackbar#api

Snackbar: Fix break due to trimming of SnackbarMessageType

---

src/MudBlazor/Components/DataGrid/Column.cs
src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs

Fixes #5469 
The reference to the DataGrid in FilterDefinition was set only when the FilteredItems were iterated.
I have added the reference to the DataGrid whenever a FilterDefinition is created.
(Maybe in the .net 7 it could be solved with the required modifier)

MudDataGrid: Fix missing DataGrid reference in FilterDefinition

---

src/MudBlazor/Components/Snackbar/SnackbarService.cs

In the `Remove()` method of SnackbarService.cs I've changed the order of two statements as to fix a memory leak:
Before:
```csharp
snackbar.Dispose();
snackbar.OnClose -= Remove;
```
After:
```csharp
snackbar.OnClose -= Remove;
snackbar.Dispose();
```
Live on our internal app for a couple of months now.

Snackar: Fix memory leak upon Dispose

---

src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs

The ColorPicker component with ColorPickerMode.HEX displays a MudTextField to enter the HEX color as a string value.
When setting ColorPicker.DisableAlpha to true, one would expect that the ColorPickers HEX MudTextField would only accept six digit HEX color values, which is not the case. The issue is that a user could enter an 8 digit HEX value even when ColorPicker.DisableAlpha has been set to true which leads to a confusing state of the control...
Example with ColorPicker.ColorPickerMode=ColorPickerMode.HEX and ColorPicker.DisableAlpha=true:
- If user enters '#0000ff00' 8 digit HEX value, ColorPicker.Value will be set to '#0000ff00'
- The ColorPicker HEX MudTextField displays a 6 digit HEX value (which does not represent the correct color value)
- The ColorPicker color preview displays …

MudColorPicker: Fix MaxLength on HEX TextField for transparent colors
